### ISSUE TITLE
Remove letters from version ("v1.1.2" -> "1.1.2")

### ISSUE THREAD

**Issue by demalexx** [nithinmurali/pygsheets#101]
Please remove letter "v" from version: should be "1.1.2", not "v1.1.2". With letter in version I can't build .deb package - it complains that version doesn't start with digit.

**Comment by nithinmurali** [comment]
It was added as GitHub suggests  “prefix your version names with the letter v?”. But [apparently](https://stackoverflow.com/questions/37781073/why-github-suggest-prefix-your-version-names-with-the-letter-v) its a former  former SEMVER practice. Will change it.
