### ISSUE TITLE
wks.get_named_range doesn't work for named ranges that encompass entire columns

### ISSUE THREAD

**Issue by zevaverbach** [nithinmurali/pygsheets#105]
Let's say `my_named_range` is `my_sheet!C:C`.

        >>> wks.get_named_ranges('my_named_range')

        ...pygsheets/worksheet.py in get_named_ranges(self, name)
        689             return nrange
        690         else:
    --> 691             nrange = [x for x in self.spreadsheet.named_ranges if x['name'] == name and x['range']['sheetId']==self.id]
        692             if len(nrange) == 0:
        693                 self.spreadsheet.update_properties()

        ...pygsheets/worksheet.py in <listcomp>(.0)
        689             return nrange
        690         else:
    --> 691             nrange = [x for x in self.spreadsheet.named_ranges if x['name'] == name and x['range']['sheetId']==self.id]
        692             if len(nrange) == 0:
        693                 self.spreadsheet.update_properties()

        KeyError: 'sheetId'

**Comment by nithinmurali** [comment]
Pushed a fix. Please verify if it solves your issue.

**Comment by zevaverbach** [comment]
Thanks for the quick fix!  Verified. 🙇
