### ISSUE TITLE
UnicodeEncodeError when localized Error Message

### ISSUE THREAD

**Issue by llange** [nithinmurali/pygsheets#106]
While using the master branch, I hit an UnicodeEncodeError when the return Error Message has non-ASCII characters : 
```
File "myproject.py", line 118, in <module>
    wks = document.add_worksheet("new sheet2", rows=50, cols=10)
  File "..../lib/python2.7/site-packages/pygsheets/spreadsheet.py", line 173, in add_worksheet
    result = self.client.sh_batch_update(self.id, request, 'replies/addSheet', False)
  File "..../lib/python2.7/site-packages/pygsheets/client.py", line 401, in sh_batch_update
    return self._execute_request(spreadsheet_id, final_request, batch)
  File "..../lib/python2.7/site-packages/pygsheets/client.py", line 415, in _execute_request
    if str(e).find('timed out') == -1:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 225: ordinal not in range(128)
```
(To reproduce with the same error message, create a worksheet with the same name as an already existing one, in a French account)

In that case the error message is
```
"Invalid requests[0].addSheet: Une feuille nommée "new sheet2" existe déjà. Veuillez saisir un autre nom."
```
(The characters 'é' and 'à' are encoded and do not work well with `str(e)`)
Replacing `str(e)`by `unicode(e)` fixes this UnicodeEncodeError but may not be the most clean way to correct the issue (as the error message is wrapped and there may be side effects)

**Comment by nithinmurali** [comment]
I am not really sure what is the best way to solve this issue. Any suggestions are welcome.

In the code i am trying to find out if a timeout has occurred by searching for the word `timed out` in the error message. But apparently if the error message is not English this wont work, moreover even converting error message to `str()` wont work.

**Comment by axil** [comment]
Did you try `repr(e).find('timed out')`?

**Comment by axil** [comment]
No you're not:

https://github.com/nithinmurali/pygsheets/blob/274bf51d90e79b5ffd13622952a160ebc0b109b1/pygsheets/client.py#L441

You're using `str(e)` which raises an `UnicodeError` when the message is in French. And `repr(e)` will not raise a UnicodeError. 

`repr(e)` instead of `str(e)` will solve this issue because it has nothing to do with timeout.

As for the timeout, Wieschie's approach looks reasonable to me. Can you recall a situation when it didn't work for you?

**Comment by nithinmurali** [comment]
Ahh, Thanks for pointing that out. No, I don't remember which exception it was (maybe urllib2 timeout). I guess for now i will incorporate your suggestion.
