### ISSUE TITLE
Get col/row/values/all_values functions return not filled Cell objects

### ISSUE THREAD

**Issue by demalexx** [nithinmurali/pygsheets#107]
I'd like to get all the cells from spreadsheet and e.g. use this:
```python
cells = sheet.get_all_values(returnas='cell')
```
But returned Cell objects aren't fully populated. I see in lib code that Cell objects created from simple values that Spreadsheet API returns as list of strings. That cells don't have correct `unformatted_value`, `color` and other attributes. I need to manually call `cell.fetch()` to get this info.

So it'd be cool if you could return complete Cell objects, so user don't need to call `fetch` on each of them.

(It'd be also cool to update docs and mention that issue when `returnas='cell'`)

**Comment by nithinmurali** [comment]
This would be nice feature indeed. 

This can be implemented by two changes, 
- In `get_values` function, use `sh_get_ssheet` to get the whole cell data and init cells.
- Change the cell to be able to be initialized by json object

**Comment by nithinmurali** [comment]
Please verify , if this works for you.

**Comment by demalexx** [comment]
Seems working, thanks!
