### ISSUE TITLE
set_dataframe - need help/guidance

### ISSUE THREAD

**Issue by jainraje** [nithinmurali/pygsheets#109]
Currently I am successfully writing my DF to google sheets using the following code:

wks.set_dataframe(df, (1, 1), fit=True)

The fit=True was working well for my initial situation. However, I've now modified the worksheet to add several columns to the right of the area the DF is written. With fit=True the content to right of the DF are lost. With fit=False the content to the right are untouched ( which is what I want) but the rows below the DF contain content from prior writes (which I do not want...those should be cleared before the above set_dataframe call).

I tried unsuccessfully using the named range feature to solve. Perhaps I didn't code it correctly. 

How about modify the fit=True to provide options to fit=col, fit=row or fit=True (for both)

I'm sure you have a simple and clean solution. Please advise. 

Please let me know if you require more info or would like me to test anything.

TIA

**Comment by jainraje** [comment]
I came up with a solution which appears to be working for me. 

I found the resize method:
wks.rows=df.shape[0]+1

I'll leave this open for any comment from you otherwise please close.

**Comment by nithinmurali** [comment]
I think for changing one dimension, manual fixing will do. Can add that option to library if more ppl has this requirement.
