### ISSUE TITLE
Returning inf for rows with scientific looking format

### ISSUE THREAD

**Issue by schwallie** [nithinmurali/pygsheets#111]
I made a sheet with:

> Column
> 06E59641803036524

The package returns:
```
                                               Column
0                                                 inf
```

When I use the "get_as_df" function

**Comment by schwallie** [comment]
Learned turning `numerize` to `False` fixes, but prefer to be able to do numerize without this happening as well1

**Comment by nithinmurali** [comment]
I am not really sure if `numerize` should return it as string, because the idea of `numerize` is to convert the 
number values to corresponding python integer/floats , and in python it treats such long numbers as `inf`.

**Comment by schwallie** [comment]
Yea I'm not against it staying that way, in this case. Could be more robust to explain it's going to get converted to inf, but for now we can close this if you're fine with it how it is.
