### ISSUE TITLE
del_worksheet does not work consistently

### ISSUE THREAD

**Issue by tres-pitt** [nithinmurali/pygsheets#113]
Here it is:
    all_ws=tables.worksheets()
    for ws in all_ws:
        tables.del_worksheet(ws)

The thing is, this doesn't delete every sheet. The first time, it will reduce the number of sheets by about half (from 6-3 in my example). Then if you run it a second time, it deletes some more of the sheets, leaving one. (Running it a third time throws an error, which is good and expected behavior).

I'm just looking for a way to reliably clear all cell contents. My idea was to delete sheets then immediately replace them with a sheet of the same title, but this doesn't work. thank you!

**Comment by nithinmurali** [comment]
This looks like a bug. but till this is verified, for your use case there is a `wks.clear()` function which will clear all cells.

**Comment by tres-pitt** [comment]
thanks, that is a better approach anyway. w.r.t. del_worksheet(), I've found that using a while loop with a set equality condition works fine

**Comment by nithinmurali** [comment]
This is not a bug. Here you are trying to delete list items while iterating over the same list. This is a well-documented behaviour in Python, that you aren't supposed to modify the list being iterated through. see [this](https://stackoverflow.com/questions/742371/python-strange-behavior-in-for-loop-or-lists).
