### ISSUE TITLE
get_all_records() contradicts cell()

### ISSUE THREAD

**Issue by tres-pitt** [nithinmurali/pygsheets#114]
consider a three-element sheet a la 1,2,3 (1 row, 3 columns)

called on this worksheet, get_all_records returns [] with len 0
However, if I call the specific cell() reference eg A1, then it does return the correct content, eg <Cell R1C1 u'1'>

Is this expected behavior?

**Comment by nithinmurali** [comment]
As explained in the [docs](http://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.get_all_records) This is used if you have table like spreadsheet. If your sheet is empty it will return empty list. Use get_all_values if you need to fetch all values.
