### ISSUE TITLE
Unable to find the server at accounts.google.com

### ISSUE THREAD

**Issue by waltonereed** [nithinmurali/pygsheets#115]
After I pygsheets.authorize(), I get the webpage and log in to my google account, and everything seems to work. However, after a few seconds, I get the following error code:
`ServerNotFoundError: Unable to find the server at accounts.google.com`

I've tried variations with `no_cache=True`, `outh_nonlocal=True`

**Comment by nithinmurali** [comment]
Please provide more info on your environment

**Comment by waltonereed** [comment]
Running Python 3.6.1150.1013. I've tried this on my personal and corporate Gmail and replicated the same issue.

**Comment by nithinmurali** [comment]
This dosent seem like a pygsheets error. This might be proxy error, see [this](https://stackoverflow.com/questions/18429927/google-calendar-python-api-sample-unable-to-find-the-server-at-accounts-google)

**Comment by waltonereed** [comment]
Thanks Nithin. It turns out Google Drive API has been turned off by my company, hence the error. Thanks!
