### ISSUE TITLE
Get_col + returnas=cell only returns first row

### ISSUE THREAD

**Issue by endast** [nithinmurali/pygsheets#118]
If you use get_col and set return to cell.  All you get back is the first row.

Given a spreadsheet that looks like this:
A   B
1   6
2   7
3   8
4   9
5   10

This code:

```python
import pygsheets
gc = pygsheets.authorize()
sh = gc.open('my new ssheet')
wks = sh.sheet1
col_a = wks.get_col(1, returnas='cell')
col_b = wks.get_col(2, returnas='cell')
print(col_a)
print(col_b)
print(col_a[0].value)
print(col_b[0].value)
```

Returns:

> [<Cell R1C1 '1'>]
> [<Cell R1C2 '6'>]
> 1
> 6

I recreated the get_col function using get_values, but omitted the return index ([0])

And this way i can get all the rows:

```python
col_a = wks.get_values(start=(1,1), end=(wks.rows,1),returnas='cell',majdim='COLUMNS')
col_b = wks.get_values(start=(1,2), end=(wks.rows,2),returnas='cell',majdim='COLUMNS')

print(col_a)
print(col_b)
```

returns:
> [[<Cell R1C1 '1'>], [<Cell R1C2 '2'>], [<Cell R1C3 '3'>], [<Cell R1C4 '4'>], [<Cell R1C5 '5'>]]
> [[<Cell R1C2 '6'>], [<Cell R1C3 '7'>], [<Cell R1C4 '8'>], [<Cell R1C5 '9'>], [<Cell R1C6 '5'>]]

But i don't get a list of cells, but instead a list of of lists of length 1, containing 1 cell.
And the labels are wrong (but not the values...)

```python
print("Col A")
for cell in col_a:
    print("Label: {}, cell: {}".format(cell[0].label, cell[0].value))

print("Col B")
for cell in col_b:
    print("Label: {}, cell: {}".format(cell[0].label, cell[0].value))
```

returns
> Col A
> Label: A1, cell: 1
> Label: B1, cell: 2
> Label: C1, cell: 3
> Label: D1, cell: 4
> Label: E1, cell: 5
> Col B
> Label: B1, cell: 6
> Label: C1, cell: 7
> Label: D1, cell: 8
> Label: E1, cell: 9
> Label: F1, cell: 5

**Comment by endast** [comment]
I tested rewriting parts of get_col and get_values, and this seems to solve the problem. The tests passes (except online_test.py::TestWorkSheet::test_set_dataframe FAILED). But i'm not familiar enough with the code to know if i'm doing something bad here :) 
 
https://github.com/endast/pygsheets/commit/a86599a0457903934f0795994996e16959e2a556

```python
import pygsheets

gc = pygsheets.authorize()

# Open spreadsheet and then worksheet
sh = gc.open('my new ssheet')
wks = sh.sheet1

col_a_cell = wks.get_col(1,returnas="cells")
col_b_cell = wks.get_col(2,returnas="cells")

print("Col A")
for cell in col_a_cell:
    print(cell.label)
    print(cell.value)

print("Col B")
for cell in col_b_cell:
    print(cell.label)
    print(cell.value)```

> Col A
> A1
> 1
> A2
> 2
> A3
> 3
> A4
> 4
> A5
> 5
> Col B
> B1
> 6
> B2
> 7
> B3
> 8
> B4
> 9
> B5
> 10

**Comment by nithinmurali** [comment]
Hi, on first look your solution would work fine; Will have to see why exactly the test case is failing though. 

But, we shouldn't change the `get_col`, its the `get_value`'s responsibility to give the data in right format. Here what is happening is, `get_values` is giving the data in `ROW major` form even though the `COLUMN major` form was asked. If you take  a look at the code at [L245](https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/worksheet.py#L245) it not passing the majdim param to the api call, nor is it converting the form later. So the ideal solution is to check the majdim and convert it from one form to another here. Or change [this](https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/worksheet.py#L269) loop appropriately this is where the value are created and this assumes its is right form.
