### ISSUE TITLE
Append_table shows error

### ISSUE THREAD

**Issue by hnchan** [nithinmurali/pygsheets#120]
When I try to execute the append_table with a new created sheet. It shows the following error

`        wks.append_table(values=append_value)
`
"Requested writing within range ['2017-09-08 18:21'!A1], but tried writing to column [B]"

What is the problem? Thanks.

**Comment by nithinmurali** [comment]
Hey, can you please elaborate on how to reproduce the issue? sample data of `append_value` will do.

**Comment by hnchan** [comment]
Thanks, I think I figure out the problem too. I try to append_table under an empty sheet. Now, I use insert_rows instead. Thanks again.
