### ISSUE TITLE
Batch not working?

### ISSUE THREAD

**Issue by vdecine** [nithinmurali/pygsheets#127]
Hi,

I am trying to clean a worksheet and add 800 lines. My code is as follows:

```
gc = pygsheets.authorize(service_file='/path/to/file.json')
sheet = gc.open_by_key('key')
wsheet = sheet.worksheet_by_title('Name')
wsheet.clear()


sheet.batch_start()
line_count = 0
for line in lines:
  line_count += 1
  wsheet.update_row(line_count, line)
sheet.batch_stop()
```

Doing this I run into the API Limit of 100 writes in 100 seconds. As I understand it, batch update should prevent this? As a workaround I added a time.sleep(1) inside the loop, which causes timeouts even if I increase the timeout in httplib2. Is this a bug or am I approaching the problem completely wrong?

**Comment by nithinmurali** [comment]
Currently the batch mode won't merge identical update requests, if will only save the requests and will update them in one go. Though this is a planned feature. currently you can just append the lines to a list and update the list. This would be both faster and efficient in terms of api.
```
for line in lines:
  line_count += 1
  all_list.append([line_count, line]) # take care of format here
wsheet.update_cells("A1", all_list)
```

**Comment by vdecine** [comment]
I was suspecting I was doing something wrong. Thank you very much!
