### ISSUE TITLE
Support overriding the default valueInputOption

### ISSUE THREAD

**Issue by mauryfs** [nithinmurali/pygsheets#139]
Currently the default valueInputOption value is 'USER_ENTERED' on the sh_update_range and sh_append.

I would like to be able to override the default value of valueInputOption, so that all sheet operations update with 'RAW' by default.

This would allow for functions like Worksheet.update_row to operate in 'RAW' and still omit the 'parse' argument on the update_cells call.

**Comment by nithinmurali** [comment]
Implemented in staging branch. Please verify if this works for you.

**Comment by mauryfs** [comment]
Not too familiar with the code review process, but I left a few comments on the commit. Hopefully they are appropriate.  Will test when comments are fixed or dismissed. Thanks!

**Comment by mauryfs** [comment]
Works great. Thank you.
