### ISSUE TITLE
Support sleeping to throttle API requests

### ISSUE THREAD

**Issue by dgilman** [nithinmurali/pygsheets#143]
Have some optional parameters to the Client class to record the last time of a read or write API call and sleep until the next one is ready.  Right now I can work around it with my own bookkeeping but it seems like the pygsheets library is the correct place to handle this.

**Comment by nithinmurali** [comment]
Hey, your statements are a bit ambiguous, can you please explain a bit more? Are saying there should be an option to keep api call limit? What so you mean by `sleep`

**Comment by dgilman** [comment]
No problem. The idea is inspired by the twitter API, see http://python-twitter.readthedocs.io/en/latest/rate_limits.html . But as for implementation, I see two different ways of doing this:
- Let people call APIs and note the number of calls and the time when they reset (the time of the first call + Google's throttle time).  If you run up against this (in the default configuration, you make the 101st call in less than 100 seconds) you sleep until the reset time is up and reset the counter.
- You figure out the average call rate. Google's default of 100 calls in 100 seconds would be 1 call/second. Record the time someone makes a call and if they go to make a second call in under 1 second since the previous one sleep to round that out to 1 second per call.

For regular, blocking clients it is probably fine to just whip out a call to time.sleep() but if you're up and running on python3 I am sure asyncio users would also like it if you did an asyncio.sleep().

**Comment by Kordishal** [comment]
This can be closed no?

**Comment by nithinmurali** [comment]
Closing, as this has been implemented by @Kordishal
