### ISSUE TITLE
Spreadsheet not found after a while

### ISSUE THREAD

**Issue by cachho** [nithinmurali/pygsheets#144]
My script uses
`gc = pygsheets.authorize(outh_file='client_secret.json')`
`sh = gc.open('Spreadsheet')`
`wks = sh.worksheet_by_title('Log')`
every half an hour or so. After a couple loops it returns an error and `print(sh)` returns the number of worksheets in the spreadsheet as 1, although it should be 9.
To fix i have to rename the spreadsheet, close it, open it and rename it back. That is very unfortunate because I want my script to run 24/7 without having to act. My internet connection shouldn't be a problem, especially because after it fails to get the worksheet, it tries again after a while and it gives me the error for hours. Thanks for any help.

**Comment by ytidhar** [comment]
Please note that by default the credentials are expired  after 60 minuts.
did you try to authorize in the loop or only once?

**Comment by cachho** [comment]
I do authorize inside the loop. And even if we imagine 1 loop takes an hour, if i restart the whole script it does not successfully authorize.

**Comment by nithinmurali** [comment]
What is the exact error? Does the same happen with a OAuth Credentials?

**Comment by cachho** [comment]
I solved the issue by switching to "open_by_key" instead of through the title. It's complicated but it's 100% reliable so far.
