### ISSUE TITLE
Request timeout error on cells update

### ISSUE THREAD

**Issue by kid911** [nithinmurali/pygsheets#145]
Hi! 

I'm constantly getting Timeout exception on following block of code:
```
        for test in results.keys():
            if mapping[test] != "":
                wks.update_cells(wks.find(mapping[test])[0].neighbour('right').label, [results[test]])
```

It is trying to process following set of data one-by-one:
```
{'calendarOpenEventDetailsTest': ['2.2', '1.59', '1.62', '1.7', '1.65'], 'calendarOpenDayViewTest': ['0.33', '0.3', '0.29', '0.31', '0.33'], 'switchingBetweenMonthsTest': ['0.33', '0.31', '0.28', '0.3', '0.28'], 'calendarDeleteEventTest': ['3.2', '3.08', '3.13', '2.87', '3.26'], 'calendarCreateEventTest': ['1.14', '0.88', '1.09', '1.03', '0.9'], 'switchingBetweenDaysTest': ['0.19', '0.2', '0.19', '0.2', '0.22'], 'calendarOpenMonthViewTest': ['0.44', '0.38', '0.43', '0.39', '0.41'], 'calendarOpenAgendaViewTest': ['0.43', '0.38', '0.31', '0.39', '0.38'], 'switchingBetweenWeeksTest': ['0.2', '0.22', '0.23', '0.21', '0.18'], 'calendarOpenWeekViewTest': ['0.28', '0.29', '0.3', '0.37', '0.29']}
{'createContactPerfTest': ['2.28', '1.84', '2.16', '1.47', '1.72'], 'contactsDetailsPerfTest': ['0.36', '0.31', '0.32', '0.31', '0.32'], 'scrollingContactsTest': ['3.825', '3.795', '3.785', '3.925', '3.895'], 'thousandMatchesContactsSearchPerfTest': ['1.82', '1.84', '1.89', '1.83', '1.81'], 'maxMatchesContactsSearchPerfTest': ['1.96', '2.16', '2.15', '2.27', '2.04'], 'removeContactPerfTest': ['1.63', '1.52', '1.42', '1.34', '1.4'], 'hundredMatchesContactsSearchPerfTest': ['3.33', '3.27', '3.23', '3.31', '3.33'], 'tenMatchesContactsSearchPerfTest': ['3.12', '3.1', '3.12', '0.15', '3.16'], 'openContactsListPerfTest': ['0.19', '0.16', '0.18', '0.17', '0.18']}
{'selectingEmailTest': ['0.68', '0.7', '0.5', '0.625', '0.475'], 'emailAllFoldersPerfTest': ['0.72', '0.66', '0.59', '0.57', '0.59'], 'markingEmailUnreadTest': ['1.27', '1.2', '0.89', '1.09', '1.18'], 'scrollingEmailTest': ['4.195', '3.775', '3.805', '3.83', '3.81'], 'oneMatchesEmailSearchingTest': ['0.4', '0.23', '0.28', '0.22', '0.22'], 'emailDetailsPerfTest': ['1.31', '1.34', '1.4', '1.07', '1.41'], 'markingEmailReadTest': ['0.58', '0.78', '0.85', '0.74', '0.99'], 'maxMatchesEmailSearching': ['0.88', '0.72', '0.71', '0.62', '0.6'], 'hundredMatchesEmailSearchingTest': ['1.08', '2.06', '0.98', '0.99', '1.12']}
{'oneMatchesTaskSearchingTest': ['1.33', '1.03', '1.14', '0.93', '1.06'], 'taskListOpenPerfTest': ['0.74', '0.67', '0.91', '0.72', '0.81'], 'taskDetailsPerfTest': ['0.41', '0.38', '0.31', '0.37', '0.33'], 'scrollingTasksTest': ['3.765', '3.725', '3.72', '3.73', '3.725'], 'deleteTaskPerfTest': ['1.07', '1.03', '0.95', '1.01', '0.92'], 'markingSingleTaskAsCompleteIncompletePerfTest': ['0.26', '0.37', '0.3', '0.33', '0.295'], 'createTaskPerfTest': ['0.44', '0.43', '0.41', '0.44', '0.39'], 'selectingTaskPerfTest': ['0.375', '0.39', '0.465', '0.385', '0.395'], 'hundredsMatchesTaskSearchingTest': ['1.14', '1.11', '0.97', '0.99', '0.94']}

```
And fails with following stacktrace:

> 15:16:08 Traceback (most recent call last):
> 15:16:08   File "PerfParser_new.py", line 57, in <module>
> 15:16:08     upload_test_results()
> 15:16:08   File "PerfParser_new.py", line 47, in upload_test_results
> 15:16:08     wks.update_cells(wks.find(mapping[test])[0].neighbour('right').label, [results[test]])
> 15:16:08   File "/Library/Python/2.7/site-packages/pygsheets/worksheet.py", line 653, in find
> 15:16:08     self._update_grid(force_fetch)
> 15:16:08   File "/Library/Python/2.7/site-packages/pygsheets/worksheet.py", line 118, in _update_grid
> 15:16:08     self.data_grid = self.get_all_values(returnas='cells', include_empty=False)
> 15:16:08   File "/Library/Python/2.7/site-packages/pygsheets/worksheet.py", line 301, in get_all_values
> 15:16:08     majdim=majdim, include_empty=include_empty)
> 15:16:08   File "/Library/Python/2.7/site-packages/pygsheets/worksheet.py", line 246, in get_values
> 15:16:08     ranges=self._get_range(start, end))
> 15:16:08   File "/Library/Python/2.7/site-packages/pygsheets/client.py", line 338, in sh_get_ssheet
> 15:16:08     return self._execute_request(spreadsheet_id, request, False)
> 15:16:08   File "/Library/Python/2.7/site-packages/pygsheets/client.py", line 423, in _execute_request
> 15:16:08     raise RequestError("Timeout")
> 15:16:08 pygsheets.exceptions.RequestError: Timeout

I've already tried to add pygsheets.client.GOOGLE_SHEET_CELL_UPDATES_LIMIT = 20000, but it doesn't solve problem.

**Comment by nithinmurali** [comment]
Updated the code to show exact timeout error. Please post the new outputs

**Comment by nithinmurali** [comment]
Closing as no response
