### ISSUE TITLE
sheet.update_cells(cell_list, values) does not update values

### ISSUE THREAD

**Issue by DavisMerrit** [nithinmurali/pygsheets#151]
I've tried to get any results with
```
my_cells = [sh.cell('A1'), sh.cell((1, 2))]
my_values = [["value_A1", "value_B1"]]
sh.update_cells(cell_list = my_cells, values = my_values)
```
Does it work or maybe i'm doing something wrong here?

**Comment by nithinmurali** [comment]
you can't use cell list and values together. if you are using cell list, then store the values in cells itself. if you are using values then give range (A1:C5)  and values(as matrix) . please see the examples in readme and see the documentation of update_cells

**Comment by nithinmurali** [comment]
Maybe we should raise an exception when both values and cell_list  are given.

**Comment by DavisMerrit** [comment]
Yeah. That's a god idea to raise an exception when both value are given.
Anyway, how I can assign value to a cell?
If I do 
`sh.cell('A1').value = "value_A1"`
it will immediately update my A1 cell. But if I have 1000 values it would be too slow to update cell by cell. That's why I want to use
`sheet.update_cells(cell_list)`

**Comment by nithinmurali** [comment]
cell_list internally updates the cells one by one (an optimization is in the pipeline) . Its better you fill the matrix whenever needed and in the end update the sheet using matrix with update_cells.
