### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by applehawk** [nithinmurali/pygsheets#164]
imax_range = pygsheets.DataRange(start=top_left_addr, end=bottom_right_addr)
  File "/usr/local/lib/python3.6/site-packages/pygsheets/datarange.py", line 42, in __init__
    if len(data) != end[0] - start[0] + 1 or len(data[0]) != end[1] - start[1] + 1:
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by nithinmurali** [comment]
fixed in staging branch, will be pushed to master. Please install from staging to get the fix
