### ISSUE TITLE
worksheet.update_cells() ignores cell color and formating

### ISSUE THREAD

**Issue by mateuszdrwal** [nithinmurali/pygsheets#165]
here is a code snippet which should explain the bug:
```python
>>> cell = pygsheets.Cell("A1")
>>> cell.color = (0, 1, 0, 1)
>>> worksheet.update_cells(cell_list=[cell])
#cell A1 is still white, should be green if worksheet.update_cells properly updated the cell
>>> cell.link(worksheet)
<Cell R1C1 ''>
>> cell.color = (0, 1, 0, 1)
#cell color is now green
```
the same also applies if you replace `cell.color = (0, 1, 0, 1)` with `cell.set_text_alignment("CENTER")`

**Comment by nithinmurali** [comment]
Currently `update_cells` only update the cell values, not other properties

**Comment by mateuszdrwal** [comment]
well, I assumed I was a bug because it does seem like a fairly important feature, updating cells one by one is not feasible for some applications (like mine: 240 cells to color, average request time is 2s, +2*240=480s=8min vs average 1 second for `update_cells`)

**Comment by applehawk** [comment]
The same situation:
I'm create cell_list
self.cell_list = [pygsheets.Cell(pos=((i-1)//columns+1,(i-1)%columns+1)) for i in range(1,columns*rows)]

And configure cell:
      cell.value = text
      cell.row = cell_row_idx
      cell.col = cell_column_idx
      cell.color = (0.0, 1.0, 1.0, 1.0)
      cell.text_format["foregroundColor"] = {"red": 1.0, "green": 0, "blue": 0}

  def end_cell_writing(self):
    #pprint.pprint(self.cell_list)
    self.wks.update_cells(crange=self.cell_range, cell_list=self.cell_list)

Nothing changed !

How can I updates 100 x 8 cells immediately, if that updates each 10 seconds?

**Comment by applehawk** [comment]
This method, which I created very slowly!

  def color_range(self, scolumn, srow, ecolumn, erow, color):
    cell = pygsheets.Cell(pos="A1")
    cell.color = color
    top_left_addr = '%s%d'%(colnum_string(scolumn), srow)
    bottom_right_addr = '%s%d'%(colnum_string(ecolumn), erow)
    srange = "%s%d:%s%d"%(colnum_string(scolumn), srow, colnum_string(ecolumn), erow)
    imax_range = self.wks.get_values(top_left_addr, bottom_right_addr, returnas='range',include_empty=True, include_all=True) #pygsheets.DataRange(start=(scolumn, srow), end=(ecolumn, erow))
imax_range.applay_format(cell)

**Comment by willianvargas** [comment]
Hello nithinmurali,

`update_cells_prop` is not working for me, there is some special code to update the cells properties?
The code below does nothing on the destination spreadsheet.

```py
# Get a matrix of cells from source tab
cells_matrix = source_sheet.get_values(start=(1,1), end=(1,2), returnas='cell')

# Get the first list from the matrix
cells_list = cells_matrix[0]

# Set the cells on the destination tab
destination_sheet.update_cells_prop(cell_list=cells_list)

**Comment by nithinmurali** [comment]
get_values wont fetch any cell properties, it would only return cells with values set. what property are you trying to update here ?

**Comment by willianvargas** [comment]
I need replicate all the properties from every single cell, like text formatting, colors, notes, etc, to another sheet. With `returnas='cell'` I can get a list of instantiated cells with these properties. So, I'm trying to send this list to the destination sheet with `update_cells_prop`.

**Comment by nithinmurali** [comment]
currently fetching cells with all properties are not implimented, so you will have to call fetch() on each cell before calling `update_cells_prop`.
