### ISSUE TITLE
When creating a SS in a shared folder, it also appears in my home folder. 

### ISSUE THREAD

**Issue by rubenwap** [nithinmurali/pygsheets#183]
I am creating a SS with this:

`sh = gc.create("myFile", parent_id="XXX")`

Where the `parent_id` is a folder shared with me, where I have full permissions, but I don't own it. 

After creating the file, it correctly appears in the specified folder, but it also displays under my home folder. I haven't found any parameter to prevent this. 

Is this expected behavior or can it be considered a bug?

**Comment by nithinmurali** [comment]
This is is not expected behavior. If confirmed this is a bug.

**Comment by rubenwap** [comment]
I did test again and it happens everytime. Hopefully some more users reading this thread could confirm if it happens to them too?

**Comment by nithinmurali** [comment]
I tested it. bug confirmed

**Comment by nithinmurali** [comment]
The Issue is we only adding the shared folder as a parent but not removing the current parent.
