### ISSUE TITLE
value_unformatted not working

### ISSUE THREAD

**Issue by gamerton** [nithinmurali/pygsheets#188]
Date cell with formats 2/5/2018 or 02.05.2018 return formated value on both method:
c1.value return 5-FEB
c1.value_unformatted return 5-FEB
Is it bug? or probably it's possible to get input_value like gspread did

**Comment by nithinmurali** [comment]
You need to do a fetch on the cell before accessing formatted value. Did you do that ?

**Comment by gamerton** [comment]
Hm. sorry with fetch() before getting unformated value a get a raw data that google sheet good converted to viisual format.
But could u help to understand how get input value  2/5/2018 from 43136 that return unformated value or 
How to write universal inputl_value function :)

**Comment by nithinmurali** [comment]
see [this](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#ExtendedValue) and [this](https://developers.google.com/sheets/api/reference/rest/v4/DateTimeRenderOption#ENUM_VALUES.SERIAL_NUMBER).
In short 

> The whole number portion of the value (left of the decimal) counts the days since December 30th 1899.

**Comment by gamerton** [comment]
Thx) Not user frendly but worked
