### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rwrsachinjain** [nithinmurali/pygsheets#191]
I am getting FileNotFoundError: [Errno 2] No such file or directory. Refer attached screenshot

![image](https://user-images.githubusercontent.com/32810198/36942926-6fafe8a8-1fa5-11e8-838e-cc1643f0773a.png)

Please help me to fix this issue

**Comment by mccartney** [comment]
Instead of pasting a screenshot - please paste the full stacktrace as text. And some more information on how to reproduce (your full program text or some other minimal example), etc.

**Comment by robkorn** [comment]
I also just got this error today with code I've been running daily without touching for the past few months and just wanted to mention it's probably not an isolated issue.
I'm really quite busy right now but if nothing gets figured out within the next few days then I'll find some time and look into it/post more info on it as well.

**Comment by diegofdocastro** [comment]
Appending no_cache=True in the authorize call works!

**Comment by nithinmurali** [comment]
This is fixed in the trunk, install form github to get the fix. ref : #100

**Comment by nithinmurali** [comment]
update to latest version 1.1.4 to get the fix
