### ISSUE TITLE
Worksheet.find has inconsistent behavior

### ISSUE THREAD

**Issue by Kordishal** [nithinmurali/pygsheets#197]
When using find to search and replace the behavior is different for when providing a string or a compiled pattern.

- When providing a string only full matches are returned (== comparison)
- When providing a compiled pattern both full and partial matches are returned (pattern.search())
- Replace always replaces the entire cell value even if it is only a partial match.

It would be better to offer consistent behavior. There are a few ways to do this:

1. Change the search with a compiled Regex to only return on full match.
2. Change replacement strategy to replace partial match if a compiled Regex is provided.
3. Expand find function to include a parameter 'full_match=True' and re-implement the function accordingly to always allow for both.
4. Replace find with a search and a full_match function (but keep find for backwards compatibility?)

What would you prefer? I can implement each of them.

**Comment by nithinmurali** [comment]
Currently it is implemented as a wrapper around the findReplace api provided by google. Still its better to have a consistent behavior. I think the best option is (3) to include a full_match parameter.

**Comment by Kordishal** [comment]
Actually you are thinking of Spreadsheet.find(), which is implemented kind of strange as well. What it currently does is just search worksheets (not cells) and return them if replacement is None. Otherwise it does a findReplaceRequest.

Worksheet.find() does not use an API call. I have re-read the docs for findReplaceRequest and it appears to always want to replace, but it might not replace if replacement is None. Would have to test this.

I think it would make sense to make sure to have similar behavior for find on both the spreadsheet and worksheet. I will make some tests to see how the findReplaceRequest works and then suggest a solution.

The implementation in the end should be able to use findReplaceRequests if linked and search locally if unlinked.

The spreadsheet.find function should be able to search through all sheets, a single sheet or a specified GridRange.

The worksheet.find should be able to search through itself or a GridRange within that worksheet.

Each find function should be able to set all parameters of findReplaceRequest (e.g. find, replacement, matchCase, matchEntireCell, searchByRegex, includeFormulas)

**Comment by Kordishal** [comment]
Should the worksheet/sheet be searched if unlinked? I feel just implementing find with the findReplaceRequest for now would be much better and overall more efficient. There are other, better ways to search/replace data if they want to do it offline.

Or do you want to generally move towards a better offline support? But then why use gsheet in the first place?

**Comment by nithinmurali** [comment]
> Actually you are thinking of Spreadsheet.find(), which is implemented kind of strange as well. What it currently does is just search worksheets (not cells) and return them if replacement is None. Otherwise it does a findReplaceRequest.

currently find in spreadsheet will return cells, if the replacement is none.

> Worksheet.find() does not use an API call. I have re-read the docs for findReplaceRequest and it appears to always want to replace, but it might not replace if replacement is None. Would have to test this.

The findReplaceRequest does not gives the search functionality. It never returns the matching cells (from what i have tested). That's is the reason i have implemented the search seprately in the worksheet.find() 

> The implementation in the end should be able to use findReplaceRequests if linked and search locally if unlinked.

Ideally yes, but this is not possible as findReplaceRequests dosent do search.

> The spreadsheet.find function should be able to search through all sheets, a single sheet or a specified GridRange.
> 
> The worksheet.find should be able to search through itself or a GridRange within that worksheet.
> 
> Each find function should be able to set all parameters of findReplaceRequest (e.g. find, replacement, matchCase, matchEntireCell, searchByRegex, includeFormulas)

This can be done.

**Comment by Kordishal** [comment]
> The findReplaceRequest does not gives the search functionality. It never returns the matching cells (from what i have tested). That's is the reason i have implemented the search seprately in the worksheet.find()

I figured that out too ;/

And there really isn't just a find request. It kinda makes sense since these are spreadsheet batchUpdate requests. I feel then it would make more sense to clearly differentiate this behavior. 

E.g. have a findReplace function on Spreadsheet/Worksheet which does its thing and simply returns the findReplaceResponse. This would either always link the sheet or throw an error if unlinked.

And another function find which just does search and return the found cells as a list. Implement this locally only, but update cells beforehand if Spreadsheet/Worksheet is linked. This way people can decide themselves how they want to replace since there are many different possibilities.

**Comment by nithinmurali** [comment]
It dosent make much sense to do a local replacement if the sheet is linked as its very costly. So there might not be much benefit in giving the choice. If we give them two functions for same behavior mostly people will randomly use one, and will later complaint about performance. So i think its better we choose what is best, as i can't find a scenario where they can choose and get something better.

**Comment by Kordishal** [comment]
>  If we give them two functions for same behavior mostly people will randomly use one

I guess this is a good point. I feel the problem is, that there are different ways you can use google spreadsheets in applications. 

One (and I think the most common) is to just have it as data store. So just load data from/save data to it, but not actually use any formatting features or special API calls. The primary concern here is speed and ease of access in different ways (by row, by column, list row-dictionary, entire sheet) and then put the data back once processed. Such a use will also usually just use a single sheet and mostly use a very simple spreadsheet and a simple worksheet model. No need for data ranges or cells. Python dictionaries and lists are much better for storing and handling this kind of data.

A second way is to actually use spreadsheet features and structures. To then better display it in the spreadsheet, use formulas etc. This use needs a way to handle synchronization and good integration with the format properties. And I feel most parts of the module are aimed at this.

A third way would be to not have any data locally, but actually let the spreadsheet handle all the operations. I am not sure if anyone actually does this, but I guess this would be useful for cases where you don't have a lot of computing power locally or need advanced sheets features and do a lot of computations and charts within sheets.

Each need their own model to work well, because currently this module is a bit of a mix of 1 and 2 (which makes a lot of sense), but it would be nicer if we could better separate this. 

It would be possible to do this by having different classes for each model and a common base class. 

For example have a BaseSpreadsheet, SimpleSpreadsheet, Spreadsheet (same as current basically), RemoteSpreadsheet (for requests only). Then people could choose what they want.

Of course to start it slow I would start with creating a SimpleSpreadsheet which supports all the row/col get & update functions, read the entire sheet and have a col/row argument, but nothing more. Then it would also be easier to implement the DictReaderSpreadsheet.

**Comment by Kordishal** [comment]
And I guess my point about this is: 

The find function fits into the second model. Where cells are a special model so it makes sense to provide a function to search it.

While findReplace request would fit the third model where all the computing is done remotely. This is fairly powerful since your machine uses no computing power.

The first model does not really need a find function because these are just lists or dictionaries for which there is a lot of stuff implemented in python or other libraries.

I hope you get my point :)
