### ISSUE TITLE
global name 'flags' is not defined

### ISSUE THREAD

**Issue by jdsinh** [nithinmurali/pygsheets#2]
I got an error
"global name 'flags' is not defined" when I try
gc = pygsheets.authorize()
I guess its from get_credential() method from client.py
I am using python 2.7
can u help with these ?

**Comment by nithinmurali** [comment]
HI @jdsinh , Thanks for reporting this. It should be fixed by now.

**Comment by jdsinh** [comment]
Now the system shows the error

usage: manage.py [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
                 [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                 [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
manage.py: error: unrecognized arguments: runserver

when app is loaded

Please help with this

**Comment by jdsinh** [comment]
if credentials is None or credentials.invalid:
    flags = argparser.parse_args('--auth_host_name localhost --logging_level INFO'.split())
    credentials = run_flow(flow, storage, flags)



I don't know but this might help you fixing this

**Comment by nithinmurali** [comment]
Oops my bad. It was parsing the external arguments too . fixed it

**Comment by nithinmurali** [comment]
closing the issue as this seems fixed, reopen if necessary.
