### ISSUE TITLE
Problem when making executable

### ISSUE THREAD

**Issue by mblom122** [nithinmurali/pygsheets#200]
Hi, the module works just fine when using on my pc where I have installed python. It manages to save to my drive just fine. But when I make an executable with pyinstaller, the program wont run on my other machine. I get the error:
  File "site-packages\pygsheets\client.py", line 599, in authorize
  File "site-packages\pygsheets\client.py", line 75, in __init__
IOError: [Errno 2] No such file or directory: 'C:\\Users\\MICKE-~2\\AppData\\Loc
al\\Temp\\_MEI67~2\\pygsheets\\data\\sheets_discovery.json'
 Seems like it trying to find two local files: sheets_discovery.json and drive_discovery.json, I managed to go into the client file and change the destination to the exe folder manually, and then it finds the files but is this the only way? To send with the 2 files and change the client file? Cant I get this packed into the exe file?

**Comment by nithinmurali** [comment]
Hi, technically yes you can pack the files in the executable. There is another way, you can download the documents instead of loading them from files. please see the google api documentation for more details. Or you can see the old code, the library initially used this method.

**Comment by mblom122** [comment]
Could you please help me with that code for downloading the documents instead? Thanks alot

**Comment by nithinmurali** [comment]
I dont remember the exact code, please check the old commits of client.py, you can see the code.

**Comment by psdantonio** [comment]
In case anyone else stumbles here with the same issue, all you have to do is refer to the 1/26/17 [commit](https://github.com/nithinmurali/pygsheets/commit/48058df7fa18017184618a7d7c5f9bdef51ffff3). Afterwards, it works perfectly when bundled into a single file app.

Comment out or replace:
```
        data_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
        with open(os.path.join(data_path, "sheets_discovery.json")) as jd:
            self.service = discovery.build_from_document(jload(jd), http=http)
        with open(os.path.join(data_path, "drive_discovery.json")) as jd:
           self.driveService = discovery.build_from_document(jload(jd), http=http) 
```
with this:
```
        self.service = discovery.build('sheets', 'v4', http=http)
        self.driveService = discovery.build('drive', 'v3', http=http)
```

**Comment by DgitalTrex** [comment]
@psdantonio 

What exactly do we have to do? Do I have to download client.py and do the changes and compile via pyinstaller?
