### ISSUE TITLE
.create_protected_range() seems to have an issue

### ISSUE THREAD

**Issue by rgregory1** [nithinmurali/pygsheets#206]
This library is wonderful! I've used a few different ones but the search is definitely over!

Everything works exactly as expeceted until I tried to protect a sheet that I just copied to a new workbook.  I tried the following code:

employee_sheet.create_protected_range('B2:F72')

It triggered the following error, https://pastebin.com/qLrEbtWy

I have used the employee_sheet object successfully many times in my code, so I thought I'd drop a line here to see if it was something I was doing or a bug.

**Comment by Kordishal** [comment]
To create a protected range use the DataRange class:
`DataRange(start='B2', end='F72', worksheet=employee_sheet).protected = True`

The `create_protected_range` function should be private or be changed. It expects a grid range and not a range:

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#gridrange

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#protectedrange

It would make much more sense to be able to add a protected range with `create_protected_range('B2:F72')` instead.

**Comment by nithinmurali** [comment]
@rgregory1 DataRange is a pygsheets class. use it as `pygsheets.DataRange`

you can also use the create_protected_range function, it takes the a grid range, not like the one you have specified. so use this instead
`wks.create_protected_range(wks.get_gridrange('A1', 'C2'))`

**Comment by rgregory1** [comment]
Perfect!!  Worked like a charm.  Thank you for taking the time to post. 

I don't think there is anything in the documentation that gives an example like this, is it rude to suggest that an example similar to this be added to the docs?  It might be very helpful for folks at a similar level to myself in understanding the library at a deeper level?

My issue is closed for sure, but I'll leave it open for a day to see if I get a response on this.

**Comment by Kordishal** [comment]
Leave it open so we remember to update the docs, And improve the interface for next iteration.

**Comment by rgregory1** [comment]
Hello again, my new sheets are now in the wild, it turns out using the vanilla protect range line that I have

employee_sheet.create_protected_range(employee_sheet.get_gridrange('B1', 'G74'))

works as expected, but that functionality seems to only protect the sheet from those without edit rights!   Which is really not useful.  It 'protects' the sheet then allows anyone with edit rights to the sheet to make changes to the protected sheet...

Is there a way to add a command to this to protect it from anyone except one account?  Otherwise it's the same as edit vs view with google sheets.

**Comment by Kordishal** [comment]
The reason for this is, that create protected range has only a limited implementation. It only sets the range not the editors or read only. This means that all editors of the sheet will get access (at the point at which the range is created). 

You can use the custom request function on the spreadsheet class to make the request yourself.

Documentation on how to do that is here:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#ProtectedRange

```
request = {
    "addProtectedRange": {
        "protectedRange": {
                "range": gridrange
            },
        }}
```

This is the base for the request. Add the additional fields inside the `protectedRange` object. Hope this helps. Have not tested this.

**Comment by rgregory1** [comment]
Thank you for the explanation.  I'm adding it to a workbook that is already shared with everyone.  

I might have to create a function that:

1. copies the sheet from a different workbook
2. adds the content
3. unshares with everyone
4. protects the range
5. shares with everyone again

Might be a few extra lines of code, but it might be the effect I want.

**Comment by yanokwa** [comment]
@Kordishal I'm also having this problem. Could you share a more complete example where you protect an entire sheet so that only one person can edit it?
