### ISSUE TITLE
Google spreadsheet not visible in Google Drive when using service account

### ISSUE THREAD

**Issue by edgarsampson** [nithinmurali/pygsheets#207]
Hello, 

I am trying to create a Google spreadsheet using a generated service account. The project has access to Google Drive API aswell as Google Sheets API. My logging info informs me that the spreadsheet was created as I can retrieve the sheet ID. However the sheet is not visible in my Google Drive. The permissions of the file is also set. If I instead use the outh-file way the spreadsheet is created. When I use this in a headless server environment and use the outh_nonlocal param, expecting to get an authorization URL to run from another computer, it fails at this point 
**File "/usr/local/lib/python2.7/dist-packages/oauth2client/tools.py", line 240, in run_flow
    code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line**    
So I cannot authorise the application either and a bit stuck.
Any suggestions would be appreciated.

Regards,
Edgar

**Comment by Kordishal** [comment]
You shared the file with your email after creation? In the service account example?
