### ISSUE TITLE
Worksheet.Find and Spreadsheet.Find return wrong row Numbers when empty rows

### ISSUE THREAD

**Issue by ashwarsadh** [nithinmurali/pygsheets#209]
I have tested both Spreadsheet Find and Worksheet Find.
It is reporting correct Column but Wrong Rows Every time.
My Data has many blank rows ,there is some bug in calculating Row Number when rows above the searched string are empty.
For Example if Data is in C13 it replaces C9, and if its in D13 then D9 is replaced.
If data is in D20 then D12 was replaced.
But when I filled all rows above the Searched string with random data then correct Cell was replaced.
Kindly look into it.

**Comment by ashwarsadh** [comment]
Hello,
You have made an excellent library but there is still a bug in find and replace.
When there is any merged cells rows in data then it is calculating wrong row number by offset of number of merge rows.
A screenshot is attached highlighting it when i replaced $date with value it is not replaced at right position
![find replace bug](https://user-images.githubusercontent.com/24552398/39077392-20901b4a-451f-11e8-883b-fc76c2714090.JPG)

**Comment by suneetm** [comment]
I still have this issue. Why is this closed?

**Comment by nithinmurali** [comment]
This is opened as a  separate issue #215
