### ISSUE TITLE
Appending a df to the end

### ISSUE THREAD

**Issue by modqhx** [nithinmurali/pygsheets#210]
Hi there, I can really use someones help for a pretty easy task. I'm writing a df on the fly for my group by dataframe for every APP to google sheets. 
Is there a way to append a new dataframe to the last "empty" row? This is basically 1 row I'm trying to add in the end within every for loop. Thanks.

**Comment by nithinmurali** [comment]
Please clarify what you wanna achieve. Also for usage questions, please use stackoverflow with `pygsheets` tag.

**Comment by modqhx** [comment]
@nithinmurali Sure. Its kinda urgent and very library specific. But right now I've something like:
```
    for APP in APPS:
        app_df= df[df.app == APP]
        for idx, row in app_df.iterrows():
            out_df = <some_data_frame>
            out_df = out_df.reset_index()
            out_df['impact_scaled'] = out_df['impact'].map(lambda x: 100 + (100*x))
            print(APP)
            write_to_gsheet(out_df)
        default_df = pd.DataFrame((default_row), columns=['week_start_idx', 'app', 'impact', 'description', 'impact_scaled'])
        write_to_gsheet(default_df, True, out_df.shape[0], out_df.shape[1])
```
The second `write_to_gsheet` outside the inner `for` loop doesn't work and inserts it at the wrong spot. So really I want to append a new custom dataframe at the end. Does that make sense?
