### ISSUE TITLE
Format text alignment

### ISSUE THREAD

**Issue by Ricardosgeral** [nithinmurali/pygsheets#212]
Hi
congrats on pygsheets. it's great

I want to put all cells of the worksheet with center alignment 
I know how to set the text alignment of a cell, and i know how to apply that format to a range of cells.
I just don't know how to set that range to be all the cells. How to I do this (assuming that i don't know the number of rows of the sheet)?
Is there a select all feature? 
thanks

**Comment by nithinmurali** [comment]
you can get the number of rows , and cols by wks.rows and wks.cols, hence can be used to select all the cells
