### ISSUE TITLE
Add developer metadata resource

### ISSUE THREAD

**Issue by 4word** [nithinmurali/pygsheets#213]
It looks like you are manually specifying which resources to load in the discovery file for the spreadsheets service. I can manually set developer metadata on a sheet with a custom_request, but I cant retrieve it without the developerMetadata resource. 

I have never manually specified which resources to load in a discovery document before (I always just use discovery.build('sheets', 'v4', credentials=credentials)) so I am not really sure about where to add it in there and what parameters it needs, otherwise I would just open up a PR. I am hopeful that its something you can do easily!

**Comment by nithinmurali** [comment]
we are not manually specifying which resources to load in the discovery file for the spreadsheets service. The discovery files are stored offline just so that it would save an api call.
