### ISSUE TITLE
Accessing the values of cells created with formulas

### ISSUE THREAD

**Issue by bmazeraski** [nithinmurali/pygsheets#219]
If I have a sheet for which most of the cells have values generated by formulas, how should I access those values? The cells that don't have formulas are returned as expected with get_values(), but the cells with formulas all have values of '#REF!' in the returned data structure. The formulas involve the GoogleFinance API, if that matters. Please advise.

**Comment by nithinmurali** [comment]
I am unable to recreate the issue with a simple summation formulas. Please provide steps to recreate the issue.

**Comment by nithinmurali** [comment]
I tried using the finance formulas. I am able to get the correct values. 

This is what i did. 
```
wks.update_value('B2',"AAPL")
wks.update_value('B7','=GoogleFinance(B1,"price")')
 wks.get_all_values()
```
i was able to get 16.7

**Comment by nithinmurali** [comment]
closing as no response. ans unable to reproduce/
