### ISSUE TITLE
Date format lost (replaced by default number format) by bulk formatting

### ISSUE THREAD

**Issue by whatnick** [nithinmurali/pygsheets#221]
When applying format over a range dates seem to be parsed, interpreted and replaced by default float representation. e.g *Apr 26 2018 10:40 AM* morphs to *43216.4444444444* , this might be an aspect of sheets trying to be smart/helpful, however it is horrible for readability and inefficient for bulk formatting. Is it possible override this in.

*range.apply_format* to disable parsing.

**Comment by nithinmurali** [comment]
I am unable to reproduce your error. Can you please give the steps for reproducing the error. Also what is the version of pygsheets you are using. Is it the staging version?
