### ISSUE TITLE
cell.set_text_format() - doesn't work for me unless cell.update() before call?

### ISSUE THREAD

**Issue by dpreilan** [nithinmurali/pygsheets#222]
I am on OSX using latest version 1.1.4.

I am having issues attempting to update cell formatting, but I think this simple test case shows the issue. It appears you need to call cell.update() before set_text_format() and perhaps other formatting apis?? What is the purpose of these apis then and why not just set object (cell instance) fields??

 <pre>
wks = sh.worksheet_by_title("cxx")
c = wks.cell('A1')
c.value = 'aa'
c.text_format['bold'] = True
c.update()
c.text_format['bold'] = True
# Both of the following set_txt_format() works fine
c.set_text_format('bold', False)

c.set_text_format('bold', True)

# get a different cell
c = wks.cell('A2')
c.value = 'bb'
# w or w/o the next line doesn't matter
# c.text_format['bold'] = True

# this line fails with
c.set_text_format('bold', False)

  File "/Users/dreiland/PycharmProjects/SupremeOptimization/TimeInput/gtest1.py", line 102, in <module>
    c.set_text_format('bold', False)
  File "/Library/Python/2.7/site-packages/pygsheets/cell.py", line 202, in set_text_format
    self.update()
  File "/Library/Python/2.7/site-packages/pygsheets/cell.py", line 362, in update
    self._worksheet.client.sh_batch_update(self._worksheet.spreadsheet.id, request, None, False)
  File "/Library/Python/2.7/site-packages/pygsheets/client.py", line 443, in sh_batch_update
    return self._execute_request(spreadsheet_id, final_request, batch)
  File "/Library/Python/2.7/site-packages/pygsheets/client.py", line 455, in _execute_request
    response = request.execute()
  File "/Library/Python/2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1PSpipwEc-Qc6AtbYm76CyItMQyyAk8R0AQ06oVXsb-Q:batchUpdate?alt=json returned "Invalid value at 'requests[0].repeat_cell.cell.user_entered_value.number_value' (TYPE_DOUBLE), "bb"">
</pre>

**Comment by nithinmurali** [comment]
your comment is very ill formated , please format it.

**Comment by dpreilan** [comment]
interesting, it might be picking up bold in the text

**Comment by nithinmurali** [comment]
>  It appears you need to call cell.update() before set_text_format() and perhaps other formatting apis??
No, you dont need to , if you are calling the apis. but if you are setting the properties directly, then you need to. 

> What is the purpose of these apis then and why not just set object (cell instance) fields??
The api's have more validity checks for the params. and they would update instantly. So it prefered to use functions.

> c.set_text_format('bold', False)
The error thrown is not because of this statement. From traceback i can see that, you have set the cell format to `Double` and is setting a string value to it. That is the error.

**Comment by nithinmurali** [comment]
Okay, apprently it is a bug in the 1.1.4. Its fixed in the staging. 

Please install from staging to get the fix. pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip

**Comment by dpreilan** [comment]
that fixed it, but looks like the apis have changed?

I originally hit this bug while using sheet.update_cells_prop(). That method appears to be gone.
Also, unrelated, but I had a call to sheet.get_row(1, returnas='matrix', include_empty=True) and looks like include_empty parameter went away.

**Comment by nithinmurali** [comment]
Yes, There are some api changes. The next version 1.2.0 will be non backwards compalitable, so these are in the pipeline for it.  These changes will be documented. For now you can refer to the [docs ](http://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.get_row) to see what are the new params. 

update_cell_props -> update_cells
include_empty -> include_tailing_empty

**Comment by dpreilan** [comment]
thanks for quick turnaround
