### ISSUE TITLE
Fix major dimension in get_values

### ISSUE THREAD

**Issue by nithinmurali** [nithinmurali/pygsheets#227]
`major_dimension` is not working properly in get_values. Which in turn makes many other functions like `get_col` etc non functional. 

Only in staging

**Comment by pablog** [comment]
@nithinmurali hi! any news about this? I'm having troubles using `get_col` which is returning only the first cell with content. I've seen there are multiple issues for that, so I didn't create a new one, but need to know if there's a fix or a workaround for this.

Thanks!

**Comment by nithinmurali** [comment]
What is the version you are using?

**Comment by pablog** [comment]
I'm using: `Version: 1.1.4`.

I'm also having trouble using `find` which in fact is more accurate for what I'm doing. It doesn't seem to play nice with uppercase characters. Has this ever happened to you?

**Comment by nithinmurali** [comment]
No, can you please give the steps to reproduce? The find is reworked in staging, i will check if it has the same issue.

**Comment by pablog** [comment]
Sure, I have a cell with content `U11: Something`

If I do `worksheet.find('U11')` it finds nothing. Instead if I do `worksheet.find('u11')` it works.

The same happens if I use a regex. Always keeping `matchCase=False` as default.

I found this out after my last message, so I have it working right now. Anyway I still don't know why the previous version (with the capital `U`) doesn't find anything.

**Comment by nithinmurali** [comment]
The find issue is fixed in the staging, but please note that there are a lot of unbreakable changes in the staging.

> @nithinmurali hi! any news about this? I'm having troubles using get_col which is returning only the first cell with content. I've seen there are multiple issues for that, so I didn't create a new one, but need to know if there's a fix or a workaround for this.

This issue is for a bug in the staging branch. Can you please provide steps to reproduce the same?
