### ISSUE TITLE
Can't set kwargs to worksheet.find()

### ISSUE THREAD

**Issue by Qwentor** [nithinmurali/pygsheets#229]
pprint(wks.find(address, matchEntireCell=True))
TypeError: find() got an unexpected keyword argument 'matchEntireCell'

But when I do not use any kwargs find works
pygsheets==1.1.4

**Comment by Kordishal** [comment]
In version 1.1.4. wks.find does not have any kwargs yet. You will have to either load from staging or read the older documentation.

`find(self, query, replace=None, force_fetch=True):`
