### ISSUE TITLE
Google sheet size grows (with new rows) using wks.clear() and then wks.append()

### ISSUE THREAD

**Issue by dahartzell** [nithinmurali/pygsheets#233]
The row count grows on the sheets, when using the clear function, followed by an append_table (which inserts correctly at the top of the sheet):

data = [(1,2,3), (4,5,6), etc...]
wks.clear()
wks.append_table(values=data)

The default row count on a sheet is 1000, and when clearing a sheet, then appending to it, the sheet grows by the number of rows appended (even though the get inserted at the top of the sheet  A1, and the new rows in the sheet are empty).

**Comment by nithinmurali** [comment]
`overwrite` param controls this. refer https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append
