### ISSUE TITLE
decimals not pulled in with get_as_df()

### ISSUE THREAD

**Issue by DavisTownsend** [nithinmurali/pygsheets#234]
When using get_as_df() function, only the values showing in the google sheet are read in, not the actual numeric value which can be many decimal places long

**Comment by nithinmurali** [comment]
That's because formatted values are fetched by default. Will add an option in `get_as_df`.

**Comment by nithinmurali** [comment]
fixed in 91fb71a70b4c25363bc641ff9ae1d1181e4c2c36
