### ISSUE TITLE
create worksheet doesn't work with Teamdrives

### ISSUE THREAD

**Issue by derichard** [nithinmurali/pygsheets#237]
If one moves a file from a personal drive to a teamdrive, its id changes. This creates trouble for the create function in client.py:

``` 
if parent_id:
   cur_parent = self._execute_request(None, self.driveService.files().get(fileId=result['spreadsheetId'],
                                               fields='parents', supportsTeamDrives=self.enableTeamDriveSupport), False)
            cur_parent = cur_parent['parents'][0]
            self._execute_request(None, self.driveService.files().update(fileId=result['spreadsheetId'],
                                                                         addParents=parent_id, fields='id, parents',
                                                                         removeParents=cur_parent,
supportsTeamDrives=self.enableTeamDriveSupport), False)

```

Once the file is moved, it looses its id, so it is not found in the original root folder of the user and therefore a Not Found Error is raised: 
removeParents=cur_parent but the current parent is not found since the file_id changed

I understand that the removeParents was introduced to avoid creating new files in the rootfolder, but with teamdrives it raises this issue.
One way to fix it would be to explicitly add a boolean if the parent folder is a teamdrive or not. Or one adds a check for the parent id, and if it is a teamdrive, one doesn't need to remove the parent since it is automatically removed.

**Comment by nithinmurali** [comment]
The drive wrapper is reworked in #204 , can you please verify if this bug still exists? Please reopen if so.
