### ISSUE TITLE
TypeError: Type aliases cannot be used with isinstance().

### ISSUE THREAD

**Issue by MarcoPorracin** [nithinmurali/pygsheets#240]
Im getting this error while trying to set a dataframe.

> Traceback (most recent call last):
  File "CostosFB_JC.py", line 85, in <module>
    wks.set_dataframe(frameSheets, 'A'+str(ultimaFila))
  File "/usr/local/lib/python3.5/dist-packages/pygsheets/worksheet.py", line 957, in set_dataframe
    df = df.replace(pd.np.nan, nan)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 3795, in replace
    method=method)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 5879, in replace
    regex=regex)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 3720, in replace
    return self.apply('replace', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 2432, in replace
    if not either_list and is_re(to_replace):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/inference.py", line 219, in is_re
    return isinstance(obj, re_type)
  File "/usr/lib/python3.5/typing.py", line 260, in __instancecheck__
    raise TypeError("Type aliases cannot be used with isinstance().")
TypeError: Type aliases cannot be used with isinstance().

Any idea why?

**Comment by nithinmurali** [comment]
Can you please provide a sample of you dataframe ? cant reproduce the issue without that.

**Comment by MarcoPorracin** [comment]
**Versions:**

Ubuntu 16.04 LTS (AWS EC2 public ami-67fca30b)
Python 3.5.2
pip 8.1.1 
pygsheets 1.1.4
pandas 0.23.0

**DataFrame:**

> ga:date,ga:medium,ga:source,ga:adClicks,ga:impressions,ga:adCost,ga:campaign
>20180530,Display,Facebook,354,9045,188.38,DP_Facebook_AlwaysOn_Propsecting_ALL_AWA_Competencia
> 20180530,Display,Facebook,301,6879,95.7,DP_Facebook_AlwaysOn_RMK_ALL_INT_Visitas
>20180530,Display,Facebook,915,26048,378.65,DP_Facebook_AlwaysOn_Propsecting_ALL_AWA_Seguidoras
> 20180530,Display,Facebook,100,2235,313.29,DP_Facebook_AlwaysOn_RMK_ALL_INT_Carrito
>20180530,Display,Facebook,569,9587,194.78,DP_Facebook_AlwaysOn_RMK_ALL_INT_ContenidoVisto
>20180530,Display,Instagram,124,41587,149.61,DP_Instagram_Stories_Propsecting_ALL_AWA_Seguidoras

(Its in CSV format)

**Comment by MarcoPorracin** [comment]
@nithinmurali Am i missing any info i can provide?

**Comment by nithinmurali** [comment]
No, i will check this is out once i get some free time.

**Comment by nithinmurali** [comment]
Unable to reproduce this error. I can successfully, read the data you gave from csv. and set it to a worksheet.

my code:
```
df = pd.read_csv('tmp.csv')
wks.set_dataframe(df, 'A1')
```

**Comment by MarcoPorracin** [comment]
Im actually able to run the code on my mac but it fails on the VM thats what is bothering me and i cant see to find why or what i need to add/update/fix.

**Here is my code:**
```
lastRow = len(wks.get_all_values(returnas='matrix',include_empty=False)) + 1
wks.set_dataframe(frameSheets, 'A'+str(lastRow))
wks.delete_rows(ultimaFila)
```
PS: I just use this to append the DataFrame after the last row.

Any idea what could be causing this?

**Comment by nithinmurali** [comment]
`df.replace(pd.np.nan, "NAN")` this is the line that is causing the error. Can you try runing this outside on your dataframe and see if its throws an error?

This line basically replaces your nan with string "NAN".

**Comment by MarcoPorracin** [comment]
I just tried that a couple other thing and i even took the time of comparing and updating all packages versions (numpy, pandas and pygsheets) but the problem persists. It works on my mac and not on the VM on AWS.
The only difference is the python version:
- Ubuntu, python 3.5.2 - Doesn't work
- MacOS, python 3.6.1 - Works

**Comment by MarcoPorracin** [comment]
This may be the problem: https://stackoverflow.com/questions/50495099/typeerror-type-aliases-cannot-be-used-with-isinstance

**Comment by nithinmurali** [comment]
Ahh so not a pygsheets issue.

**Comment by MarcoPorracin** [comment]
@nithinmurali It doesnt seems like it. I ll close the issua and add any solution if i find any for future people.

**Comment by nithinmurali** [comment]
Maybe try updating python/pandas as said in stackoverflow? The error is caused by this line `df.replace(pd.np.nan, "NAN")` which has nothing to do with pygsheets api. we are using the dataframe function to replace.  Even-though we can try some hack to resolve this issue, i think its better to let it get fixed by pandas.
