### ISSUE TITLE
HttpError 400 when writing multi column index DF to google sheets:

### ISSUE THREAD

**Issue by jainraje** [nithinmurali/pygsheets#242]
Here is sample code to duplicate error:

###
# step 1 - create DF
###
import pandas.util.testing as tm; tm.N = 3
def unpivot(frame):
    N, K = frame.shape
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    return pd.DataFrame(data, columns=['date', 'variable', 'value'])
df = unpivot(tm.makeTimeDataFrame())
df['value2'] = df['value'] * 3
df = df.pivot(index='date', columns='variable')

###
# step2 - write DF to google sheets 
###

df.index = df.index.strftime('%Y-%d-%m')

global oauth_file
gc = pygsheets.authorize(outh_file=oauth_file)
sh = gc.open(spreadsheet='test)
wks = sh.worksheet_by_title(worksheet='test)
pygsheets.client.GOOGLE_SHEET_CELL_UPDATES_LIMIT = 10000
wks.set_dataframe(df, (1, 1), fit=True, copy_index=copy_index)

The source object is a DF so my thinking is the API should write the DF to google sheets.

Please comment, advise.

thank-yu,
--jainraje

**Comment by nithinmurali** [comment]
fixed in 51ad240
