### ISSUE TITLE
TypeError: Object of type 'Timestamp' is not JSON serializable

### ISSUE THREAD

**Issue by helgisteinar** [nithinmurali/pygsheets#245]
When trying to update a sheet from a Panda Data Frame I keep running into type issues.

For my code, I cast the dataframe to a string before it is converted into a list.

in [https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/worksheet.py](url)

line 1103 

        values = df.values.tolist()

becomes

        values = df.values.astype(str).tolist()

I am not familiar enough with the Google API to know what data types, formats might work better.  I.e. does it accept some specific formats for date/time strings?  There is also the series part

**Comment by nithinmurali** [comment]
will add this string conversion as a optional parameter.

**Comment by helgisteinar** [comment]
The index of the dataframe is going to need the same treatment.  Very often those contain date times.  So when in the 

    set_dataframe(df, start, copy_index=False, copy_head=True, fit=False, escape_formulae=False, nan='NaN')

when `copy_index=True` the index copy will need to cast to string.
