### ISSUE TITLE
insert_cols and insert_rows only for interval

### ISSUE THREAD

**Issue by francot** [nithinmurali/pygsheets#246]
Could be useful use insert_cols (or insert_rows) function only for an interval
(the same if insert columns manually after selecting an interval of cell)
For example:
insert_cols(col, number=1, rowstart=None,rowend=None, values=None, inherit=False)
where:
rowstart=index of row where interval starts
rowend=index of row where interval end

insert colons only for defined row interval

**Comment by nithinmurali** [comment]
This can be useful, will add to the pipeline

**Comment by nithinmurali** [comment]
This can be achieved using `col` and `number` in insert_cols
