### ISSUE TITLE
Hide worksheet

### ISSUE THREAD

**Issue by pablog** [nithinmurali/pygsheets#248]
I was needing the ability to hide/show a worksheet.

I think this is as simple as adding this to `worksheet.py`:

```
    @property
    def hidden(self):
        """Mark the worksheet as hidden."""
        return self.jsonSheet['properties'][hidden']

    @hidden.setter
    def hidden(self, hidden):
        self.jsonSheet['properties']['hidden'] = hidden
        if self._linked:
            self.client.sheet.update_sheet_properties_request(self.spreadsheet.id, self.jsonSheet['properties'], 'hidden')
```

By reading [this documentation](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#sheetproperties).

Let me know if I'm right, and if there's a reason this was not yet implemented.

**Comment by nithinmurali** [comment]
There was no specific reason this was not implemented, API v4 has a ton of features, so i have only implemented those which i felt would be useful. If you send a PR i will accept the same.

**Comment by pablog** [comment]
PR sent @nithinmurali

**Comment by shs-cse** [comment]
In case anyone wondering, setting `wks.hidden = True` seems to work well.
