### ISSUE TITLE
AttributeError: 'SheetAPIWrapper' object has no attribute 'sheets_to_copy'

### ISSUE THREAD

**Issue by pablog** [nithinmurali/pygsheets#250]
When using the function: `add_worksheet` in `Spreadsheet`.

The error happens in this line:

https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/spreadsheet.py#L203

This works in `master` 

`jsheet['properties'] = self.client.sh_copy_worksheet(src_worksheet.spreadsheet.id, src_worksheet.id, self.id)`

This fails in `staging`:

`jsheet['properties'] = self.client.sheet.sheets_to_copy(src_worksheet.spreadsheet.id, src_worksheet.id, self.id) `

Should we use the code in `master` then?

**Comment by pablog** [comment]
@Kordishal the error was introduced in this line: https://github.com/nithinmurali/pygsheets/commit/66cfc1f012337a2cdcfdc087fb640d723adcfac6#diff-71403ba862975445f8bd172d95d4299bR203

Any idea?

**Comment by nithinmurali** [comment]
I think this is just a typo. He move the old function to sheets.py with name `sheets_copy_to` but here he is using the name `sheets_to_copy`

**Comment by nithinmurali** [comment]
merged, Thanks :)
