### ISSUE TITLE
get_col method doesn't return empty fields if returnas="cell" is used

### ISSUE THREAD

**Issue by quaswex** [nithinmurali/pygsheets#254]
Hello guys,

Using `get_col` with matrix returns me proper list of cells from the sheet:
`old_data = old_wks.get_col(col=offset, returnas="matrix")`
`['', 'Test3', 'value', '', '27.1', '31', '13.3', '15.6', '15.6', '15.6', '14', '45', '0', '2.8', '8.3', '0', '0', '0', '0', '1.1', '1.1', '1.1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']`

Using `get_col` with cell object parameter doesn't return empty values:
`old_data = old_wks.get_col(col=offset, returnas="cell")`
`[<Cell E1 'Test3'>, <Cell E2 'value'>, <Cell E3 '27.1'>, <Cell E4 '31'>, <Cell E5 '13.3'>, <Cell E6 '15.6'>, <Cell E7 '15.6'>, <Cell E8 '15.6'>, <Cell E9 '14'>, <Cell E10 '45'>, <Cell E11 '0'>, <Cell E12 '2.8'>, <Cell E13 '8.3'>, <Cell E14 '0'>, <Cell E15 '0'>, <Cell E16 '0'>, <Cell E17 '0'>, <Cell E18 '1.1'>, <Cell E19 '1.1'>, <Cell E20 '1.1'>]`

This means that I'm incapable of iterating over list of cell object for further cells transformation. Any thoughts?

**Comment by nithinmurali** [comment]
Hey, i think this is fixed in staging. Can you please test with the staging version? But please note that there are few breaking changes in staging.
