### ISSUE TITLE
get "note" and "color" from cell not working

### ISSUE THREAD

**Issue by Revencu** [nithinmurali/pygsheets#256]
pygsheets.cell(1,1).note - not return the exist note from a cell
pygsheets.cell(1,1).color- not return the background color of a cell

**Comment by nithinmurali** [comment]
By default, the cells are simple cells, ie. they store only the value not the format etc, this is done to reduce the number of requests and memory footprint. After you create a cell, use cell.fetch() to fetch the extra attributes and make it a non simple cell.

**Comment by SimasJan** [comment]
Hi @nithinmurali , really happy with the library and thank you for sharing it with the world. I am not sure whether I am doing something wrong or missing a bit out, I am unable to receive cell (background) color, what I get is 4 None tuple.
My flow for context:
get specific cell (gsh = class instance, active_wks = active current worksheet)
`b35 = gsh.active_wks.cell('B35')`
`b35.fetch()`
`b35.color`
Output:
 `(None, None, None, None)` 

Any help much appreciated. Thank you.

**Comment by nithinmurali** [comment]
@SimasJan  `None` implies no color has been set.  Also you don't need to call fetch anymore, its called by default when you access color
