### ISSUE TITLE
get_as_df() has trouble with columns with same name in source sheet

### ISSUE THREAD

**Issue by jankojankojanko** [nithinmurali/pygsheets#257]
When you import an excel/csv/... in pandas as a dataframe and columns have the same name, pandas starts giving them a number (eg. headers=('Item','Item','Item'), pandas turns this automatically into headers=('Item','Item.0','Item.1') to make sure the headers are unique in your dataframe.

However, when you use get_as_df(), it keeps the headernames as 'Item','Item','Item', which gives a hard time to work with pandas.

To reproduce: make a spreadsheet in drive with 2 or more columns which have the same name and import it.

Below the result of a google spreadsheet I read using pygsheets / get_as_df()
![capture](https://user-images.githubusercontent.com/39901117/43370670-9b6eb904-9383-11e8-9361-7e07f1ab3c05.JPG)

**Comment by nithinmurali** [comment]
Not sure if this is a desired behavior, as this would be changing the data given in sheet.
