### ISSUE TITLE
Index error list index out of range - pygsheets 

### ISSUE THREAD

**Issue by Aruloli** [nithinmurali/pygsheets#261]
Hi Nithin, How are you? My wife having few Google sheets with data asked me to make reports based those data. Before touching her drive, I tested your code in my drive first and it worked perfect. When i tried in my wife's google account it shows following error.
''ss = gc.open('chitra')
File "C:\Users\Aruloli\Python\pygsheets-staging\pygsheets\client.py", line 136, in open
spreadsheet = list(filter(lambda x: x['name'] == title, self.drive.spreadsheet_metadata()))[0]
IndexError: list index out of range''
When I open with gc.open_by_key & gc.open_by_url it works perfect but without many pygsheets methods
Pl help me. Arul

**Comment by nithinmurali** [comment]
what is the version of your pygsheets?

**Comment by Aruloli** [comment]
Sorry, how to get version?

**Comment by Aruloli** [comment]
I downloaded this from yours  https://github.com/nithinmurali/pygsheets

**Comment by nithinmurali** [comment]
how did you install pygsheets?

**Comment by Aruloli** [comment]
pip install

**Comment by Aruloli** [comment]
Python 3.5

**Comment by nithinmurali** [comment]
Okay, this error means, there is no spreadsheet with the given name. are you sure there is a sheet with the name `chitra` ?

**Comment by Aruloli** [comment]
I have my own drive where it works perfect. Only in my wife's drive I am getting this problem. Also it opens with both gc.open_by_key & gc.open_by_url . But when I try gc.open("chitra") it gives problem(chitra is the name of the sheet).

**Comment by Aruloli** [comment]
https://docs.google.com/spreadsheets/d/18sQwgrdpyLz3iOZMq6vDq4kJA9yPRbTiaYy9-IPHJEE/edit#gid=1900064719

**Comment by Aruloli** [comment]
![image](https://user-images.githubusercontent.com/19381434/43878756-746a00a0-9bbe-11e8-94bf-fd0fe7a9a41c.png)

**Comment by Aruloli** [comment]
With gspread it is getting opened.   

credentials = ServiceAccountCredentials.from_json_keyfile_name('ChitraGTCS-eb21b5753afc.json', scope)
gc = gspread.authorize(credentials)
wks = gc.open("chitra").sheet1

**Comment by nithinmurali** [comment]
When you use the same service account credentials also you cant open in pygsheets?

**Comment by Aruloli** [comment]
Thank you so much for devoting your valuable time. Sorry for disturbing you. It is my first ever GitHub query. Your module pygheets is excellant

**Comment by Aruloli** [comment]
When you use the same service account credentials also you cant open in pygsheets?
1 I tried pygheets first. Since it was giving index error I tried gspread

**Comment by Aruloli** [comment]
But my wife's email chitra@gatewaytheschool.in belong to school. May be that is the issue

**Comment by Aruloli** [comment]
But this sheet belong to her ie she is the owner

**Comment by Aruloli** [comment]
![image](https://user-images.githubusercontent.com/19381434/43879058-c92414c2-9bbf-11e8-88ec-bd9d764017db.png)
Her credentials

**Comment by nithinmurali** [comment]
As described in [docs](http://pygsheets.readthedocs.io/en/latest/authorizing.html), if you wanna access your wife's account make sure the oauth credentials are generated from her account. Else create a service creds and share the sheet to that email.

**Comment by Aruloli** [comment]
One more thing. My account i was asked for credential authorisation to handle sheets and drive. But i did not receive such thing when I created service account in her login and tried to run the python file. 
How to manually generate credentials from her account to approve the scopes ------ 
SCOPES = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.metadata.readonly']

**Comment by nithinmurali** [comment]
`gc = pygsheets.authorize(outh_file=' path to client_secretxxx.json of her acccount ')` try auth like this.

It is supposed to ask her login.

**Comment by Aruloli** [comment]
Thank you so much. Let me try

**Comment by nithinmurali** [comment]
Else you can also try to use that service account which worked with gspread like this 

`gc = pygsheets.authorize(service_file=' path to service_creds.json')`

**Comment by Aruloli** [comment]
### Thank you so much. It is working perfect. ###  Can I try to open another sheet in the same location?

**Comment by Aruloli** [comment]
Suppose I have two sheets in the same drive, **do I need two seperate Service account json files?**

**Comment by nithinmurali** [comment]
okay cool. Now it should work for any sheet in her account. 

No but all those sheets should be shared with the first service account. Its better to use outh credentials, as then you can acess any sheet in her account.

**Comment by Kordishal** [comment]
Hi @Aruloli

For security reasons I would delete the picture of the credentials library and your wifes email address.

Additionally delete the API Keys you generated as they are now public and can be used by anyone to access your wifes account, via API.

The other credentials are not necessarily compromised, but I would still re-generate all of them, just to be sure.

**Comment by nithinmurali** [comment]
True that @Kordishal

**Comment by Kordishal** [comment]
And the comment with to the sheet. By posting a sheet link, you share it publicly. I could just delete all the information in it.

**Comment by Aruloli** [comment]
I agree with you. I just deleted the API keys also which I created without knowing the purpose

**Comment by nithinmurali** [comment]
Also @Aruloli, for usage questions please use stackoverflow with `pyghseets` tag. Github issues are mainly used for reporting issues in the project.

**Comment by Aruloli** [comment]
I got it. I tried many tags in stackoverflow but failed to get a solution for 2 consecutive days

**Comment by nithinmurali** [comment]
Ohh i see. I am subscribed to the pygsheets tag, so if you use it i would get a notification in few mins.

**Comment by Aruloli** [comment]
Pl give a link on Complete Task flow of creating Service account>> Give permissions>> Open google sheets. If I could not get your connection I would have dropped this project. Thank you so much. 
Shall I close this issue? Suppose I get another issue, if at all, i will open another issue

**Comment by nithinmurali** [comment]
See the docs, http://pygsheets.readthedocs.io/en/latest/authorizing.html everything is explained there.

Also use the staging version of pygsheets, many issues are fixed there, 
`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip` at moment.

**Comment by Aruloli** [comment]
gc = pygsheets.authorize(outh_file='client_secretxxx.json')
gc = pygsheets.authorize(service_file='service_creds.json')
Sorry. Do I need to authorise both these files? outh_file & service_file

**Comment by Aruloli** [comment]
No where I got a clear cut guidance on how to go about except yours

**Comment by nithinmurali** [comment]
NO, Use 1st one if you wanna use oauth authorization, 2 for service account . you only need one of it.

**Comment by Aruloli** [comment]
After your advice i got very good clarity

**Comment by Aruloli** [comment]
It got clicked when you advised me to put  **gc = pygsheets.authorize(service_file='service_creds.json')**

**Comment by cnpants** [comment]
Hi! I will be deploying an app thru Heroku. Will this work? I used the authentication method and followed the link and copied it. Will this happen if I deployed it there?

**Comment by Kordishal** [comment]
Hi,

Please use Stackoverflow for usage questions.

When using a service account you need to share your sheet with the service account email.

And if you do ever post on GitHub again, open a new issue. I only saw this because of an E-Mail notification. Or if you do not want to create a new issue, you can re-open a closed issue.

**Comment by cnpants** [comment]
Noted. Thanks!
