### ISSUE TITLE
Docs: References are empty 

### ISSUE THREAD

**Issue by Daviddep** [nithinmurali/pygsheets#263]
Seems like all the references in the docs are empty ... 

See for instance the page with the Spreadsheet references: https://pygsheets.readthedocs.io/en/latest/spreadsheet.html

**Comment by nithinmurali** [comment]
Thanks for reporting this. went un-noticied.

**Comment by Daviddep** [comment]
No worries - really enjyoing your library. Is there a way to get the ID of worksheet? Like `get_id` or similar?

**Comment by nithinmurali** [comment]
yeah, id is a property, just `worksheet.id`

**Comment by Daviddep** [comment]
Excellent. Thank you!

**Comment by nithinmurali** [comment]
fixed in 75934051df428cf9658cf00fa093f2f3752f0423
