### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by Kordishal** [nithinmurali/pygsheets#266]
Considering all the breaking changes which have been introduces, I think it would be a good idea to make a new release and maybe take the time to create a change log.

While releasing it as 2.0 should make it clear that there have been major changes!

**Comment by nithinmurali** [comment]
Yes,  was thinking the same. Also was planning to add deprivation warning wherever possible before release.

**Comment by nithinmurali** [comment]
Also I am waiting for the PR from @ssg2526, who is working in adding charts support.

**Comment by nithinmurali** [comment]
All milestones completed. Will publish once all the docs(README) are updated.
