### ISSUE TITLE
Cannot share spreadsheet

### ISSUE THREAD

**Issue by theimperium20** [nithinmurali/pygsheets#267]
I followed the documentation and used this command 
` sh.share('', role='reader', type='anyone')` to make the worksheet public but i am getting this error
    sh.share('', role='reader', type='anyone')
    TypeError: share() got an unexpected keyword argument 'type'

**Comment by nithinmurali** [comment]
The docs are for the version which is in master now. You might be using the 1.1.4 ?

TODO: fix docs link

**Comment by theimperium20** [comment]
This code `wsIV.update_cell(1,x+1, values[x])` throws this error
`label = format_addr(addr, 'label')`
`raise InvalidArgumentValue("addr of type " + str(type(addr)))`
`pygsheets.exceptions.InvalidArgumentValue: addr of type <class 'int'>`

**Comment by nithinmurali** [comment]
what is your version of pygsheets ?

**Comment by nithinmurali** [comment]
as specified in [docs](https://pygsheets.readthedocs.io/worksheet.html#pygsheets.Worksheet.update_cell), update cell take first argument as adress, it should be label or tuple, `wsIV.update_cell((1,x+1), values[x])` this would work

**Comment by theimperium20** [comment]
1.1.4
