### ISSUE TITLE
Docs are incorrect in multiple locations. Which docs to use? readthedocs or readme?

### ISSUE THREAD

**Issue by samlazrak** [nithinmurali/pygsheets#269]
The docs are incorrect all over the place. I've managed to get authorization and creating a new worksheet on an existing file working however I keep trying to do other operations and I am getting errors such as for creating a new file I get: `TypeError: Got an unexpected keyword argument "parent_id"`

Such as here:
```
https://pygsheets.readthedocs.io/authorizing.html

in the authorization section it shows: 

8. Find the client_id from the file, your application
 will be able to acess any sheet which is shared with this email.
 To use this file initiliaze the pygsheets client as shown

gc = pygsheets.authorize(outh_file='client_secretxxx.json')

```
And in the readme: 
```
More Examples
Opening a Spreadsheet
# You can open a spreadsheet by its title as it appears in Google Docs 
sh = gc.open("pygsheetTest")

# If you want to be specific, use a key
sht1 = gc.open_by_key('1mwA-NmvjDqd3A65c8hsxOpqdfdggPR0fgfg5nXRKScZAuM')

# create a spreasheet in a folder (by id)
sht2 = gc.create("new sheet", parent_id="adF345vfvcvby67ddfc")

# open enable TeamDrive support
gc.enableTeamDriveSupport=True
gc.teamDriveId = "Dqd3A65c8hsxOpqdfdggPR0fgfg"
```

following these instructions to use gc.create results in error: `TypeError: Got an unexpected keyword argument "parent_id"`

**Comment by samlazrak** [comment]
057cfe9, The one installed with: `pip install https://github.com/nithinmurali/pygsheets/archive/master.zip` as it was the recommended version.

**Comment by nithinmurali** [comment]
As we are in the process of releasing v2.0, there are many breakable changes, and the docs reflect the old version v1.1.4. Currently there is some issuein displaying different docs versions. So either you can revert to old version (install using pip) or wait till the docs are fixed.

**Comment by nithinmurali** [comment]
within a week. Just waiting for the chart PR to be merged.
