### ISSUE TITLE
What to do to deploy in Web?

### ISSUE THREAD

**Issue by cnpants** [nithinmurali/pygsheets#277]
Hi I would want to use the package to log periodically on the spreadsheet. These would be on a timely basis and scheduled. I will be using Flask and APScheduler for these. But I think I got a problem when deploying it to Heroku, it won't authenticate via Oauth2. Then it presented me this: [LINK]

How do I go about these? Has someone tried it? Thanks!
(https://developers.google.com/api-client-library/python/guide/aaa_client_secrets)

**Comment by nithinmurali** [comment]
what is your pygsheets version ?

**Comment by cnpants** [comment]
I guess it is the latest, I used the pip install https://github.com/nithinmurali/pygsheets/archive/master.zip

**Comment by nithinmurali** [comment]
you can use either the service account or oauth, both should work.  about oauth just paste that link in your browser and authenticate.

**Comment by nithinmurali** [comment]
btw is this your question regarding the same issue?

**Comment by cnpants** [comment]
Yes. After that, I renamed the JSON file to client_secret.json. Then presented me that link that I can't OAuth on a running web. I will give it another try.

**Comment by cnpants** [comment]
My version is pygsheets==1.1.4.
When I used
`gc = pygsheets.authorize(outh_file='client_secretxxx.json')`

I got these error:
```
UserWarning: The argument outh_file is deprecated. Use client_secret instead.
  warnings.warn('The argument {} is deprecated. Use {} instead.'.format(key, _deprecated_keyword_mapping[key]))
Traceback (most recent call last):
  File "app.py", line 25, in <module>
    gc = pygsheets.authorize(outh_file='client_secret_xxx.json')
  File "\Anaconda3\envs\project3\lib\site-packages\pygsheets\authorization.py", line 90, in authorize
    for key in kwargs:
RuntimeError: dictionary changed size during iteration
```

**Comment by cnpants** [comment]
Hi I summarized my problem here:

[STACKOVERFLOW LINK](https://stackoverflow.com/questions/52196342/how-to-authenticate-google-cloud-services-on-pygsheets-deployed-in-web-server-h)

**Comment by nithinmurali** [comment]
cool, we changed the way nonlocal_auth is handled, maybe it has a bug. I will verify the same.

**Comment by cnpants** [comment]
In the meanwhile I will be using gspread. It is quite working with these codes:
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('XXXXXXXXXXXXX.json', scope)
gc = gspread.authorize(credentials)

wks = gc.open('RSSI Spreadsheet').sheet1
wks.append_row(['hello', 'world'])

```

I will be watching this thread though so I can check. Thanks!

**Comment by nithinmurali** [comment]
Ok, i had this tested. And it is working good (had an issue with python2 though). I think your issue is you are using different version on your local and on your cloud. On your local you are using master version. but on the server you are using 1.1.4, which needs to set a `outh_nonlocal` param to enable oauthorization in server. also the param for the service_account has also changed.

**Comment by cnpants** [comment]
Ohhh. Maybe I'll reroute pygsheets in the requirements.txt to download from the master.

**Comment by cnpants** [comment]
Hi still no avail after tried using:
`git+git://github.com/nithinmurali/pygsheets/archive/master.zip#egg=pygsheets`
on my `requirements.txt
`

How do I set a `oauth_param`? Where do I place that?

This is still my logs:
```
2018-09-07T03:34:05.791202+00:00 app[web.1]: Your browser has been opened to visit:
2018-09-07T03:34:05.791204+00:00 app[web.1]: 
2018-09-07T03:34:05.791206+00:00 app[web.1]:     https://accounts.google.com/o/oauth2/auth?client_id=XXXXXXXXXX-isqd84kjnfu7o6gr7s1j6p79crvco2ms.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8090%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code
2018-09-07T03:34:05.791208+00:00 app[web.1]: 
2018-09-07T03:34:05.791210+00:00 app[web.1]: If your browser is on a different machine then exit and re-run this
2018-09-07T03:34:05.791212+00:00 app[web.1]: application with the command-line parameter
2018-09-07T03:34:05.791213+00:00 app[web.1]: 
2018-09-07T03:34:05.791215+00:00 app[web.1]:   --noauth_local_webserver
2018-09-07T03:34:05.803127+00:00 app[web.1]: 
```

**Comment by cnpants** [comment]
I both tried using:
`gc = pygsheets.authorize(service_account_file='XXXXXXXXXXXX.json')`

and
`gc = pygsheets.authorize()`

**Comment by cnpants** [comment]
Will try them, thanks!
