### ISSUE TITLE
Ability to Hyperlink cell values

### ISSUE THREAD

**Issue by ikmalpani** [nithinmurali/pygsheets#278]
I want to hyperlink some cells to open a webpage to get more information about the cell in question.

Given a set of cells with values in them and a set of links(URLs), I want to be able to embed the links to the values in the set of cells.

**Comment by nithinmurali** [comment]
won't just setting their value as the links work?

**Comment by ikmalpani** [comment]
Thanks for your quick response. I'm not sure how I would do that. I use the `set_dataframe` method to paste the entire data frame into the sheet and then format it.

**Comment by nithinmurali** [comment]
You can use this formula  `=HYPERLINK("https://www.facebook.com/public/asdfsdff", "text")` as the cell values. So just change the values in your dataframe

**Comment by ikmalpani** [comment]
Ok, thanks. Closing this issue! 👍
