### ISSUE TITLE
"Infinity" string causes error when downloading data

### ISSUE THREAD

**Issue by ritterSC** [nithinmurali/pygsheets#279]
If you have a spreadsheet containing a cell with the string "Infinity", when downloading the data trough `worksheet.get_as_df()` or `worksheet.get_all_records()`, it'll be interpreted as `float("inf")` causing loss of data and an HTTP error if you try to upload it again using `worksheet.set_dataframe()`:

`HttpError: <HttpError 400 when requesting: .... returned "Invalid JSON payload received. Unexpected token.`

My workaround is downloading the data trough `worksheet.get_all_values()`, which is a bit less convenient.

**Comment by nithinmurali** [comment]
Confirmed that it is converting string to float. But i am able to successfully update the sheet again using `set_dataframe`.

**Comment by nithinmurali** [comment]
Also what is the version of pygsheets you are using ?

**Comment by ritterSC** [comment]
1.1.4 downloaded from github

**Comment by ritterSC** [comment]
The complete traceback from the `set_dataframe`
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-309-3cb34c3a61ff> in <module>()
----> 1 oi2.set_dataframe(teste, (1,1))

~\Anaconda3\lib\site-packages\pygsheets\worksheet.py in set_dataframe(self, df, start, copy_index, copy_head, fit, escape_formulae, nan)
    999                         row[i] = "'" + str(row[i])
   1000         crange = format_addr(start) + ':' + end
-> 1001         self.update_cells(crange=crange, values=values)
   1002 
   1003     def get_as_df(self, has_header=True, index_colum=None, start=None, end=None, numerize=True, empty_value=''):

~\Anaconda3\lib\site-packages\pygsheets\worksheet.py in update_cells(self, crange, values, cell_list, extend, majordim, parse)
    518         body['values'] = values
    519         parse = parse if parse is not None else self.spreadsheet.default_parse
--> 520         self.client.sh_update_range(self.spreadsheet.id, body, self.spreadsheet.batch_mode, parse=parse)
    521 
    522     def update_cells_prop(self, cell_list, fields='*'):

~\Anaconda3\lib\site-packages\pygsheets\client.py in sh_update_range(self, spreadsheet_id, body, batch, parse)
    387             final_request = self.service.spreadsheets().values().update(spreadsheetId=spreadsheet_id, range=body['range'],
    388                                                                         valueInputOption=cformat, body=body)
--> 389             self._execute_request(spreadsheet_id, final_request, batch)
    390         else:
    391             if batch_length == 0:

~\Anaconda3\lib\site-packages\pygsheets\client.py in _execute_request(self, spreadsheet_id, request, batch)
    453             for i in range(self.retries):
    454                 try:
--> 455                     response = request.execute()
    456                 except Exception as e:
    457                     if repr(e).find('timed out') == -1:

~\Anaconda3\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131         return positional_wrapper
    132 

~\Anaconda3\lib\site-packages\googleapiclient\http.py in execute(self, http, num_retries)
    840       callback(resp)
    841     if resp.status >= 300:
--> 842       raise HttpError(resp, content, uri=self.uri)
    843     return self.postproc(resp, content)
    844 

HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1BwkIwPc3xr8kC0_4_BQjQW44MZF-sR_NTwN1xPu04EE/values/Sheet1%21A1%3AB3?valueInputOption=USER_ENTERED&alt=json returned "Invalid JSON payload received. Unexpected token.
lues": [["Brand"], [Infinity]]}
                    ^">

**Comment by nithinmurali** [comment]
Try using the latest version from staging or master (if it dosen't break your code) `set_dataframe` bug is fixed in the them.

May i know what is the workaround using the get_all_values? Wont it again be converted to a `inf` if you create a `df` from it?

**Comment by nithinmurali** [comment]
try setting the `numerize=False`, it should work

**Comment by ritterSC** [comment]
It works indeed. Thank you!

**Comment by nithinmurali** [comment]
If you still want your numbers to be converted to numbers, use `value_render=pygsheets.ValueRenderOption.UNFORMATTED_VALUE`
