### ISSUE TITLE
Issue when accessing team drive sheets

### ISSUE THREAD

**Issue by dcarrion87** [nithinmurali/pygsheets#282]
Whenever trying to access team drive sheets I get  "The caller does not have permission".

No issues after moving sheet into regular user drive space and sharing.

Is this something related to scope or additional permission needed to be granted on top of service account Editor to the sheet?

--

googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/....?fields=properties%2Csheets%2Fproperties%2CspreadsheetId%2CnamedRanges&includeGridData=false&alt=json returned "The caller does not have permission">

**Comment by nithinmurali** [comment]
did you enable team drive ?  also where did you install pygsheets from ?

**Comment by dcarrion87** [comment]
fixed with update to version from github

Thanks!
