### ISSUE TITLE
can i get unformatted values with wks.get_all_records() ?

### ISSUE THREAD

**Issue by keyapi** [nithinmurali/pygsheets#284]
i have some gsheets columms with mixed data types, like below and i want to keep them

- Variation.number
- 21107_21108_21109_01
- 21107

when i run wks.get_all_records(), i just got a list like below, the underscores"_" are all missing.
[{'Variation.number': **21107211082110901**}, {'Variation.number': 21107}]

i know there's a method value_unformatted to get unformatted value of a cell.
is there a method to get all unformatted values? maybe with wks.get_all_records()?

Thx
Key

**Comment by Rizhiy** [comment]
On a similar note, can you please add ability to pass kwargs for `get_values` to `get_value`?
