### ISSUE TITLE
append_table keeps formatting of the first row

### ISSUE THREAD

**Issue by karambaq** [nithinmurali/pygsheets#285]
Hey, I'm trying to append_table with the frozen title row, which format in color and bold font
I want that appended rows appends without formatting, how can I do that? Thank you.

**Comment by nithinmurali** [comment]
append_table is just a wrapper around `spreadsheets.values.append` . It dosen't provide any customization options. Hence this might be its behavior. You might need to do the un-formatting manually using other calls.
