### ISSUE TITLE
Dependency oauth2client is missing when installing from pip

### ISSUE THREAD

**Issue by MarkBird** [nithinmurali/pygsheets#290]
**Describe the bug**
Installing version 1.1.4 via pip does not install the oauth2client dependency. client.py has multiple references to oauth2client

**To Reproduce**
pip install pygsheets

**System Information**
 - OS: Windows 10
 - pygsheets version : 1.1.4
 - pygsheets installed from (github or pypi): pypi

**Comment by sauravhiremath** [comment]
Explicitly install <b>oauth2client</b> using pip command.

Try

` ` `
pip install oauth2client
` ` `

**Comment by FukujiMihoko** [comment]
`pygsheets==2.0.0` doesn't depend on `oauth2client` anymore so I think this can be closed.

**Comment by sauravhiremath** [comment]
Agreed. Issue can be closed
