### ISSUE TITLE
Update range cells

### ISSUE THREAD

**Issue by dimkoug** [nithinmurali/pygsheets#293]
**Describe the bug**
When i want to update a range of cells i get AttributeError

```
code here ...
# Traceback (most recent call last):
  File "quickstart.py", line 203, in <module>
    get_data(data, gc, months)
  File "quickstart.py", line 117, in get_data
    wks_sheet.update_cells('d2:aj2', dates)
  File "/home/dimitris/googlesheets/env/src/pygsheets/pygsheets/worksheet.py", line 639, in update_cells
    request = cell.update(get_request=True, worksheet_id=self.id)
AttributeError: 'str' object has no attribute 'update'

```

**System Information**
 - OS: Ubuntu
 - pygsheets version : latest clone from repository
 - pygsheets installed from (github or pypi): github

**Comment by nithinmurali** [comment]
in the new version, [update_cells](https://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.update_cells) will update the cell properties. You need to use [update_values](https://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.update_values)
