### ISSUE TITLE
Get raw cell information

### ISSUE THREAD

**Issue by Rizhiy** [nithinmurali/pygsheets#295]
**Is your feature request related to a problem? Please describe.**
I need to get raw cell information, i.e. if a cell has a formula, then I need to get a formula of that cell.

**Describe the solution you'd like**
I would like either a separate function in worksheet or ideally a new attribute for cell named something like `raw_content`, e.g.
```python
cell = worksheet.cell((x, y))
print(cell.raw_content)

# =AVERAGE(C3:D3)
```

or the one I'm more interested in
```python
cell = worksheet.cell((x, y))
print(cell.raw_content)

# =HYPERLINK("https://github.com/nithinmurali/pygsheets/issues/295","issue")
```

**Any other info**
Would also be nice to have comments and other information.

**Comment by nithinmurali** [comment]
there are 3 values for a cell, the `value`, `value_unformatted`, `formula` . for your case just use 

```
cell = worksheet.cell((x, y))
print(cell.formula)
```

**Comment by nithinmurali** [comment]
maybe we should update the docs to highlight this info

**Comment by Rizhiy** [comment]
This doesn't work for me. It just returns empty string for `cell.formula`.

**Comment by Rizhiy** [comment]
Just to be clear: I want to get the function from existing spreadsheet.

**Comment by Rizhiy** [comment]
Thanks, that works, I think I was searching for `function` instead of `formula` and couldn't find it.

I think either make `cell.function` reference `cell.formula` in docs or make a property in the code.

**Comment by nithinmurali** [comment]
> Would also be nice to have comments and other information.

The sheets api dosent give access to comments, so its not possible at the moment. But you can acess all other information like notes, color etc. see [cell doc](https://pygsheets.readthedocs.io/en/stable/cell.html)
