### ISSUE TITLE
Efficient Batch Formatting

### ISSUE THREAD

**Issue by Djones4822** [nithinmurali/pygsheets#299]
I'm working on creating a sheet where I dump a dataset in and then format the rows to a certain color based on column attributes. I've found that I don't have a "great" solution for the whole-row formatting option. 

within the worksheet object there should be a way to apply format rules by arbitrary label sets and handle the updates with as few calls as possible.

Right now I've written each of my "Format types" into a custom request and pass them that way, am I missing something easier?

**Comment by nithinmurali** [comment]
If i understand your issue correctly, you want to apply some formatting to a group of cells rt? You can use the `apply_format` method in DataRange

**Comment by nithinmurali** [comment]
You can get a datarange by setting returnas='range' for almost all the get_* functions. You can also instantiate a Datarange object using the datarange class.  But yes all of these methods will fetch the data if not provided (except when you provide the data in `data` param of constructor).

Will change the datarange to do lazy fetching.

**Comment by wgordon17** [comment]
@nithinmurali The `apply_format` seems perfect, except is assumes there's already an existing cell with the matching style. Is there anyway to specify the style explictly? Otherwise, I would have to manually style 1 cell, then update all cells to match.

**Comment by wgordon17** [comment]
Nevermind ;) I just figured out I can use `unlinked` cells...it does make it much easier!

```
worksheet.range('A1:A30', returnas='range').apply_format(Cell('A1').set_text_format('bold', True))
```
