### ISSUE TITLE
share method is not supported email with '_'(underscore)

### ISSUE THREAD

**Issue by JIhan-Jin** [nithinmurali/pygsheets#301]
Hello

Share method is not supported email with '_'(underscore).
But Google Drive Rest API supports to email with '_'(underscore).

It works well if there is no underscore,
in the opposite case, an exception occurs.

Check Please.
Thanks :)

[Version]
- 2.0.0, 1.1.4

[Example Code]
gsheets = pygsheets.authorize()
spreadsheet = gsheets.open_by_key(spreadsheet_key)
spreadsheets.share('test_underscore@example.com', 'writer') # execption occurs

[Exception - v2.0.0]
pygsheets.exceptions.InvalidArgumentValue: The provided e-mail address doesn't have a valid format: test_underscore@example.com.

[Cause]
in 'drive.py'
_EMAIL_PATTERN = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@[-a-zA-Z0-9.]+\.\w+)\"?")

**Comment by nithinmurali** [comment]
Will remove the email pattern check and will let google handle it.

**Comment by JIhan-Jin** [comment]
Thanks :)
