### ISSUE TITLE
date_time_render has wrong default, and is not available as a parameter

### ISSUE THREAD

**Issue by traynier** [nithinmurali/pygsheets#302]
**Describe the bug**
wks.get_range documentation says that `"The default dateTime render option is [DateTimeRenderOption.SERIAL_NUMBER"`.  But it isn't, its FORMATTED_STRING (as a default on Client.get_range in client.py line 185).

I cannot see any functions where I can optionally provide a DateTimeRenderOption, and hence:

**Related feature request**
As a aside to this, I ideally need the ability to switch between DateTimeRenderOptions on the various worksheet get_value/get_values/get_all_values functions. 

e.g. I would like to call:

```
wks.get_all_values(include_tailing_empty=False, include_tailing_empty_rows=False, value_render='UNFORMATTED_VALUE', date_time_render='SERIAL_NUMBER')
```

but date_time_render is not implemented.

**Comment by nithinmurali** [comment]
added features requested in  9718702
