### ISSUE TITLE
append_table adds cells before row values

### ISSUE THREAD

**Issue by OSjerick** [nithinmurali/pygsheets#303]
I'm trying to append rows (using a for loop) to an existing spreadsheet using `append_table`. The rows have these values:
```
rows = [['2018-12-05 08:05:25 UTC', 'software', 'Basic Tax Software', 29.95, 19.95, '', '', '', ''],
['2018-12-05 08:05:25 UTC', 'software', 'Deluxe Tax Software', 54.95, 44.95, '', '', '', ''],
['2018-12-05 08:05:25 UTC', 'software', 'Premium Tax Software', 74.95, 64.95, '', '', '', ''],
['2018-12-05 08:05:25 UTC', 'software', 'Premium & Business', 89.95, 79.95, '', '', '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Self-Employed', 119.99, 89.99, '', 39.99, '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Deluxe', 59.99, 39.99, '', 39.99, '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Live Deluxe', 119.99, 89.99, '', 39.99, '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Live Premier', 169.99, 139.99, '', 39.99, '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Premier', 79.99, 59.99, '', 39.99, '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Live Basic', 79.99, 49.99, '', 29.99, '', ''],
['2018-12-05 17:41:19 UTC', 'online', 'Live Self-Employed', 199.99, 169.99, '', 39.99, '', '']]
```
The problem I have is that for an empty worksheet several of the firsts rows are rendered with some blank self before values. What is the possible cause of this?
![screenshot_2018-12-05 untitled spreadsheet](https://user-images.githubusercontent.com/8047984/49545016-cd7a1f80-f8b2-11e8-96ba-18f05a2c7ec2.png)
![screenshot_2018-12-05 untitled spreadsheet 1](https://user-images.githubusercontent.com/8047984/49545019-d4089700-f8b2-11e8-972a-42880865878b.png)

**Comment by OSjerick** [comment]
I think the issue is related to rows which has empty values ('', None) in between other values, for example: `['2018-12-05 17:41:19 UTC', 'online', 'Self-Employed', 119.99, 89.99, '', 39.99, '', '']`.

**Comment by nithinmurali** [comment]
You are trying to append these rows on an empty sheet rt?

**Comment by OSjerick** [comment]
> 
> 
> You are trying to append these rows on an empty sheet rt?

Yes, it is an empty sheet. Why is this happening? I have tested with a non-empty sheet and everything works well.

**Comment by OSjerick** [comment]
> 
> 
> I will try reproducing the same. But the append table is just a wrapper around the append_table request by google. You can check how it is working(i think it Expects some existing table) . Else u you can use insert_row to insert a row first and then append table.

Oh, I understand. I did that and it is working right now. It is interesting that this issue doesn't happen if the first time you append rows they don't have empty values in between.
