### ISSUE TITLE
Set Proxy?

### ISSUE THREAD

**Issue by waltonereed** [nithinmurali/pygsheets#307]
Hello,
I'm trying to run the library behind my corporate firewall and am getting issues. IT says if I change the proxy it should work (and indeed my script works fine when I'm off my corporate network). 

Is there a simple implementation of this or do I need to go into the source code and change things?
Thanks!
Walt

**Comment by nithinmurali** [comment]
You wont need to change anything in the code. You can pass a custom http request object into the client with the proxies set. But you wont be able to use the authorize() function to create credentials, you will have to create them yourself and pass into Client.

[https://pygsheets.readthedocs.io/en/stable/reference.html#pygsheets.client.Client](https://pygsheets.readthedocs.io/en/stable/reference.html#pygsheets.client.Client
)

**Comment by waltonereed** [comment]
Thanks for your help! The least painful way for me to get this working again was by slightly modifying the `client.py` file as such:
`from httplib2 import socks`
`http_client = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, 'enteryourproxyinfo', 'enter your proxy port'))`

**Comment by waltonereed** [comment]
After updating to v 2.0.0, a different approach has to be taken since the dependency on `oauth2client` was removed and now uses `google-auth` and `google-auth-oauth`. 
Specifically for Windows:
1. Set environment variables for `HTTP_PROXY` and `HTTPS_PROXY`. 
2. `pip install httplib2shim` 
3. Open `google_auth_httplib2.py` file
4. In the import statement, modify from `import httplib2` to `import httplib2shim as httplib2` 

Hopefully this will help anyone with this need in the future.

**Comment by ddow** [comment]
@waltonereed  Its helping me now, thanks! @nithinmurali Any plans to add a proxy= arg to the main client?

**Comment by nithinmurali** [comment]
Yeah, will check if that can be implemented.

**Comment by lidatou1991** [comment]
> Thanks for your help! The least painful way for me to get this working again was by slightly modifying the `client.py` file as such:
> `from httplib2 import socks`
> `http_client = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, 'enteryourproxyinfo', 'enter your proxy port'))`

I am using shadowcks to access google server in China. I modified the `client.py` by adding codes below:

`import httplib2

from httplib2 import socks

http_client = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_SOCKS5, '127.0.0.1', '1086'))
`

still get the operation time error. Could you please help, thanks in advance? More information at [issue](https://github.com/nithinmurali/pygsheets/issues/274#issuecomment-495920566)

**Comment by nithinmurali** [comment]
http paramter added in 5bb558c7c9096de4a3bea7d8fc413e2d056d1815
