### ISSUE TITLE
Service account blocked, captcha required to unblock

### ISSUE THREAD

**Issue by rhcpfan** [nithinmurali/pygsheets#313]
I have shared the service account credentials file with someone in another country (both working on the same project). He ran the python script that modifies the worksheets just fine. After a few minutes, when I have tried to run it again, I've got an error:

"Our systems have detected unusual traffic from your computer network.  This page checks to see if it's really you sending the requests, and not a robot. "

Here's the Response (`resp`):
```html
{
    'status': '503', 
    'content-length': '3430', 
    'x-xss-protection': '1; mode=block',
    'expires': 'Fri, 01 Jan 1990 00:00:00 GMT',
    'server': 'HTTP server (unknown)', 
    'pragma': 'no-cache', 
    'cache-control': 'no-store, no-cache, must-revalidate',
    'date': 'Tue, 05 Feb 2019 15:13:32 GMT', 
    'alt-svc': 'quic=":443"; ma=2592000; v="44,43,39"',
    'content-type': 'text/html'
}
``` 

And here's the content (that's where I got the error message from):

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://sheets.googleapis.com/v4/spreadsheets/1-P6yRD9YOJrusYCJN79TE3XJtY_5cSyN2RT7ybn_cs0?fields=properties%2Csheets%2Fproperties%2CspreadsheetId%2CnamedRanges&amp;alt=json&amp;includeGridData=false</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
To continue, please type the characters below:<br><br>
<img src="/sorry/image?id=3034596771474720609&amp;q=EgRSTFVeGJvQ5uIFIhkA8aeDS3CIqr-jMLKSID-7m1L6CSZGPwOxMgFj&amp;hl=en&amp;continue=https://sheets.googleapis.com/v4/spreadsheets/1-P6yRD9YOJrusYCJN79TE3XJtY_5cSyN2RT7ybn_cs0%3Ffields%3Dproperties%252Csheets%252Fproperties%252CspreadsheetId%252CnamedRanges%26alt%3Djson%26includeGridData%3Dfalse" border="1" alt="Please enable images"><br><br>
<input type="text" name="captcha" value="" id="captcha" size="12" style="font-size:16px; padding:3px 0 3px 5px; margin-left:0px;"><br><br><br>
<input type="submit" name="btn-submit" value="Submit" style="font-size:18px; padding:4px 0;">
<input type='hidden' name='q' value='EgRSTFVeGJvQ5uIFIhkA8aeDS3CIqr-jMLKSID-7m1L6CSZGPwOxMgFj'><input type="hidden" name="continue" value="https://sheets.googleapis.com/v4/spreadsheets/1-P6yRD9YOJrusYCJN79TE3XJtY_5cSyN2RT7ybn_cs0?fields=properties%2Csheets%2Fproperties%2CspreadsheetId%2CnamedRanges&amp;alt=json&amp;includeGridData=false">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

IP address: MY_IP_ADDRESS<br>Time: 2019-02-05T15:13:32Z<br>URL: https://sheets.googleapis.com/v4/spreadsheets/1-P6yRD9YOJrusYCJN79TE3XJtY_5cSyN2RT7ybn_cs0?fields=properties%2Csheets%2Fproperties%2CspreadsheetId%2CnamedRanges&amp;alt=json&amp;includeGridData=false<br>
</div>
</div>
</body>
</html>
```

How can I avoid this in the future? Is it possible to add support for filling out the reCAPTCHA and unblocking the trafic?

**Comment by rai2048iiit** [comment]
I also faced this issue.

**Comment by nithinmurali** [comment]
Well, I am not sure what triggered this. Usually when people make a lot of requests they get blocked by quota exhausted error not a captcha. I think **maybe** you using the service account from different countries might have triggered this. 

I am not really sure if filling the captcha is within the scope of this library, as that is a request you could make using any other http client and not specific to sheets api as such.

Unrelated to this library sometimes i face such google issue while browsing when i am behind some kind of proxy, which a lot of people use. As google think it a single person. are you behind one?

**Comment by rai2048iiit** [comment]
In my case, I'm making lots of google spreadsheet calls (read/write using pygsheets) and these calls are load balanced to 4 servers but all have the same external IP address.  Do you think if I get different external IP for all the servers it will help?

**Comment by rhcpfan** [comment]
I am not behind any proxy. 

This has worked very well for a long time, since there was only me calling the API. The issue appeared when my colleague made some calls from another country, so this must be the issue for sure.

The thing is that I cannot unblock the API, from what I’ve tried, nothing has worked...

I have reset the service account credentials, changed the auth JSON... It is still blocked...

**Comment by nithinmurali** [comment]
@rai2048iiit I think that would work. Other option is to create 4 service accounts. 

@rhcpfan Maybe try creating a new service account? also new service account for your colleague too. Did you check if a google search is working ?

**Comment by rhcpfan** [comment]
Google search works fine. I’ll try to create new service accounts.

If I have multiple service accounts, can I share the same data (spreadsheets) between them?

**Comment by nithinmurali** [comment]
Yes, you can. you would just need to share the sheets with all of them. If you want to skip the sharing use OAuth Credentials.
