### ISSUE TITLE
Unable to set text format "foregroundColor"

### ISSUE THREAD

**Issue by wgordon17** [nithinmurali/pygsheets#315]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**

Unable to set a "foregroundColor" on a cell

**To Reproduce**
```
cell = ws.cell('A1')
cell.set_text_format('foregroundColor', (0, 255, 0, 255))

# googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1OhrxYuGIdEnC_60uA7uZDUHX3ynBJ0atSPY-wVD34_Y:batchUpdate?fields=%2A&alt=json returned "Invalid JSON payload received. Unknown name "foreground_color" at 'requests[0].repeat_cell.cell.user_entered_format.text_format': Proto field is not repeating, cannot start list.">
```

**System Information**
 - OS: MacOS 10.14.3
 - pygsheets version : 2.0.0
 - pygsheets installed from (github or pypi): pypi

**Comment by nithinmurali** [comment]
`cell.set_text_format('foregroundColor', (0, 1, 0, 1))`   use decimal form 0-1 for color intensity.
