### ISSUE TITLE
Worksheet.update_cells does not update cells.

### ISSUE THREAD

**Issue by nicker-bocker** [nithinmurali/pygsheets#319]
Worksheet.update_cells does not update cells.

**To Reproduce**
This is reproduced using the documented example. 
```
import pygsheets

client = pygsheets.authorize()
sh = client.open('Betting Odds')
wks = sh.sheet1
wks.update_cells('A2:A5',[['name1'],['name2'],['name3'],['name4']])
```

The issue is the documentation specifies a string cell value to be passed but the update_cells method expects a list of Cell objects. There is no conversion of the string to a Cell object anywhere so it is raising this error
```
request = cell.update(get_request=True, worksheet_id=self.id)
AttributeError: 'str' object has no attribute 'update'
```

**Comment by nithinmurali** [comment]
Hi, you should use [update_values](https://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.update_values) to update cell values from a matrix( list of lists )
