### ISSUE TITLE
Basic usage according to documentation fails

### ISSUE THREAD

**Issue by helgihg** [nithinmurali/pygsheets#321]
The "Basic usage" section is missing the definition of an array which is included in the code: my_nparray

Upon running the basic usage, one receives the error: "NameError: name 'my_nparray' is not defined"

The array or examples of what it should contain are also nowhere to be found.

**Comment by nithinmurali** [comment]
It is assumed that you already have a numpy array which is to be written to the sheet
```
import numpy as np
my_nparray = np.random.randint(10, size=(3, 4))
```

above code will generate a dummy array, which you can use there. I will add this to docs.
