### ISSUE TITLE
Problem with custom_requests() call

### ISSUE THREAD

**Issue by Stefan2142** [nithinmurali/pygsheets#324]
I tried calling custom_requests() method on worksheet object. 
Im calling it like this:
```
def create_req(id)
    return {'requests': [{'addConditionalFormatRule': {'index': 0, 'rule': {'ranges': [{'endColumnIndex': 10, 'sheetId': id, 'startColumnIndex': 9}], 'gradientRule': {'maxpoint': {'color': {'green': 0.9}, 'type': 'MAX'}, 'minpoint': {'color': {'green': 0.2, 'red': 0.8}, 'type': 'MIN'}}}}}]}

gc = pygsheets.authorize(client_secret='google_secret.json')
sh = gc.create('PY to Gsheet Test')
sh.custom_request(create_req(sh.id),'')
```
```
Error code:
    sh.custom_request(create_req(sh.id),'')
  File "c:\python27\lib\site-packages\pygsheets\spreadsheet.py", line 342, in custom_request
    return self.client.sh_batch_update(self.id, request, fields=fields, batch=False)
AttributeError: 'Client' object has no attribute 'sh_batch_update'
```
Now, I may be passing wrong parameters (especially that second one, im not sure what 'Fields' argument is, but nevertheless this looks like the bug in library because Client doesnt seem to have 'sh_batch_update' attribute

    

[Link to that method in docs](https://pygsheets.readthedocs.io/en/stable/spreadsheet.html#pygsheets.Spreadsheet.custom_request) 
**System Information**
 - OS: WIN10
 - pygsheets version : 2.0.0
 - pygsheets installed from (github or pypi): pip

**Comment by nithinmurali** [comment]
This is a bug which is fixed in the trunk. Please install from github 
`pip install https://github.com/nithinmurali/pygsheets/archive/master.zip` . Fields is a standard parameter of the batch Request. If you don't wanna use it just pass * .
