### ISSUE TITLE
Exclude Tailing Rows

### ISSUE THREAD

**Issue by ngordenier** [nithinmurali/pygsheets#329]
In version 1.1.4 when pulling down a sheet as a df it excluded the empty rows at the bottom of the sheet. The default behavior is now to pull all rows regardless. It looks like the most recent release fixed this issue for columns only. 

Can we add in that functionality to remove tailing_rows. Here is the call on the get_al_values function. 
include_tailing_empty_rows=True

**Comment by nithinmurali** [comment]
Sure, there is no need for empty rows to be pulled.
