### ISSUE TITLE
MemoryError when getting Sheet

### ISSUE THREAD

**Issue by jfcralo** [nithinmurali/pygsheets#337]
Hi,

I'm try to make a script to get all data in a single spreadsheet:

code:
import pygsheets

CM_SPREADSHEET_ID = 'spreadsheet_ID'
CM_RANGE_NAME = 'spreadsheet_range'

c = pygsheets.authorize(outh_file='client_secret.json')
wrk = c.sheet.get(CM_SPREADSHEET_ID)
sh = wrk.get_range(CM_RANGE_NAME)
sh.export(filename="Interventions.xlsx")

I'm getting the following error:
Traceback (most recent call last):
  File "C:/Users/jralo/Documents/stuff/Intervenions/teste2.py", line 7, in <module>
    wrk = c.sheet.get(CM_SPREADSHEET_ID)
  File "C:\Python37-32\Lib\site-packages\pygsheets\sheet.py", line 138, in get
    return self._execute_requests(self.service.spreadsheets().get(spreadsheetId=spreadsheet_id, **kwargs))
  File "C:\Python37-32\Lib\site-packages\pygsheets\sheet.py", line 351, in _execute_requests
    response = request.execute(num_retries=self.retries)
  File "C:\Python37-32\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python37-32\Lib\site-packages\googleapiclient\http.py", line 852, in execute
    return self.postproc(resp, content)
  File "C:\Python37-32\Lib\site-packages\googleapiclient\model.py", line 209, in response
    return self.deserialize(content)
  File "C:\Python37-32\Lib\site-packages\googleapiclient\model.py", line 264, in deserialize
    content = content.decode('utf-8')
MemoryError

What can be causing this? My Sheet is just too big?

**Comment by nithinmurali** [comment]
how large is your sheet?

**Comment by jfcralo** [comment]
hey, 4713 rows, 25 columns

**Comment by nithinmurali** [comment]
That's not  too large. I will try replicating this.

**Comment by jfcralo** [comment]
Hello, any luck with this issue?

**Comment by nithinmurali** [comment]
> sh = wrk.get_range(CM_RANGE_NAME)

what are you trying to do here?

I tried exporting a large sheet and it works. export method is available for spreadsheet and worksheet.

**Comment by nithinmurali** [comment]
why are you using the client.sheet ? that is only for internal use. it wont return a spreadsheet instance. Checkout the examples on how to use the library. 

you need to use `c.open_by_key` or `c.open`

**Comment by jfcralo** [comment]
Hey you are right, I used open_by_key instead of get and it works!
Thank you very much!

**Comment by mgmagnitude** [comment]
sorry, i'm a newbie here (not sure about code of conduct, to begin with), but i simply can't find anywhere the proper syntax for exporting the google sheets in xlsx format. default is csv, but what about xlsx?
sh.export(file_format=???, filename='Interventions.xlsx')
sorry for barging like this, but i'm pretty desperate ...

ps pygsheets really made my life so much easier :-)

**Comment by jfcralo** [comment]
Hey mgmagnitude, you are right the documentation is lacking some details.
I'm not sure you can export the googlesheet data directly to a xlsx file like that.
What I do is create a xlsx file with xlsxwriter library, then write the data from the google sheet to that file with the write_row function.

**Comment by nithinmurali** [comment]
Hi, I noticed that the documentation is lacking there, will update.

You can see that file_format takes in a ExportType enum. You can see it [here](https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/custom_types.py#L73). So for xlsx use `file_format=ExportType.XLS`

**Comment by mgmagnitude** [comment]
woo-hoo!!!! thank you very much! both of you! so, just to, maybe, help some newbie like myself, this worked for me like a breeze:

filef='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:.xlsx'
sh.export(file_format=filef, filename='blah')

and again, pygsheets rocks! 🥇
