### ISSUE TITLE
`cells_data.append([s3_bucket_name, last_modified, tags])` get from JSON: "... "Invalid values[40][2]: list_value { ..." after last S3 bucket is processed

### ISSUE THREAD

**Issue by rbarakjsonar** [nithinmurali/pygsheets#338]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**

When I run the below script, after line 98 is being executed for the last time
I get the traceback as below (if line 98 is commented out, no traceback occures):

...
Bucket: ury2 Tags: no_tags last_modified: "2019-01-16 23:14:11+00:00"
counter: 230
Bucket: wiki.jsonar.com Tags: no_tags last_modified: "2015-10-22 07:06:12+00:00"
counter: 231
Bucket: yael-cloudtrail-bucket Tags: no_tags last_modified: "2019-04-02 02:00:06+00:00"
counter: 232
Bucket: yhager Tags: no_tags last_modified: "2017-04-02 04:07:23+00:00"
counter: 233
Traceback (most recent call last):
  File "../stackoverflow/so_s3_3.py", line 114, in <module>
    s3_worksheet_creation(spread_sheet, regions)
  File "../stackoverflow/so_s3_3.py", line 107, in s3_worksheet_creation
    populate_cells(start_cell='A2', cells_data=cells_data, worksheet=worksheet)
  File "../stackoverflow/so_s3_3.py", line 34, in populate_cells
    worksheet.update_values(start_cell, cells_data)
  File "/usr/lib/python3.6/site-packages/pygsheets/worksheet.py", line 644, in update_values
    self.client.sheet.values_batch_update(self.spreadsheet.id, body, parse)
  File "/usr/lib/python3.6/site-packages/pygsheets/sheet.py", line 273, in values_batch_update
    self._execute_requests(request)
  File "/usr/lib/python3.6/site-packages/pygsheets/sheet.py", line 351, in _execute_requests
    response = request.execute(num_retries=self.retries)
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1mPrMPbXg1RE3IDKCwdgo5tx_eKzZzKPzekKMjrflNpI/values/s3%21A2%3AD236?valueInputOption=USER_ENTERED&alt=json returned "Invalid values[40][2]: list_value {
  values {
    struct_value {
      fields {
        key: "Key"
        value {
          string_value: "aws:cloudformation:stack-id"
        }
      }
      fields {
        key: "Value"
        value {
          string_value: "arn:aws:cloudformation:ca-central-1:627577395509:stack/customer-instance-1/8e9df8e0-15cc-11e9-88d4-504dce355a1e"
        }
      }
    }
  }
  values {
    struct_value {
      fields {
        key: "Key"
        value {
          string_value: "aws:cloudformation:stack-name"
        }
      }
      fields {
        key: "Value"
        value {
          string_value: "customer-instance-1"
        }
      }
    }
  }
  values {
    struct_value {
      fields {
        key: "Key"
        value {
          string_value: "aws:cloudformation:logical-id"
        }
      }
      fields {
        key: "Value"
        value {
          string_value: "SonarS3Bucket"
        }
      }
    }
  }
}">

**To Reproduce**
```
import collections
import boto3, botocore
import datetime
import json
import os
import pprint 
import pygsheets

pp = pprint.PrettyPrinter(indent=4)

currentDT = str(datetime.datetime.now())


def create_spreadsheet(outh_file, spreadsheet_name = "jSonar AWS usage"):
    client = pygsheets.authorize()
    client.spreadsheet_titles()
    spread_sheet = client.create(spreadsheet_name)
    return spread_sheet


def populate_headers(headers_data, worksheet):
    h = headers_data
    header = dict()
    for i in range(len(h)):
        col = i + 1
        header[col] = worksheet.cell(h[col].cell)
        header[col].value = h[col].name
        header[col].text_format['bold'] = h[col].bold
        #pp.pprint(header[col])    
        header[col].update()


def populate_cells(start_cell, cells_data, worksheet):
    worksheet.update_values(start_cell, cells_data)


def get_regions():
    region = "us-east-1"
    region = "ap-northeast-1"
    region = "us-west-1"
    regions = dict()

    ec2 = boto3.client("ec2", region_name=region)
    ec2_responses = ec2.describe_regions()

    ssm_client = boto3.client('ssm', region_name=region)
    for resp in ec2_responses['Regions']:
        region_id = resp['RegionName']
        tmp = '/aws/service/global-infrastructure/regions/%s/longName' % region_id
        ssm_response = ssm_client.get_parameter(Name = tmp)
        region_name = ssm_response['Parameter']['Value'] 
        regions[region_id] = region_name
    return(regions)

            
def s3_worksheet_creation(spread_sheet, regions):
    worksheet = spread_sheet.add_worksheet("s3", rows=100, cols=26, src_tuple=None, src_worksheet=None, index=None)
    Header = collections.namedtuple('Header', 'cell name bold')
    s3_header_data = dict()
    s3_header_data[1] = Header(cell='A1', name='Name', bold=True)
    s3_header_data[2] = Header(cell='B1', name='Tags', bold=True)
    s3_header_data[3] = Header(cell='C1', name='Last Modified', bold=True)
    s3_header_data[4] = Header(cell='D1', name='WorksheetCreated: %s' % currentDT, bold=False)
    populate_headers(headers_data=s3_header_data, worksheet=worksheet)
   
    cells_data = list()
    for region, region_h in sorted(regions.items()):
        print()
        #print("{} buckets in {}".format("S3", region_h))
        print("{} buckets".format("S3",))
        print("---------------------------")
        s3_client = boto3.client('s3', region_name=region)
        s3_resource = boto3.resource('s3', region_name=region)
        paginator = s3_client.get_paginator("list_objects_v2")
        buckets = s3_client.list_buckets()

        counter = 0
        for bucket in s3_resource.buckets.all():
            try:
                s3_bucket_name = bucket.name
            except botocore.exceptions.ClientError:
                print("+++ Not Authorised to read bucket info (bucket.name) +++")
                continue
            pages = paginator.paginate(Bucket=s3_bucket_name)
            try:
                for page in pages:
                    try:
                        last_modified = json.dumps(page['Contents'][0]['LastModified'], 
                                        indent=4, sort_keys=True, default=str)
                    except KeyError:
                        last_modified = "unknown"
                    try:
                        response = s3_client.get_bucket_tagging(Bucket=s3_bucket_name)
                        tags = response['TagSet']
                    except botocore.exceptions.ClientError:
                        tags = "no_tags"
                    print("Bucket:", s3_bucket_name, "Tags:", tags, "last_modified:", last_modified)
                    cells_data.append([s3_bucket_name, last_modified, tags])
                    counter += 1
                    print("counter:", counter)
                    break
            except botocore.exceptions.ClientError:
                print("+++ Not Authorised to read bucket info (for page in pages) +++")
                cells_data.append([s3_bucket_name, "not authorised to read", "not authorised to read"])
                continue
        break # S3 doesn't have regions, so we break after one region.
    populate_cells(start_cell='A2', cells_data=cells_data, worksheet=worksheet)


if __name__ == "__main__":
    spread_sheet = create_spreadsheet(spreadsheet_name = "jSonar AWS usage", outh_file = '../client_secret.json')
    regions = get_regions()

    s3_worksheet_creation(spread_sheet, regions)

    # share the sheet by email
    spread_sheet.share("rbarak@jsonar.com")

# see error
```

**System Information**
 - OS: CentOS 7
 - pygsheets version : 2
 - pygsheets installed from (github or pypi): pip install pygsheets

**Comment by nithinmurali** [comment]
There is some issue with the data you are sending. make sure it is in the right format (2d list)

**Comment by rbarakjsonar** [comment]
Aha, thanks: after you pointed it out, I found and fixed my bug.
