### ISSUE TITLE
Add other input options for authorisation code

### ISSUE THREAD

**Issue by FIRE-AKA-DRAZN** [nithinmurali/pygsheets#339]
Not sure if if this is already supported or not, but I'm building a very simple front-end app that accesses google spreadsheets and pygsheets seems like the simplest solution.

However as far as I can tell the authorisation code needs to be entered via a console, and I would like my app to do this entirely through its UI.  The UI library is just tkinter.

Is there a way to do this?  If not I would like to request this as a feature

**Comment by nithinmurali** [comment]
authorization code? if you are running on local machine you wont need to copy paste code, everything should happen automatically.

**Comment by FIRE-AKA-DRAZN** [comment]
Hmm, that hasn't been my experience.  When my program goes to generate the access token, initially it would display in the console a link to google Oauth and you had to manually copy or click the link to go there.

Once there it does the usual google consent stuff then displays a page with an authentication code which you need to paste into the console.

For my program i got around this by using a custom version of the library with this code added to the authorization.py:

```python
 from tkinter import *
userInput = ""
authInput = ""
...
global userInput
    global authInput
    inputWindow = Tk()
    Label(inputWindow,text="Your web browser should have opened.\n\nFollow Google's instructions 
    there to get your authorisation code.\n\nOnce you have it, paste it into the box below and press the 
    'Authorise' button").pack()
    authInput = Entry(inputWindow)
    authInput.pack()
    Button(inputWindow,text="Authorise",command=lambda:[getEntry(),inputWindow.destroy()]).pack()
    inputWindow.mainloop()
    
    code = str(userInput)
    flow.fetch_token(code=code)
...
```
I wrote this in a hurry so it could be way cleaner but it gets the job done

But as far as i can tell, at-least in the code in the main repo this process was originally completely manual.  Hence my posting of this issue.
