### ISSUE TITLE
Program crashes when made into executable

### ISSUE THREAD

**Issue by FIRE-AKA-DRAZN** [nithinmurali/pygsheets#341]
After making program, which uses pygsheets as a library, an executable using pyinstaller the program crashes after authentication is completed

```
[Errno 2] No such file or directory: 'C:\\Users\\FIRE~1\\AppData\\Local\\Temp\\_MEI196682\\pygsheets\\data\\sheets_discovery.json'
```

[This was listed as a bug previously ](https://github.com/nithinmurali/pygsheets/issues/200) and I have tried the solutions listed there however this specific code has changed and the solutions no longer work.

**System Information**
 - OS: Win 7
 - pygsheets version : 2.0.1
 - pygsheets installed from : pip

**Comment by nithinmurali** [comment]
Hi, that code is moved into two places: [here](https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/sheet.py#L35) and [here.](https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/drive.py#L48). 

Loading from file was done to speedup the initialization. But we can make it optional.

**Comment by FIRE-AKA-DRAZN** [comment]
Thanks.  It would be helpful if you could, using your library to make a college project and part of the requirements is to have an .exe as a final product.

Been trying to jury rig a temporary solution for now:

sheet.py -
```
try:
     with open(os.path.join(data_path, "sheets_discovery.json")) as jd:
              self.service = discovery.build_from_document(json.load(jd), http=http)
except:
            self.service = discovery.build('sheets', 'v4', http=http)
```

drive.py -
```
try:
     with open(os.path.join(data_path, "drive_discovery.json")) as jd:
            self.service = discovery.build_from_document(json.load(jd), http=http)
except:
     self.driveService = discovery.build('drive', 'v3', http=http)
```

Probably not very elegant, i'm still learning, but this seems to still work when running the source code, however after making an .exe I get a new error:
```AttributeError: 'DriveAPIWrapper' object has no attribute 'service'```

Any idea why that happens?
