### ISSUE TITLE
Warning message not very helpful, as it doesn't actually identify the missing method, nor the line in the code that caused it.

### ISSUE THREAD

**Issue by rbarakjsonar** [nithinmurali/pygsheets#343]
If I run the following minimal script, I get the following warning:

```
$ cat ~/python/boto3-originalcontent/stackoverflow/so_s3_3.py
import pygsheets


def create_spreadsheet(outh_file, spreadsheet_name = "AWS usage"):
    client = pygsheets.authorize(outh_file=outh_file, outh_nonlocal=True)
    client.list_ssheets(parent_id=None)
    spread_sheet = client.create(spreadsheet_name)
    return spread_sheet


if __name__ == "__main__":
    spread_sheet = create_spreadsheet(spreadsheet_name = "AWS usage", outh_file = '../client_secret.json')
    spread_sheet.link(syncToCloud=False)
$ python3 ~/python/boto3-originalcontent/stackoverflow/so_s3_3.py
/usr/lib/python3.4/site-packages/pygsheets/spreadsheet.py:326: UserWarning: method not implimented
  warnings.warn("method not implimented")
$ 
```

That message is not very helpful, as it doesn't actually identify the missing method, nor the line in the code that caused it.

**Comment by nithinmurali** [comment]
pygsheets version?

**Comment by rbarakjsonar** [comment]
> pygsheets version

2

**Comment by nithinmurali** [comment]
There are no such warning in the 2.x. Maybe you are using an old version?

**Comment by rbarakjsonar** [comment]
> There are no such warning in the 2.x. Maybe you are using an old version?

I did a 'git clone' of version 2.
Is there a way to verify the version in effect.

**Comment by nithinmurali** [comment]
you can see the version in `pygsheets/__init__.py`. linking of spreadsheets is an old feature and is removed in 2.x. You must be using 1.x . That warning is raised by `link()` method of spreadsheet, which was not implemented.

**Comment by nithinmurali** [comment]
Closing as this looks solved
