### ISSUE TITLE
Setting formatting piecemeal for rows and cols.

### ISSUE THREAD

**Issue by ddow** [nithinmurali/pygsheets#347]
Currently, it seems if, for example, I want to update the color of an entire row or column but don't want to touch any other formatting like, say, font or text size, I have to do it one cell at a time.

This would rule:
row.color = [0, 1, 0, 0]
or
row.apply_format(cell, "color")

**Comment by nithinmurali** [comment]
Hey, you can use the range object to apply properties to multiple cells. Checkout the documentation [here](https://pygsheets.readthedocs.io/en/stable/datarange.html#pygsheets.DataRange.apply_format). Also see the examples in the github readme.

**Comment by nithinmurali** [comment]
Reopen is issue is not solved

**Comment by ddow** [comment]
I get that, but I'd like to only apply part of a format, not the whole thing. So, if text is bold in a red cell, I only want to export the red color to the whole row, not the bold text.

**Comment by ddow** [comment]
To be more specific, I have a column. At the top is a group name from my proprietary system that is mapped there. I find that the group name does not exist in my system. I want to alert the user that there is a problem so I turn that cell red. Down that column is text that describes users that should be in that group. I want to light up the entire column red. However, the top cell with the group name has bold text. I want to paste the whole column red, but I don't want to make the text in every cell in the column bold.

**Comment by nithinmurali** [comment]
While setting format you don't need to use an existing cell in the sheet, you can just create an unlinked cell (directly from cell class). Amd then set only the properties you need, in this case color and call range object apply format.

**Comment by ddow** [comment]
@nithinmurali Aha! Thanks!

**Comment by ddow** [comment]
@nithinmurali Is there a chance you can tell me what I'm doing wrong here?

`    def set_row_color(self, color):
        """
        Lights up a row because it looks cool and lets you know stuff is happening.
        :return: Nothing
        """
        model_cell = Cell('A1')
        model_cell.color = color  # rose color cell

        # now set its format to all cells in the range
        rng = self.sheet.get_row(self.row_count, returnas="range")
        rng.apply_format(model_cell)`

`  File "/Users/ddow/dev/charlotte/services/project_user_sync.py", line 376, in set_row_color
    rng.apply_format(model_cell)
AttributeError: 'list' object has no attribute 'apply_format'
`
Any help would be appreciated! Thanks!

**Comment by nithinmurali** [comment]
This was a bug, i have fixed it. if you dont wanna update you can use `sheel.get_values` as a workaround. But you don't need to get the row at all, as you don't need the data fetched. You can directly create a Datarange object and apply format.
```
Datarange('A1', 'A10', worksheet=sheet).apply_format(model_cell)
```
This will be much faster as the former will fetch complete row data and will build the datarange.

**Comment by ddow** [comment]
@nithinmurali Sorry to be a bug. The above works, but it resets all formatting. So, if I have a row and some of the cells have bold text and some don't and some are centered text and some aren't, when I do that above it changes the row color, but also sets all text in the row to non-bold and left justified. I'd like to change the color and nothing else in any cell. Does that make sense?

**Comment by nithinmurali** [comment]
The apply_format takes a param called fields, there you can specify what all fields of the model cell you want to apply. Check out the doc for apply_format

**Comment by cwdjankoski** [comment]
Hi @nithinmurali - many thanks for this super useful pkg.

I started writing an issue / question initially - but in the meantime i managed to figure out how to achieve what I thought is still not supported and i decided to post it here in case someone else might find it useful. Feel free to remove it or i can do so if you feel this place is not appropriate for such things. 

The goal is for example - formatting e.g. column A as percentage format, column B as currency format. Then formatting row 1 as white , row 2 as grey colour.

```
model_cell = pygsheets.Cell("A1")

model_cell.set_number_format(
    format_type = pygsheets.FormatType.PERCENT,
    pattern = "0%"
)
# first apply the percentage formatting
pygsheets.DataRange(
    left_corner_cell , right_corner_cell , worksheet = wks
 ).apply_format(model_cell)

# now apply the row-colouring interchangeably
gray_cell = pygsheets.Cell("A1")
gray_cell.color = (0.9529412, 0.9529412, 0.9529412, 0)

white_cell = pygsheets.Cell("A2")
white_cell.color = (1, 1, 1, 0)

cells = [gray_cell, white_cell]

for r in range(start_row, end_row + 1):
    print(f"Doing row {r} ...", flush = True, end = "\r")
    wks.get_row(r, returnas = "range").apply_format(cells[ r % 2 ], fields = "userEnteredFormat.backgroundColor")
```

**Comment by nithinmurali** [comment]
cool no problem, I was thinking of adding a section in docs some non-obvious examples. Will probably add this there.

**Comment by cwdjankoski** [comment]
I can also try my hand at contributing something like this example. 
Thanks again for the wonderful pkg.
