### ISSUE TITLE
How do I import a CSV to a sheet inside a worksheet ?

### ISSUE THREAD

**Issue by varunchandak** [nithinmurali/pygsheets#350]
**Is your feature request related to a problem? Please describe.**
Unable to find `import` option for csvs.

**Describe the solution you'd like**
Able to import CSV on my machine to a new sheet in a worksheet

**Any other info**
NA

**Comment by nithinmurali** [comment]
There is not direct option to import csv. But you can import the csv using pandas and then use  [set_dataframe](https://pygsheets.readthedocs.io/en/staging/worksheet.html#pygsheets.Worksheet.set_dataframe) method.
