### ISSUE TITLE
googleapiclient.errors.HttpError thrown after minor changes to running code

### ISSUE THREAD

**Issue by rbarakjsonar** [nithinmurali/pygsheets#351]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**

I made some minor changes (added columns that include only a header) to code that used to work, and now I get the following:

**To Reproduce**

python3 create_aws_usage_spreadsheet.py

------
[create_aws_usage_spreadsheet.py.txt](https://github.com/nithinmurali/pygsheets/files/3259537/create_aws_usage_spreadsheet.py.txt)
------

```
Code:

[create_aws_usage_spreadsheet.py.txt](https://github.com/nithinmurali/pygsheets/files/3259537/create_aws_usage_spreadsheet.py.txt)

print("code is in https://github.com/nithinmurali/pygsheets/files/3259537/create_aws_usage_spreadsheet.py.txt")

```

**System Information**
 - OS: CentOs/rhel 7
 - pygsheets version : pygsheets==1.1.4
 - pygsheets installed from (github or pypi): pygs

**Comment by rbarakjsonar** [comment]
Note that if I break the creation of the spreadsheet into two steps, I see no issues.

Namely, I first run the script so only snapshot_worksheet_creation is run:
379     """
380     ec2_instance_worksheet_creation(spread_sheet, regions)
381     """
382     snapshot_worksheet_creation(spread_sheet, regions)
383     """
384     volume_worksheet_creation(spread_sheet, regions)
385     s3_worksheet_creation(spread_sheet, regions)
386     rds_worksheet_creation(spread_sheet, regions)
387     ami_worksheet_creation(spread_sheet, regions)
388     """           

And then I run all the rest  *_worksheet_creation functions (volume_worksheet_creation(), s3_worksheet_creation(), rds_worksheet_creation(), ami_worksheet_creation(), ec2_instance_worksheet_creation()).

**Comment by rbarakjsonar** [comment]
The issue is probably the following:
```
This version of the Google Sheets API has a limit of 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user. Limits for reads and writes are tracked separately. There is no daily usage limit.

To view or change usage limits for your project, or to request an increase to your quota, do the following:

If you don't already have a billing account for your project, then create one.
Visit the Enabled APIs page of the API library in the API Console, and select an API from the list.
To view and change quota-related settings, select Quotas. To view usage statistics, select Usage.
```

However, all I changed was just adding empty columns to the sheets I create, so seems to me that no extra calls to the Google API should be made. Am I wrong?

Is there a way to merge calles to the Google API so I wong reach the limit?

**Comment by Kordishal** [comment]
When updating pygsheets to 2.x the package will ensure this limit will not be crossed. Otherwise you will have to look into the code and see how often API calls are made.

**Comment by nithinmurali** [comment]
Closing as no changes needed.
