### ISSUE TITLE
There is a typing error in get_as_df(), index_colum -> index_column

### ISSUE THREAD

**Issue by Lahongkkito** [nithinmurali/pygsheets#354]
Hi, I'm a beginner of python, M.J from South Korea. 
When I using pyg, I found a misspelt word in get_as_df function. 
I think "index_colum" should be "index_column".
It isn't a big problem, if someone who uses this parameter with declaratively, it could 
take some confusion.
Thank you :)

**Comment by nithinmurali** [comment]
Discussion shifted into PR.
