### ISSUE TITLE
Key error when updating cell color and FG color set on text 

### ISSUE THREAD

**Issue by ddow** [nithinmurali/pygsheets#358]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
It appears under certain conditions, if you have set a FG text color that a key error results when you try to set the cell color.

**To Reproduce**
Steps to reproduce the behavior: foregroundColor is set in textFormat:

`<class 'dict'>: {'red': 0.26666668, 'green': 0.32941177, 'blue': 0.41568628}`

Relevant code is in cell.py
`if self.text_format is not None:
     ret_json["userEnteredFormat"]["textFormat"] = self.text_format
     fg = ret_json["userEnteredFormat"]["textFormat"].get('foregroundColor', None)
         if fg:
             ret_json["userEnteredFormat"]["textFormat"]['foregroundColor'] = {"red": fg[0], "green": fg[1],
                                                                                  "blue": fg[2], "alpha": fg[3]}`

This code tries to grab values like from a list from the fg object. However, the fg object is a dict:

`<class 'dict'>: {'red': 0.26666668, 'green': 0.32941177, 'blue': 0.41568628}`

Also, there are only three values and the code above is looking for an alpha value where there is none.

**System Information**
 - OS: OS X 10.14.5
 - pygsheets version : 2.0.1
 - pygsheets installed from (github or pypi): Pypi

**Comment by ddow** [comment]
Steps to reproduce the above. Open a sheet. Set a cell's text formatting to "bold." Then try to do:
`cell.color = (1,1,1,0)`
 This seems to break it every time.

**Comment by ddow** [comment]
Also breaks if you set text formatting on a cell to "italics."

**Comment by ddow** [comment]
After testing for a while, it appears any kind of text formatting breaks that code in cell.py at line 475.

**Comment by ddow** [comment]
There are two problems. It appears that the code is expecting a list when it gets a dict. It also expects values for all four of RGB and Alpha but it may only get some of them. For example, when I set the text color to green the only thing that came back in that fg dict was {"green": 1.0}.

**Comment by ddow** [comment]
Fix:
`        if self.text_format is not None:
            ret_json["userEnteredFormat"]["textFormat"] = self.text_format
            fg = ret_json["userEnteredFormat"]["textFormat"].get('foregroundColor', None)
            if fg:
                keys = ["red", "green", "blue", "alpha"]
                ret_json["userEnteredFormat"]["textFormat"]['foregroundColor'] = {key: fg[key] for key in keys if key in fg}`

**Comment by nithinmurali** [comment]
Hey, Thanks for reporting this. But this is already fixed in the trunk. So the fix should be out by next release.
