### ISSUE TITLE
Search by Column

### ISSUE THREAD

**Issue by pantuts** [nithinmurali/pygsheets#359]
Can't find the api that will allow me to search by column. Is there a current implementation on this or a plan for this kind of searching? Thanks.

**Comment by nithinmurali** [comment]
Currently there is only option to search whole sheet. By "search by column" you mean restricting search to a column rt?

**Comment by pantuts** [comment]
Okay got it. I wanted to search for example Cols: A, B, C, I wanted to search data only from the records within column C. Will it be in the roadmap?

**Comment by nithinmurali** [comment]
This should be small feature addition. Will add to 2.0.2 roadmap .
