### ISSUE TITLE
IOError Raised Without Filename in Client.py

### ISSUE THREAD

**Issue by e-beach** [nithinmurali/pygsheets#36]
In [client.py](https://github.com/nithinmurali/pygsheets/blob/e383c391a12a3b78355a6a837f6510713a8f5e9b/pygsheets/client.py#L424-L426), lines 426 and 452, the IOError should not be raised with a single argument. According to the [docs](https://docs.python.org/2/library/exceptions.html#exceptions.EnvironmentError), raising the error with only one argument makes the `e.filename` attribute be `None`. If you concur, I can fix this.

**Comment by nithinmurali** [comment]
Yea, sure.
