### ISSUE TITLE
Service Account Request Limit Uncatchable

### ISSUE THREAD

**Issue by samamorgan** [nithinmurali/pygsheets#362]
As of version 2, HttpError thrown by the Google API Client are caught by the Sheets wrapper object and handled with a timeout. In my opinion, this is poor behavior.

I'd prefer that this error be passed up so it can be caught and handled by the executor. This would allow me to, for example, fail over to a different credential when a request limit is hit.

**Comment by samamorgan** [comment]
Another thought: How about a flat that allows you to either have the library handle a timeout, or throw an exception, similar to how `subprocess.run(check=True) works?`

**Comment by nithinmurali** [comment]
The check looks better, it would be non-breaking change.
