### ISSUE TITLE
get_as_df() results in index errors

### ISSUE THREAD

**Issue by rchardb** [nithinmurali/pygsheets#365]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
loading pandas dataframe from gsheets using pygsheets results in an error when processing the dataframe, the issue does not occur with an export of gsheets to csv and load nor does it occur if the dataframe generated from get_as_df() is written to csv and then reloaded.

In either case, visually the dataframe appears identical.

**To Reproduce**

code here ...
normalMaster = matrix_pricing.worksheet_by_title('Regular')
matrix_df = normalMaster.get_as_df()
matrix_df.set_index(['Rarity','Price'], inplace=True)

 results in 
KeyError: (0, 'occurred at index 1')

loading from csv exported directly from gsheets or using pygsheets to load dataframe from gsheets, saving and reloading works around the error:

normalMaster = matrix_pricing.worksheet_by_title('Regular')
matrix_df = normalMaster.get_as_df()
matrix_df.to_csv('temp.csv',index=False)
matrix_df = pd.read_csv('temp.csv')

**System Information**
 - OS: Windows 10
 - pygsheets version : 2.02
 - pygsheets installed from (github or pypi): pip

**Comment by nithinmurali** [comment]
I am unable to reproduce the error. the set_index is running without any error. It moust be some thing specific to your data. Can please add the code to set the some sample data and then reproduce the error.

**Comment by rchardb** [comment]
My apologies, I was unclear when the error occurs. It doesnt occur when set_index is executed, rather it occurs when that df later is referenced. I'll try to recreate using different data.
