### ISSUE TITLE
Text format alignment problem

### ISSUE THREAD

**Issue by mandy331** [nithinmurali/pygsheets#366]
**Is your feature request related to a problem? Please describe.**
I'm frustrated about text format problem. I want to change text format alignment to be in  center, but I have tried any times and failed. Is there any way to fix this problem? Thank you very much!

![image](https://user-images.githubusercontent.com/33720290/62832414-0fd4d700-bc60-11e9-9f56-50f5d704745d.png)

**Comment by nithinmurali** [comment]
you can use the [`horizontal_alignment`](https://pygsheets.readthedocs.io/en/latest/cell.html#pygsheets.Cell.horizontal_alignment) property to set alignemnt, options are LEFT, RIGHT, CENTER.

see more options in the docs/

**Comment by nithinmurali** [comment]
The options needs to be updated in the docs.

**Comment by mandy331** [comment]
I use horizontal_alignment, but it turns out another error. Is there another way to fix it?
Thank you!
![image](https://user-images.githubusercontent.com/33720290/62878942-adadcc00-bd5c-11e9-920e-54fd6ffb527a.png)

**Comment by nithinmurali** [comment]
Its not a function its a property. use it like this.
``` 
acell.horizontal_alignment = pygsheets.custom_types.HorizontalAlignment.CENTER
```

**Comment by mandy331** [comment]
It's okay now!! It works!!! Thank you!!!

**Comment by CharlyWargnier** [comment]
Hi Nithin,

I would want to do for a range of cells or whole rows, yet it doesn't seem to be working.

Thus, at present, I'm writing 1 line per cell, i.e.:

# get a range of cells for further transformation below
cA4 = wks.cell('A4')
cB4 = wks.cell('B4')
cC4 = wks.cell('C4')

#Horizontal alignment
cA4.horizontal_alignment = pygsheets.custom_types.HorizontalAlignment.CENTER
cB4.horizontal_alignment = pygsheets.custom_types.HorizontalAlignment.CENTER

#Bold related cells
cA4.text_format['bold'] = True # make the header bold
cA4.update()
cB4.text_format['bold'] = True # make the header bold
cB4.update()

There must be a faster way I believe?

Thanks,
Charly
