### ISSUE TITLE
Clear all values in DataRange

### ISSUE THREAD

**Issue by ddow** [nithinmurali/pygsheets#376]
Hello. What's the most efficient way to clear all values in a DataRange? I have this code:

`        error_range = self.gsheet.sheet.get_values(start, end, returnas="range")
        model_cell = pygsheets.Cell("A1")
        model_cell.color = self.gsheet.error_color(False)
        error_range.apply_format(model_cell)
        error_range.clear()
        `
But that doesn't work. I also tried:

`error_range.update_values("")`

But that also didn't work. Any help would be appreciated! :)

**Comment by nithinmurali** [comment]
Use this function to clear vlaues https://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.clear

**Comment by nithinmurali** [comment]
Or you can also use error_range.clear()
