### ISSUE TITLE
Doesn't work with Service Account

### ISSUE THREAD

**Issue by j2318** [nithinmurali/pygsheets#38]
I get credentials form Service Account:
`credentials = ServiceAccountCredentials.from_json_keyfile_name(key_file, scopes=scopes)`
but then when I use them:
`gc = pygsheets.authorize(credentials)`
I get this:

> Traceback (most recent call last):
>   File "/home/jacek/workspace/ibis2/branches/161204/py/tests/gsheet.py", line 29, in <module>
>     gc = pygsheets.authorize(credentials)
>   File "build/bdist.linux-x86_64/egg/pygsheets/client.py", line 492, in authorize
>   File "build/bdist.linux-x86_64/egg/pygsheets/client.py", line 434, in get_outh_credentials
>   File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 407, in get
>     return self.locked_get()
>   File "/usr/local/lib/python2.7/dist-packages/oauth2client/file.py", line 45, in locked_get
>     _helpers.validate_file(self._filename)
>   File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 250, in validate_file
>     if os.path.islink(filename):
>   File "/usr/lib/python2.7/posixpath.py", line 135, in islink
>     st = os.lstat(path)
> TypeError: coercing to Unicode: need string or buffer, ServiceAccountCredentials found

Any ideas? way around.
-- jacek

**Comment by nithinmurali** [comment]
@j2318   `authorize` will directly take the secret file as an argument, you don't need to create credentials (It will also work though).As for your error ,the first argument is not credentials object but the oauth client secret file. Please take a look at the [docs](http://pygsheets.readthedocs.io/en/latest/reference.html#pygsheets.authorize).

what you can do:
`gc = pygsheets.authorize(service_file=key_file)`
or 
`credentials = ServiceAccountCredentials.from_json_keyfile_name(key_file, scopes=scopes)`
`gc = pygsheets.authorize(credentials=credentials)`
