### ISSUE TITLE
Deploying in google cloud functions

### ISSUE THREAD

**Issue by mtzirkel** [nithinmurali/pygsheets#385]
I am getting the following error when trying to set up a google cloud function. I am passing an oauth and from my understanding pygsheets is trying to store some temp authorization data on a read only "bucket". Any suggestions of how to work around this? Seems similar but not exactly the same as issue number [227](https://github.com/nithinmurali/pygsheets/issues/277)

Error message:
OSError: [Errno 30] Read-only file system: 'sheets.googleapis.com-python.json'

Thank you much in advance. This package has been wonderful to use for the past two years

**Comment by nithinmurali** [comment]
Once authenticated pyghsheets needs to save the credentials, else it will ask for login everytime. 

you can do the authorization in your local machine and then copy the generated file into the GC and then give the location using `credentials_directory` param in authorize.

you can do the authorization in your local machine and create a [Credentials object](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html) from its data, and pass it to authorize in `custom_credentials` .

**Comment by mtzirkel** [comment]
I remade the oauth client_secret ran my script locally and moved it into the cloud using th credentials_directory param in authorize.  The error message is below. It seems that the authorize.py is still trying to open the  sheets.googleapis.com-python.json file with 'w' permissions. I do not know how to create custom credentials if that would help. Thanks for the quick response. 


` textPayload: "Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 346, in run_http_function
    result = _function_handler.invoke_user_function(flask.request)
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function
    return call_user_function(request_or_event)
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 210, in call_user_function
    return self._user_function(request_or_event)
  File "/user_code/main.py", line 7, in update_sheets
    gc = pygsheets.authorize(credentials_directory='creds')
  File "/env/local/lib/python3.7/site-packages/pygsheets/authorization.py", line 133, in authorize
    credentials = _get_user_authentication_credentials(client_secret, scopes, credentials_directory, local)
  File "/env/local/lib/python3.7/site-packages/pygsheets/authorization.py", line 65, in _get_user_authentication_credentials
    with open(credentials_path, 'w') as file:
OSError: [Errno 30] Read-only file system: 'creds/sheets.googleapis.com-python.json' `

**Comment by nithinmurali** [comment]
It will try to open the file `sheets.googleapis.com-python.json' form the credentials directory you give. If you have the file there it should work.

**Comment by mtzirkel** [comment]
Cloud functions seems to be finding the file. When I give it the wrong folder it resorts to trying to find client_secret. It seems like in the authorization.py _get_user_authentication_credentials() will open the file with write privileges. It seems that this _get_user_authentication_credentials() is only called if there is not custom credentials or service_account. I am not the owner of this sheet so it looks like i need to create custom credentials.  I am still new to oauth what do i need to put in?

**Comment by nithinmurali** [comment]
I will change that to open file by read mode.

Basically you have to create [this](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html) object.  You can call the `from_authorized_user_info` or  class function to create that. you have to pass [these](https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/authorization.py#L57) info.

**Comment by andrewng88** [comment]
Hi @nithinmurali , thanks for the wonderful library.

I have authorized my machine locally and I have this file ( sheets.googleapis.com-python.json ) in my directory. 

some questions
1) how do I run this python script monthly ( is cron the easiest ? )
2) or is Google Cloud easier. Is there an instruction for this?

Thanks.

**Comment by nithinmurali** [comment]
For running periodically, cron will be the easier. If you want to run locally. But if your machine is not turned on at the required time, obviously it wont work. So in such cases google cloud will be a better option.

**Comment by case** [comment]
@andrewng88 you might try running it on Heroku or in a GitHub Action? I added Environment Variables support for credentials in this PR -- nithinmurali/pygsheets#345 -- so you can store the credentials in an env var/secret. Both Heroku and GH Actions support scheduled job runs.

**Comment by adityaunbxd** [comment]
@nithinmurali  I am facing this same issue, but it is not resolving. 
If I am keeping the authorized credentials object in the same directory, it is giving this error: 
 **line 64, in _get_user_authentication_credentials with open(credentials_path, 'w') as file: OSError: [Errno 30] Read-only file system: 'sheets.googleapis.com-python.json'**

but when I am not keeping it, it is resorting to read client_Secrets file, and then giving this error:
**line 51, in _get_user_authentication_credentials code = input('Enter the authorization code: ') EOFError: EOF when reading a line**

Please help. @mtzirkel  , I would appreciate if you can help if you had this resolved.

**Comment by nithinmurali** [comment]
@adityaunbxd did you try sending in a service account in service_account_env_var ? 

You can also try creating a custom [Credentials](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials) object like i mentioned.

```
 credentials_as_dict = {
        'token': "  # Set these values from your authorized  json credential object
        'refresh_token': "",
        'id_token': ""
        'token_uri': "",
        'client_id': "",
        'client_secret': "",
        'scopes': ('https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive')
    }

creds = Credentials(**credentials_as_dict)

gc = authorize(custom_credentials=creds)
```

Also i have added a fix to ignore errors in writing creds.
