### ISSUE TITLE
HttpError 400 when trying to write a note

### ISSUE THREAD

**Issue by nittolese** [nithinmurali/pygsheets#386]
Hey,
I'm trying to add a note with pygsheets but I'm getting this error:

```
HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1zuwtE8kKIGhkYiiBujja84mBdF6sP8WaEhyG1x7Le-4:batchUpdate?fields=%2A&alt=json returned "Invalid requests[0].repeatCell: No grid with id: 0">

```

Here is my code

```python
wks = sh[0]
f3 = wks.cell('F3') 

f3.value # I can see the value
f3.note # I can see the note if I add it manually on browser

#but trying to write a note on a cell I keep geeting HttpError
f3.note = 'test'

```

Any advice to overcome this issue?
Thank you!

**Comment by nittolese** [comment]
Hey @nithinmurali , have you tried to replicate this issue?

**Comment by nithinmurali** [comment]
Hi, @nittolese  I am traveling and will be back by next weekend. Will look into this once I am back.

What is the pygsheets version you are using? Is it installed from github master ?

**Comment by nittolese** [comment]
No problem, it was just for information.
I am using pygsheets==2.0.2 ( https://pypi.org/project/pygsheets/ ).

Thank you for support :)

**Comment by nittolese** [comment]
Hi @nithinmurali ,
any update on this bug?
Thank you!

**Comment by nithinmurali** [comment]
This is already fixed in the trunk.
