### ISSUE TITLE
template parameter in create() attribute not doing anything

### ISSUE THREAD

**Issue by you-say-that** [nithinmurali/pygsheets#387]
**Description**
When creating a new Googlesheet object, using the create attribute, the result is the same when an argument is passed to the template parameter as if there is no argument passed.

**To Reproduce**
Steps to reproduce the behavior (in Google Colab):
```python
from google.colab import auth
auth.authenticate_user()
from googleapiclient.discovery import build
sheets_service = build('sheets', 'v4')
drive_service = build('drive', 'v3')

#Install necessary packages into session
!pip install --upgrade --quiet pygsheets

sheet_template = (sheets_service.spreadsheets()
                    .get(spreadsheetId = 'somesheetid')
                    .execute())

sh = gc.create('Some Googlesheet',
                template = sheet_template))

#This produces a Googlesheet without fail, but with the formatting and content 
#from the template file not present
```

**System Information**
 - OS: Windows
 - pygsheets version : 2.0.2
 - pygsheets installed from pypi

**Comment by nithinmurali** [comment]
Why are you using the sheets_service? What is the type of `sheet_template ` ? Is that a dict?

**Comment by you-say-that** [comment]
Using sheets_service so that I can pass a sheet resource object as an argument to the template parameter, which as far as I'm aware is the only way to do it.  The type of sheet_template is indeed a dict

**Comment by nithinmurali** [comment]
It will also take a Spreadsheet object. Please check out [docs](https://pygsheets.readthedocs.io/en/latest/reference.html#pygsheets.client.Client.create). Passing dict should also work, but while i check what's the issue you can try passing an Spreadsheet object.

**Comment by nithinmurali** [comment]
Also Note that if you wish to get the resource object for any pygsheets model. Just call the `get_json` function on them.
