### ISSUE TITLE
Error when trying to grab cell value in a row greater than row 33 (or row index 34)

### ISSUE THREAD

**Issue by heathblandford** [nithinmurali/pygsheets#389]
**Describe the bug**
Connecting to and getting data from the gsheet works great, but I am unable to access any specific cell by coordinate in a row greater than row 33 (or row index of 34). 

looping through all 1000 rows of the sheet works fine. 

**To Reproduce**
```
wb = gc.open('My Spreadsheet')

sheet = wb[0]

print(sheet[34][2]) # this prints the cell value
print(sheet[35][2]) # error

# see error

Traceback (most recent call last):
  File "script.py", line 26, in <module>
    print(sheet[35][2]) 
  File "C:\Users\Heath\AppData\Local\Programs\Python\Python37\lib\site-packages\pygsheets\worksheet.py", line 1483, in __getitem__
    raise CellNotFound
pygsheets.exceptions.CellNotFound

```

**System Information**
 - OS: Windows
 - pygsheets version : 2.0.2
 - pygsheets installed from (github or pypi): pypi

**Comment by nithinmurali** [comment]
This issue is fixed in the trunk.
