### ISSUE TITLE
AttributeError when trying to rename a spreadsheet

### ISSUE THREAD

**Issue by karaluh** [nithinmurali/pygsheets#392]
When trying to rename a spreadsheet
`googleCloud.open_by_key(spreadsheetKey).title = 'test'`

I get
`AttributeError: can't set attribute`

I'm under the impression that this used to work. Did Google change something?

**System Information**
 - OS: Linux
 - pygsheets version : 2.0.2
 - pygsheets installed from (github or pypi): github

**Comment by jorijnsmit** [comment]
Does this answer your question? https://stackoverflow.com/a/42353453/1838257

**Comment by nithinmurali** [comment]
hmm, This looks unimplemented. Even I am surprised that this went unnoticed.
