### ISSUE TITLE
Verbose print out from pygsheets.Workshseet.find()

### ISSUE THREAD

**Issue by jayarerita** [nithinmurali/pygsheets#393]
When using the find() method in the pygsheets.Workhseet class it seems to print the entire worksheet to the terminal along with the list of resulting cells. 

I have managed to silence this action by commenting out the `print(found_cells)` found on line 1069 in the pygsheets.worksheet.py file.

I am not sure if others are experiencing this same behaviour.

**Comment by nithinmurali** [comment]
Hi, whats the version of pygsheets you are using? The print statements are removed from the trunk.

**Comment by jayarerita** [comment]
I am using version 2.0.2.  Thanks for checking it. I am unsure why my copy has the print statement.
