### ISSUE TITLE
Cant set horizontal alignment

### ISSUE THREAD

**Issue by mking275** [nithinmurali/pygsheets#394]
The docs seem to have a circular definition, that assumes the reader knows what legit values of "HorizontalAlignment" are... however; "Left", "LEFT", "Center", "CENTER" etc all raise exceptions.

Can anyone tell me what is actually meant by 'HorizontalAlignment' in the following code? An actual example of a valid value, instead of yet another circular definition would be greatly appreciated.

```
  def horizontal_alignment(self, value):
        if isinstance(value, HorizontalAlignment):
            self._horizontal_alignment = value
            self.update()
        else:
            raise InvalidArgumentValue('Use HorizontalAlignment for setting the horizontal alignment.')
```

**Comment by darren-mayne** [comment]
Experiencing the same

**Comment by nithinmurali** [comment]
HorizontalAlignment is the Enum defined [here](https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/custom_types.py#L86).

can be used as:
`cell.set_horizontal_alignment(pygsheets.custom_types.HorizontalAlignment.CENTER)
`

Will update the docs.
