### ISSUE TITLE
Can I disable or change log level from pygsheets

### ISSUE THREAD

**Issue by edwardinubuntu** [nithinmurali/pygsheets#396]
Can pygsheets turn off log level or not out print to the console?

I saw lots of cell info print from pygsheets:
'>, <Cell BH234 ''>, <Cell BI234 ''>, <Cell BJ234 ''>, <Cell BK234 ''>, <Cell BL234 ''>, <Cell BM234 ''>, <Cell BN234 ''>, <Cell BO234 ''>, 

It's quite hard for me to debug my project when using logging.debug, info or error. Thanks.

**Comment by nithinmurali** [comment]
this print is removed in latest release
