### ISSUE TITLE
Pandas 1.0 now issues a FutureWarning using .set_dataframe()

### ISSUE THREAD

**Issue by ldsalomone** [nithinmurali/pygsheets#397]
Getting the error below when using `.set_dataframe()`:

> c:\users\~\appdata\local\continuum\anaconda3\lib\site-packages\pygsheets\worksheet.py:1256: FutureWarning:
>
>The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

I think this line: `df = df.replace(pd.np.nan, nan)` is all that needs to be fixed. 

Happy to submit a PR myself to address if necessary.

**Comment by ldsalomone** [comment]
@nithinmurali I created a local branch from staging with a fix on it but can't push the branch to remote. Are there additional permissions I need?

**Comment by jorijnsmit** [comment]
@ldsalomone usual workflow is to fork the project, make changes there and submit a pull request from there.

**Comment by jorijnsmit** [comment]
Possibly related issue: I get the following error (besides the warning already mentioned) due to a column of the new pandas 1.0 dtype `Int64` containing `pd.NA`.

> <U1 cannot be converted to an IntegerDtype

**Comment by jorijnsmit** [comment]
Related PR: https://github.com/nithinmurali/pygsheets/pull/400

**Comment by ldsalomone** [comment]
> Possibly related issue: I get the following error (besides the warning already mentioned) due to a column of the new pandas 1.0 dtype `Int64` containing `pd.NA`.
> 
> > <U1 cannot be converted to an IntegerDtype
> 
> I believe the line
> https://github.com/nithinmurali/pygsheets/blob/62832278fbcb3f0075d013f6010230b107e89ab9/pygsheets/worksheet.py#L1303
> 
> 
> can be omitted completely, what purpose does it serve? `pd.np.nan` let's itself be cast to `'nan'` without problem; `pd.DataFrame([pd.np.nan]).astype('unicode')` works fine.

I think the point of the line is to replace np.nans with a user-defined value passed in as a kwarg. 
https://github.com/nithinmurali/pygsheets/blob/62832278fbcb3f0075d013f6010230b107e89ab9/pygsheets/worksheet.py#L1294-L1300

**Comment by jorijnsmit** [comment]
Ah yeah you're right! Guess I'll pass `nan=pd.np.nan` as a work-around for now then :-)
