### ISSUE TITLE
Is it possible to include Checkbox and Dropdown List?

### ISSUE THREAD

**Issue by tanlin2013** [nithinmurali/pygsheets#398]
Dear Developers,

I really like this library with well organized and intuitive conceptual models. They save me huge amounts of time without going through API!

As said in the title, I wonder it is also possible to include CheckBox, Dropdown List or even other features in Data -> Data validation -> Criteria (the dropdown option in sheet)? That will be greatly appreciate to many end users!

best,
tao

**Comment by tanlin2013** [comment]
Hi again, just wonder is there any updates for this? Thanks!

**Comment by nithinmurali** [comment]
@tanlin2013 it is implimented at [here](https://pygsheets.readthedocs.io/en/staging/worksheet.html#pygsheets.Worksheet.set_data_validation).

**Comment by tanlin2013** [comment]
thanks for the updates!
