### ISSUE TITLE
Is there a way to set 'seconds_per_quota' parameter 

### ISSUE THREAD

**Issue by yongks** [nithinmurali/pygsheets#401]
Hi there,

Great work on pygsheet, it is really useful to me.

I know that pygsheets keep track of the APi call internally and 'sleep' and retry when default quote of 100 read/write per 100s quota is reached. 

I had recently increased my sheet API quota. Is there a way to tell pygsheet to use the new quota parameter. I come to know about helper class "pygsheets.sheet.SheetAPIWrapper()" with parameter seconds_per_quota=100. 

Is there a way to make use of this ?

Thanks.

**Comment by nithinmurali** [comment]
The `SheetAPIWrapper` is used by the `Client`. So create your own `SheetAPIWrapper` object with the params required (here `seconds_per_quota`). and replace the `client.sheet` with your object.

**Comment by yongks** [comment]
Would like to ask: 
By default will pygsheets trigger the sleep and wait every 100seconds OR will it only trigger sleep/wait upon receiving error from Google. 

IF it is later, then I wouldn't be worried about the steps to create `SheetAPI Wrapper` and assign to my `client.sheet`.

**Comment by nithinmurali** [comment]
It only triggers on error.
