### ISSUE TITLE
Discussion: "Integer Indexes start from 1" changes with 2.0.3

### ISSUE THREAD

**Issue by yanissi** [nithinmurali/pygsheets#403]
Hello everyone,

I just wanted to have a conversation about a new feature that has been implemented in Pygsheets v2.0.3 .

I've been using Pygsheets religiously for the past year or so and have built numerous scripts that are dependent on this library.

When looking for libraries to update this morning, I noticed a 2.0.3 update to my 2.0.0 installation. Without looking at the changelog and just at the version number, it is fair to assume that this update would only be bug fixes and not a major disruption in the library's behaviour, right? Well, I was wrong.

It took me a while to figure that the problem was not coming from my code or from my spreadsheets but that the inherent way that Pygsheets counts rows and columns has been completely changed.

In Python, querying the content of a list starts with the number 0. Everything we count in programming starts with the number 0. But with 2.0.3, this whole concept has been thrown out of the window and it has been decided that "Integer Indexes start from 1" now.

I do not mean to complain about a change. I am coming here to discuss the decision and understand why this path has been chosen and also to understand the reasoning behind the version naming convention here. This change in the behaviour of the library is **massive** and **will break** any script that has been written with the 2.0.0 version of this library. Anyone that is querying rows and columns and extracting values using integers will be impacted by this update, effectively offsetting all results by 1.

Anyway, as I said, I would love to start the conversation and understand more about this choice. in the meantime, I will unfortunately not upgrade my library and stay with 2.0.0 as it looks like it's the latest stable version I can use with the plethora of scripts I've already written.

Thank you for your time,

Yaniss

**Comment by nithinmurali** [comment]
Hi @yanissi, sorry about this breaking change. Pygsheets always considers indexes to start with 1. This is in line with the api specs. All other function's start and end parameters consider row and column to start from 1. Even in the worksheet indexing you can see that the column number start from 1. So it was pretty odd that column start from 1 and row from 0. This was the reason for this planned chnage. 

This was planed for 2.1.0. And this release was meant to be 2.1 but later i could see some more planned issues for 2.1 which I didn't have time to complete. So this was chaged to 2.0.3 and this issue completely missed mind. Extremely sorry for breaking your stuff. I will make an hot release resetting this change. Also thank you for taking the time to start the discussion.

**Comment by nithinmurali** [comment]
fixed in hotfix 2.0.3.1
