### ISSUE TITLE
Filter Views

### ISSUE THREAD

**Issue by darren-martz** [nithinmurali/pygsheets#404]
How do I clear and create a filter view? The google api name for clearing is "clearBasicFilter" but I'm not sure how to make that call with pygsheets. There is also a call for "AddFilterViewRequest" to create a view. Can you provide some guidance on how to make those calls?

**Comment by nithinmurali** [comment]
This is not implemented by default but you can use the [custom_request](https://pygsheets.readthedocs.io/en/staging/spreadsheet.html#pygsheets.Spreadsheet.custom_request) function to make these calls.

First you would need to build the dict according to the the [api docs](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#addfilterviewrequest)

```
req = {
  "filter": { .... fill data here
  }
}

ss = gc.open('sheetname')
s.custom_request(req, "*")


```

**Comment by DgitalTrex** [comment]
@nithinmurali 
Is it really possible?

`googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1wt6s3pMQ0_VyDkfnstk1twJVaKuMY1QaWFewzZFnJ_k:batchUpdate?fields=%2A&alt=json returned "Invalid JSON payload received. Unknown name "filter" at 'requests[0]': Cannot find field.". Details: ...`

Payload:
`{'filter': {'filterViewId': 1, 'title': 'testfilter', 'range': {'sheetId': '1237843422', 'startRowIndex': 3, 'startColumnIndex': 1, 'endColumnIndex': 14, 'endRowIndex': '21'}}}`
