### ISSUE TITLE
import dataframe using set_dataframe, TypeError when column dtype: 'Int64' (with <NA> and integer)

### ISSUE THREAD

**Issue by keyapi** [nithinmurali/pygsheets#405]
In pandas dataframe, dtype of a column with NaN+integer would be changed into 'float', in cases of must-keep-integer, it's useful to replace dtype:'float' with dtype:'Int64', see: https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html

I use wks.set_dataframe(df, (1,1), nan="") to transfer a dataframe to a gsheet worksheet, but the pandas column with dtype:'float' (mixture of NaN and integer) could only be transfered as 'float' in a gsheet, but what i wanted for this column is only ""+integer, not float.

I also tried changing the dtype of the column first into 'Int64', e.g. df.column = df.column.astype('Int64') and then set_dataframe(), but got a "TypeError: <U1 cannot be converted to an IntegerDtype"

solution 1:
new parameter in set_dataframe() to import float as int

solution 2:
new parameter in set_dataframe() to deal with dytpe: "Int64",  take < <NA> > like a "NaN"

**Comment by nithinmurali** [comment]
Can you please provide a small example to reproduce this?

**Comment by keyapi** [comment]
# example snippet, set_dataframe with cloumn dtype: float and Int64

import numpy as np
import pandas as pd
import pygsheets

# pygsheets authorize and worksheet
gc = pygsheets.authorize(*********)
wks = gc.open_by_key('*********').sheet1

# 1.step: a dataframe with 2 columns
d = {'col1': [1, 2], 'col2': [3, np.nan]}
df = pd.DataFrame(d)
print(df.dtypes)
# col1      int64
# col2    float64

# df
# col1 | col2
# 1 | 3.0
# 2 |  NaN

wks.set_dataframe(df, (1,1), nan="")
# worksheet, 'col2' will keep float and "", "" is good, but 3.0 is not what i want
# col1 | col2
# 1 | 3.0
# 2 |  

# 2.step: make a copy and change dtype of 'col2' to 'Int64' (not int64)
df_Int64 = df.copy()
df_Int64['col2'] = df_Int64['col2'].astype('Int64')
print(df_Int64.dtypes)
# col1    int64
# col2    Int64

# df_Int64, 'col2' will keep integer 3 and NaN, both are what i want
# col1 | col2
# 1 | 3
# 2 | NaN

wks.set_dataframe(df_Int64, (1,1), nan="")
# TypeError: <U1 cannot be converted to an IntegerDtype

**Comment by jorijnsmit** [comment]
Workaround for this is to call `set_dataframe()` with `nan=np.nan`. It will replace the new pandas `<NA>` with `np.nan` which does let itself be cast.

**Comment by jorijnsmit** [comment]
Problem is that pandas v1.0.0 introduced a new dtype; Int64 (opposed to int64). This dtype allows for `<NA>` in an integer column whereas previously this was only possible with dtype object.

Calling `.fillna()` on this new dtype is what is causing said error; an `Int64` column cannot contain the `NaN` string that is provided by the kwargs by default. https://github.com/nithinmurali/pygsheets/blob/8a74911de68e18e66173115b22f095e2a518774a/pygsheets/worksheet.py#L1303

My suggestion would be to drop the `nan=` feature completely and let `.astype('unicode')` handle the casting.

If you want I can pick up this issue and submit a PR.

**Comment by keyapi** [comment]
> Workaround for this is to call `set_dataframe()` with `nan=pd.NA`. It will prevent to attempt to cast the `pd.NA` values to string.

do you mean  wks.set_dataframe(df_Int64, (1,1), nan=np.nan) ?
got no Error, but nan is not what i expected

col1 | col2
-- | --
1 | 3
2 | nan

**Comment by ldsalomone** [comment]
This isn't a problem within pygsheets, but instead a problem with pandas: https://github.com/pandas-dev/pandas/issues/25288 

A fix can be done by first filling with an int, then replacing that int with ''. 

```
d = {'col1': [1, 2], 'col2': [3, np.nan]}
df = pd.DataFrame(d)
print(df)

print(df.col2.dtype)
print(type(df.col2[0]))

df = df.fillna(99999999, downcast='infer')
print(df.col2.dtype)
print(type(df.col2[0]))

df.replace(99999999, '', inplace=True)
print(df.col2.dtype)
print(type(df.col2[0]))
print(df)
```

This is also a non-issue because the first version of the function worked (without the Int62 dtype) and once uploaded to google sheets, just tell google sheets to only display 0 decimal point for your whole table.

**Comment by jorijnsmit** [comment]
@keyapi are you still experiencing problems? Latest version should have it fixed.

**Comment by nithinmurali** [comment]
Fixed
