### ISSUE TITLE
Apply Format To Range on Specific Property Only

### ISSUE THREAD

**Issue by yongks** [nithinmurali/pygsheets#407]
I want to apply **only background color** and **text format** to a range. 

However, when I run the below commands, it overwrites destination border property of my destination range. Meaning my range original border are gone.

I know there is a "fields" parameter to appy_format(), but I had tried with 'userEnteredFormat', 'effectiveFormat', all doesn't help. 

```
        model_cell = pgs.Cell('A1')
        model_cell.set_text_format('bold', True)
        model_cell.color = 0.1
        row_range = new_wks.range('A3:E3',returnas='range')
        row_range.apply_format(model_cell, fields='effectiveFormat')
```

Any idea ? I'm currently using 2.0.2.

**Comment by nithinmurali** [comment]
border comes under userEnteredFormat. So you should use `userEnteredFormat/backgroundColor,userEnteredFormat/textFormat `

**Comment by yongks** [comment]
Thanks for the solution. This works beautifully.
