### ISSUE TITLE
SpreadsheetNotFound by Title, But It Exist !

### ISSUE THREAD

**Issue by yongks** [nithinmurali/pygsheets#408]
**Problem**

My code suddenly shows this error. While it complains spreadsheet "mns_calculator" is not found, it actually exist. My workaround is to save a copy of the spreadsheet and rename the duplicate "mns_calculator", while the original copy of the spreadsheet I rename it to "mns_calculator_backup".

Then it works after that. This is the 3rd time it happened within 2weeks and I applied the same workaround.  I have no way to reproduce this issue. Wonder if anyone experience the same.

```
 File "/usr/local/lib/python3.7/site-packages/pygsheets/client.py", line 120, in open
    raise SpreadsheetNotFound('Could not find a spreadsheet with title %s.' % title)
pygsheets.exceptions.SpreadsheetNotFound: Could not find a spreadsheet with title mns_calculator
```

my code ...
```
MNS_CALCULATOR   = 'mns_calculator' 
settings_df = gc.open(MNS_CALCULATOR) \
                    .worksheet_by_title(MNS_CALCULATOR_SETTINGS) \
                    .get_as_df()
```
**System Information**
 - OS: Windows 10, python 3.7
 - pygsheets version :2.0.2

**Comment by nithinmurali** [comment]
This doesn't look like an pygsheets Issue.

Are you using team drives?

**Comment by yongks** [comment]
I'm just using a standard google account (not team drive). This happened again just now, my workaround is the same, duplicated the affected file and swap their names. 

I also managed to capture a little extra traceback, basically it seems pygsheets can't find the title hence index out of range error.

```
pygsheets.exceptions.SpreadsheetNotFound: Could not find a spreadsheet with title mns_calculator.
152.102.145.4 - - [12/Mar/2020 01:55:01] "POST /mns HTTP/1.1" 500 -
INFO:werkzeug:152.102.145.4 - - [12/Mar/2020 01:55:01] "POST /mns HTTP/1.1" 500 -
ERROR:webapp:Exception on /mns [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pygsheets/client.py", line 117, in open
    spreadsheet = list(filter(lambda x: x['name'] == title, self.drive.spreadsheet_metadata()))[0]
IndexError: list index out of range
```

**Comment by nithinmurali** [comment]
Cant any issues from looking at the code. when this happens, try 
```
gc.drive.list(q="mimeType='application/vnd.google-apps.spreadsheet'", fields="files(name, parents), nextPageToken, incompleteSearch")
```
check if your file is listed there. Also use the [api explorer](https://developers.google.com/drive/api/v3/reference/files/list?apix=true&apix_params=%7B%22pageSize%22%3A1000%2C%22q%22%3A%22mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%27%22%2C%22fields%22%3A%22files(id%2C%20name%2C%20parents)%2C%20nextPageToken%2C%20incompleteSearch%22%7D#try-it) and check if your file is listed there.

**Comment by ashwinramdas12** [comment]
Same thing is happening to me. I used the gc.drive.list command and it even lists the spreadsheet that I'm trying to access. yet when I try to open it, it says it's not found

**Comment by nithinmurali** [comment]
@aaronorosen  is it listed on `self.drive.spreadsheet_metadata()` .

**Comment by teemal** [comment]
I'm also running into this issue

>     api = pygsheets.authorize(service_account_env_var = 'SERVICE_ACCOUNT')
>     wb = api.open('COIC-dashboard')

This produces the WorksheetNotFound exception even though I am positive the worksheet exists under the same account as my Heroku login

**Comment by ashwinramdas12** [comment]
@nithinmurali Yes it is.

**Comment by nithinmurali** [comment]
@ashwinramdas12 below is the code for finding by title. If it is listed in spreadsheet_metadata() i see no reason for this to fail. can you try running this?

Is there some typo or case difference in your title and what you are searching.

```
spreadsheet = list(filter(lambda x: x['name'] == title, gc.drive.spreadsheet_metadata()))[0]
ssheet = gc.open_by_key(spreadsheet['id'])
```

**Comment by ashwinramdas12** [comment]
@nithinmurali that seems to work. Will use that as a backup if gc.open fails again, thanks!
