### ISSUE TITLE
How to use find? 

### ISSUE THREAD

**Issue by magomaev** [nithinmurali/pygsheets#41]
Hi

I don't understand, how to use find function. Can you explain? 

sh = gc.open("google_spr")
wks = sh.worksheet('title', 'inbox')
to_find = 'hello' 
wks.find(to_find) ???

**Comment by nithinmurali** [comment]
Hi, 
the find was not implimented earlier. Now it should be working after f460ffc92e30decb50d5ed0c310492627c9974d7 .
`wks.find(to_find)` will work.

Reopen the issue, if you couldn't get it to work.
