### ISSUE TITLE
Can't update cell's text color - once more

### ISSUE THREAD

**Issue by Zgredomir** [nithinmurali/pygsheets#418]
I read issue #158 but this solution doesn't work.

After dumping cell to .json file I found a working one:

```python
text_color = {'red': 1, 'green': 0, 'blue': 0}
cell.text_format["foregroundColorStyle"] = {"rgbColor": text_color}
cell.update()
```

**Comment by davejroth** [comment]
I was also having issues using: 
`white_color = {'red': 1, 'green': 1, 'blue': 1}
cell.set_text_format('foregroundColor', white_color)`

The code above worked for me

**Comment by nithinmurali** [comment]
@Zgredomir the solution specified by @davejroth should work. 'foregroundColorStyle' is a new feature in sheets api.
