### ISSUE TITLE
Can't install package on anaconda

### ISSUE THREAD

**Issue by stikkie91** [nithinmurali/pygsheets#419]
Hi, 

I tried to install pygsheets in anaconda, this, unfortunately, doesn't work. 

I add the following line in conda run:
conda install -c bjrn pygsheets

this gave me the following error:
```
(base) C:\conda install -c bjrn pygsheets
collectiong package metadate (current_repodata.json):done
solving environment: failed with initial frozenn solve. retrying with flexible solve.
solving enviroment: failed with repodata from current_repodata.json, will retry with next repodata source.
collecting package metadata (repodata.json): done
solving environment: failed with initial frozen solve. retrying with flexible solve
found conflicts! Looking for incompatible packages
this can take several minutes. Press CTR-C to abort
failed

UnstatisfiableError: The follwoing specifications were found to be incompatible with each oter:

Outpunt in format: requested package -> Available versions
```

How can i solve this? (Maybe a beginner's question? I've only just started programming)

Looking forward to your respons.

Jeroen

**Comment by jorijnsmit** [comment]
You have some pinned packages which are not compatible with `pygsheets`.

A quick solution might be to create a new conda environment without any packages. Another option would be to figure out which packages are clashing.
