### ISSUE TITLE
Retrying of POST.

### ISSUE THREAD

**Issue by EricPreventa** [nithinmurali/pygsheets#422]
Using latest version of pygsheets on Google's Cloud Function. Keep running into this at the exact same spot.

Anything I can do to prevent it from happening?

Sleeping 0.41 seconds before retry 1 of 3 for request: POST https://sheets.googleapis.com/v4/spreadsheets/1fwdLSM2dbZO7KGCcNIgZSt_Cp--ohMjyL4guS6I-wRk:batchUpdate?fields=%2A&alt=json, after 429

It tries for 3 times, not sure if it's successful after the third or if it fails and moves on.

**Comment by nithinmurali** [comment]
retrying is because of connection error. Does some other api calls fail?

**Comment by EricPreventa** [comment]
> retrying is because of connection error. Does some other api calls fail?

I'm running this on Cloud Functions, so not sure why/if there is a connection error. It does end up working (from what I see), so not sure why it always has this warning at exactly the same place every time. 

Would increasing the time maybe help? How would i do so?

**Comment by nithinmurali** [comment]
Are you trying to write large amount of data ?

**Comment by EricPreventa** [comment]
> Are you trying to write large amount of data ?

I don't believe it is large amounts, I'm more so setting up the format of my Google Sheets layout. That may involve a good amount of different styling though (bold, italic, font size, etc)

The good news is it doesn't appear to be affecting my document, it's just troublesome seeing those messages, and making me wonder if there's anything I can do. Set a longer timeout or increase number of tries, just in case?

**Comment by nithinmurali** [comment]
you can try increasing the timeout. nothing i can think of from pygsheets side imho
