### ISSUE TITLE
'Worksheet' object has no attribute 'set_data_validation'

### ISSUE THREAD

**Issue by VlamV** [nithinmurali/pygsheets#424]
installed pygsheets, version 2.0.3.1
when executing the following command based on the Readme file
```
wks = gc.open("my_file").sheet1
wks.set_data_validation(start='F2', end='F2', condition_type='NUMBER_BETWEEN', condition_values=[2,10], strict=True, inputMessage="inut between 2 and 10")
```
I'm getting the following error:
`AttributeError: 'Worksheet' object has no attribute 'set_data_validation'
`
Is this a version issue?

**Comment by wy193777** [comment]
The library latest release on pypi is March 21st. But the function added 13 days ago according to [git blame](https://github.com/nithinmurali/pygsheets/blame/staging/pygsheets/worksheet.py#L1535).

My guess is the author accidentally uploaded document of an unreleased version.

**Comment by nithinmurali** [comment]
The `set_data_validation` is still in staging. I think the docs you are referring is of staging. You can install from staging branch to get that feature. 

```
pip install -no-cache-dir https://github.com/nithinmurali/pygsheets/archive/staging.zip
```
