### ISSUE TITLE
`Sheet.share` not working after Google sheets update

### ISSUE THREAD

**Issue by tsoernes** [nithinmurali/pygsheets#429]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
Google sheets recently updated their `share` popup menu. After that, `sht.share('', role='writer', type='anyone')` is not working anymore. It worked before google did their update.

**To Reproduce**
```
code here ...
# see error
```

**System Information**
 - OS: [e.g. iOS] Fedora 
 - pygsheets version : 2.0.3
 - pygsheets installed from (github or pypi): pypi

**Comment by katsuhisa91** [comment]
Hello. I am not reproducing this issue in my environment. Just an FYI.

Example of code execution
```
import pygsheets

gc = pygsheets.authorize(service_file='xxxxxxxxxxxxxxxxxxx.json')
sp = gc.create('sample')
sp.share('', role='writer', type='anyone')
```

System Information
- OS: macOS Catalina ver. 10.15.5
- pygsheets: 2.0.3.1
- pygsheets installed from (github or pypi): pypi

**Comment by tsoernes** [comment]
It was a bug in my own code not triggering the `sheet.share` code path.
