### ISSUE TITLE
Newby question...

### ISSUE THREAD

**Issue by Woutvan** [nithinmurali/pygsheets#431]
Hello,

I just started with Python and Pygsheets. I'm succesfully connected to Google Sheets and created a new worksheet.
In column A I have this:
A1: Test1
A2: Test2
A3: Test3

How can I query Google sheets to get ALL values that are in Column A? Now it has 3 values, but it could also have 10 for example. In other words: can Pygsheets see how many rows that are not emtpy and give me the results back?

I used this:
cell_list = wks.get_col(1)
print (cell_list)

But I get this back:
['Test1', 'Test2', 'Test3', '', '', '', '',.....................................]

Thanks and sorry for this beginner question...

**Comment by teemal** [comment]
this will eliminate trailing empty strings
`.get_col(1,  include_tailing_empty=False)`
