### ISSUE TITLE
foregroundColor(texts color) value error, version 2.0.3.1 

### ISSUE THREAD

**Issue by MrMiaoMIMI** [nithinmurali/pygsheets#432]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
get cell obj by get* function , set param returnas='cell',  then get cell's foregroundColor value by j.text_format.get('foregroundColor') error

**To Reproduce**
1、set cell 'A1'  foregroundColor(texts color) to red manually;
2、call  worksheet.get_values('A1', 'A1') get foregroundColor value，it return (1,1,1,1), expect (1,0,0,1)

code here ...
--- pygsheets/utils.py ---
def format_color(data, to='dict'):
    """
    change color format
    :param data: coloe data as dict or tuple
    :param to: 'dict' or 'tuple'
    """
    if not (type(data) is dict or type(data) is tuple):
        InvalidArgumentValue('data should be tuple or dict')

    if type(data) is tuple and to == 'dict':
        return {"red": data[0], "green": data[1], "blue": data[2], "alpha": data[3]}
    elif type(data) is dict and to == 'tuple':
            return data.get('red', 1), data.get('green', 1), data.get('blue', 1), data.get('alpha', 1)     # here，default value set 0？ ps：if set color to red ， data is {'red': 1}
    else:
        return data

**System Information**
 - OS: Mac
 - pygsheets version : 2.0.3.1 
 - pygsheets installed from (github or pypi): pypi

**Comment by nithinmurali** [comment]
this is the expected behavior. cells don't fetch all the properties (to reduce bandwidth). you need to call `cell.fetch()` . [doc](https://pygsheets.readthedocs.io/en/latest/cell.html#pygsheets.Cell.simple)
