### ISSUE TITLE
add `set_data_validations` to worksheet as batch function

### ISSUE THREAD

**Issue by fstinner** [nithinmurali/pygsheets#435]
**Is your feature request related to a problem? Please describe.**
I needed a function to set "DataValidationRules" as batch function

**Describe the solution you'd like**
add `set_data_validations` to worksheet as batch function with condition_values as nested list and also condition_type as nested list

Examples:

Example 1:
 ```
lst_values = [[[64, 68, 13]], [[15, 3, 54]]]
lst_types = [['ONE_OF_LIST'], ['ONE_OF_LIST']]
ws.set_data_validations(start='D3', end='D4', condition_values=lst_values, condition_type=lst_type, showCustomUi=True)
```

Example 2:
```
lst_values = [[[58, 48, 74], [5, 51, 20]]]
lst_types = [['ONE_OF_LIST', 'ONE_OF_LIST']]
ws.set_data_validations(start='D3', end='E3', condition_values=lst_values, condition_type=lst_type, showCustomUi=True)
```

Example 3:
```
lst_values = [[[58, 48, 74], [5, 51, 20]]]
condition_type = 'ONE_OF_LIST'
ws.set_data_validations(start='D3', end='E3', condition_values=lst_values, condition_type=condition_type, showCustomUi=True)
```

**Any other info**
the working function is in https://github.com/fstinner/pygsheets/blob/Add-set_data_validations-to-worksheet/pygsheets/worksheet.py

**Comment by nithinmurali** [comment]
added batch mode in 35d5f26  .   [doc](https://github.com/nithinmurali/pygsheets#batching-calls)
