### ISSUE TITLE
Virutalwrapper and/or dir struct causing client to fail?

### ISSUE THREAD

**Issue by dyburke** [nithinmurali/pygsheets#44]
Hello,

I'm trying to give this module a try and it looks as though it's looking for a `data_path` in the wrong place.

Here the client tries to construct a path:
`    def __init__(self, auth):
        self.auth = auth
        http = auth.authorize(httplib2.Http(cache="/tmp/.pygsheets_cache", timeout=10))
        data_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
`
Where is this path actually supposed to point?  I can't find a data file/folder anywhere that seems relevant.  This is causing pygsheets to not be able to locate `sheets_discovery.json`.

I have a feeling this is caused due to the use of `__file__`.

**Comment by nithinmurali** [comment]
@dyburke those data files are supposed to be installed during setup. can you please describe you environment? (python verson/os/virtual env/ipython)

**Comment by nithinmurali** [comment]
@dyburke If the error is not fixed , please reopen the issue

**Comment by dyburke** [comment]
This did fix the issue, thank you!  However, I'm having other issues (likely just my code); I'll create another bug if need be.

Thanks again!
