### ISSUE TITLE
Enable batch merge requests. 

### ISSUE THREAD

**Issue by David-Kane** [nithinmurali/pygsheets#440]
**Problem**
I have to run 100's of merge requests to achieve the desired aesthetic in Google Sheets. Specifically, to make a multi-column index readable by merging the upper layers which otherwise are shown as repeated values. Doing so is very slow. 

**Solution**
Ideally, I could pass a list or array of coordinates and have the merging all done in one request (I assume it is the multiple API requests that is slow).  

Thanks in advance.

**Comment by nithinmurali** [comment]
Fixed in  f4b6741

**Comment by nithinmurali** [comment]
also 35d5f26 .  [doc](https://github.com/nithinmurali/pygsheets#batching-calls)
