### ISSUE TITLE
"Updated" attribute not working

### ISSUE THREAD

**Issue by lukasbayern18** [nithinmurali/pygsheets#453]
When I try to use the attribute ".updated" on a given sheet that I have access to, the library returns a 404 error. I can import the sheet's contents as a dataframe, but do not have the ability to see an updated timestamp. Apologies if I'm misusing this attribute unintentionally!

**To Reproduce**
This code fails for me:
```python
import pygsheets
import pandas as pd

gc = pygsheets.authorize(service_file='client_secret_service.json')
ids = gc.spreadsheet_ids()
# print the sheet i'm interested in as a df
print(gc.open_by_key(ids[0]).sheet1.get_as_df())
# attempt to get the updated timestamp of this sheet
gc.open_by_key(ids[0]).updated
```

This code fails with error:
HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1cbGys017c0YsiOLnwnr_9EzY3Hg_qmZeGNFHgc6rogA?fields=modifiedTime&alt=json returned "File not found: 1cbGys017c0YsiOLnwnr_9EzY3Hg_qmZeGNFHgc6rogA.>

**System Information**
 - OS: Mac OS 11.0.1
 - pygsheets version: 2.0.3.1
 - pygsheets installed from: pypi

**Comment by nithinmurali** [comment]
This seems to be working when tested with oauth authentication.  might be cause you are using `service_file`. needs investigation.

**Comment by nithinmurali** [comment]
tested with both authentications. seems to be working.  

Is there any other speciality to your gmail account?
when you open the sheet in drive, is `1cbGys017c0YsiOLnwnr_9EzY3Hg_qmZeGNFHgc6rogA` the id displayed in address-bar ?

**Comment by lukasbayern18** [comment]
It does seem to be the same address -- perhaps because it's on a shared drive? That's the only special thing that I can think of, otherwise I think it's a normal file.

**Comment by nithinmurali** [comment]
can you try reproducing this with your normal gmail account? (private drive)

**Comment by lukasbayern18** [comment]
I'm only using my normal gmail account to access these files, but I've spent a bunch of time trying now with Google's API as well (so not pygsheets) and receive the same 404 error, so I do not believe that it is an issue with pygsheets. Thanks for your help, and apologies for taking up some of your time!
