### ISSUE TITLE
Reading and writing pandas dataframe

### ISSUE THREAD

**Issue by AnupamSaraph** [nithinmurali/pygsheets#457]

**Comment by nithinmurali** [comment]
Hi yes https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/worksheet.py#L1308

**Comment by AnupamSaraph** [comment]
Thanks for your quick reply. Can you point me to a few examples using this
with pandas?


Thank you!

**Comment by nithinmurali** [comment]
you can see the docs here. all supported params are documented there. There are no more exampes documented other than the ones in readme. you might find some in other blogs. like this [one](https://medium.com/game-of-data/play-with-google-spreadsheets-with-python-301dd4ee36eb).
 Lemme know if you need any specific examples. I can add it to the docs.
