### ISSUE TITLE
Worksheet.insert_rows() can't insert new rows to a single-row sheet

### ISSUE THREAD

**Issue by miken** [nithinmurali/pygsheets#46]
I discovered this issue while writing an app that automates the creation of a new worksheet report in Google Sheets for my company.

How to replicate:

I use a [public spreadsheet](https://docs.google.com/spreadsheets/d/1NrB3gwsvF-zQFVS5ADVaJY8OUGYwhGSue3gd3CCOfl8/edit) to replicate this error. You can access it as follows:

```python
# Authorize gc with your own credentials
sh = gc.open_by_url('https://docs.google.com/spreadsheets/d/1NrB3gwsvF-zQFVS5ADVaJY8OUGYwhGSue3gd3CCOfl8/edit')
# Open worksheet titled `Single-row sheet`
ws = sh.worksheet_by_title('Single-row sheet')
# Insert two rows after row 1
ws.insert_rows(1, 2)
```
I get this error:
```
HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1NrB3gwsvF-zQFVS5ADVaJY8OUGYwhGSue3gd3CCOfl8:batchUpdate?alt=json returned "Invalid requests[0].insertDimension: range.startIndex must be less than the grid size (1) if inheritFromBefore is false.">
```
My guess is that you set inheritFromBefore to False. Is there a way for you to either set inheritFromBefore to True, or expose that parameter through `insert_rows()` method for users to decide? Thanks in advance.

**Comment by nithinmurali** [comment]
Hi, thanks the detailed description. I have exposed the `inheritFromBefore`, until its merged to the master please install pygsheets using from staging
`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip`

**Comment by miken** [comment]
Thank you!
