### ISSUE TITLE
How to get the position of the last row that has content ?

### ISSUE THREAD

**Issue by stephane-klein** [nithinmurali/pygsheets#460]
I look for pygsheets method like Google SpreadSheet [`getLastRow`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#getlastrow) method.

I found nothing about this feature in [Pygsheets Worksheet](https://pygsheets.readthedocs.io/en/latest/worksheet.html)

I think, I can write a patch to implement this feature, what do you think? (@nithinmurali )

**Comment by nithinmurali** [comment]
Hi, you are right. There is no direct method to achieve this currently.  A patch would be welcome. But do you have any specific method in mind which doesn't involve fetching all data? maybe there is some not-so-direct api we can use to achieve this in a light way.

**Comment by nithinmurali** [comment]
closing as no response. If you like to continue discussion on this, please reopen.
