### ISSUE TITLE
Create in folder look like broken by design

### ISSUE THREAD

**Issue by mambari** [nithinmurali/pygsheets#466]
Hi all,
First, thank you for this lib, it's cool and useful.
I have an issue when I create a spreadsheet in a folder (by id) like :
`sht2 = gc.create("new sheet", folder="adF345vfvcvby67ddfc")`

I have this error:
`....../python3.9/site-packages/pygsheets/client.py", line 101, in create
    old_folder=self.drive.spreadsheet_metadata(query="name = '" + title + "'")[0]['parents'][0],
KeyError: 'parents'`

In fact, create in folder is creating a spreadsheet in the root folder of Gdrive AND THEN moving it to the right folder.
But the move function needs to have the ID of the old folder (root folder here) by requesting the "parents" key of the spreadsheet and it doesn't exist for the root folder since it's None...

If you are a user like me then the best way to avoid the issue is to use the create function with no folder and then use the move function from Drive:
```
created_spreadsheet = gc.create("spreadsheet_name")
gc.drive.move_file(created_spreadsheet.id, old_folder=None, new_folder="1ERdqsdqsdklnsqlnbdqsk")
```

If you are a dev of this lib, can you put old_folder to None by default of the move function called inside create function
since the spreadsheet is automatically created in root (which has no parents).

Thank you,
I hope it helped someone.

**Comment by ebailin** [comment]
Thank you! This did help me. Also, for others like me who burned a long time on trying to decipher the root problem by studying the documentation: the documentation for create_folder is also wrong. In the docstring, it says "parent", but in the code, it says the param is "folder".
![image](https://user-images.githubusercontent.com/18040773/204060707-e8241c51-9e4d-43a0-b61b-410eccf6e933.png)
