### ISSUE TITLE
Batch formatting request

### ISSUE THREAD

**Issue by nlarusstone** [nithinmurali/pygsheets#473]
**Is your feature request related to a problem? Please describe.**
I really like the addition of the `update_values_batch` function. I now have a bottleneck in my code in trying to apply formatting to those cells. Here's what I'm doing:

```
for i in range(n):
  start, end = ....
  val_range = pygsheets.datarange.DataRange(start, end, sheet).unlink()
  val_range.apply_format(
      pygsheets.Cell('A1').set_number_format(
          format_type=pygsheets.FormatType.SCIENTIFIC,
          pattern='0.00E+00')
```

**Describe the solution you'd like**
One solution would be to add a `update_formatting_batch` function that takes in a list of DataRanges and does the batch update. Another solution would be to add the ability to update formatting to the `update_values_batch` function (though it looks like the underlying GSheets function doesn't support that).

**Any other info**
I read through https://github.com/nithinmurali/pygsheets/issues/347 as well but it doesn't solve my issue

**Comment by nithinmurali** [comment]
I think its best to add a helper function `update_formatting_batch` , which will take a list of ranges and a model cell. 

btw have you tried the new batching mode?  https://github.com/nithinmurali/pygsheets#batching-calls . This could greatly reduce the number of api calls if you are doing property-updates in a loop.

**Comment by nlarusstone** [comment]
Oooh I haven't tried batch mode yet, but I will and will get back to you!

**Comment by nlarusstone** [comment]
That was helpful -- definitely sped it up some, thanks!
