### ISSUE TITLE
conditional format doesn't work with 'foregroundColor'

### ISSUE THREAD

**Issue by mustafa89** [nithinmurali/pygsheets#474]
The conditional format library return and error when using `foregroundColor` to change text color.

```
wks.add_conditional_formatting('I1', 'I100', 'NUMBER_GREATER_THAN_EQ', {'foregroundColor':{'red': 1.0, 'green': 0, 'blue': 0}}, ['1'])
```
# see error
```
 'Invalid JSON payload received. Unknown name "foregroundColor" at \'requests[0].add_conditional_format_rule.rule.boolean_rule.format\': Cannot find field.'}]}]">

```

**System Information**
 - OS: Ubuntu 18.04
 - pygsheets version : 2.0.4
 - pygsheets installed from (github or pypi): pypi

I also have a secondary question. Is it possible to define end as the last filled cell in the column instead of specifying `I100`?

**Comment by nithinmurali** [comment]
from the docs, you can see that it should be 

`{'textFormat': {'foregroundColor':{'red': 1.0, 'green': 0, 'blue': 0}} }`

**Comment by nithinmurali** [comment]
as for your secondary question, sheets api doesn't give an option to get last filled cell. you need to fetch the column without tailing_empty and find its length.
