### ISSUE TITLE
'dict_items' object does not support indexing

### ISSUE THREAD

**Issue by randywreed** [nithinmurali/pygsheets#48]
In setting a value into a cell, I get the the error "TypeError: 'dict_items' object does not support index"
running python 3.4.2 I should note that the action completes properly, it merely crashes afterwards. Wrapping a try around the last line handles the error but doesn't seem like it should happen.

Here's the code that triggers the error.
`a1=wks.cell('A1')`
` a1.col=int(colrow[0])`
` a1.row=int(colrow[1])`
` newval=entities[0]['value']`
` a1.value=newval`

TrackBack:
`File "/home/pi/WatsonSyllabusBot/syllabusbot.py", line 423, in getAttendance
    a1.value=newval`
`  File "/usr/local/lib/python3.4/dist-packages/pygsheets/cell.py", line 88, in value
    self.fetch()`
`  File "/usr/local/lib/python3.4/dist-packages/pygsheets/cell.py", line 201, in fetch
    self._unformated_value = result['effectiveValue'].items()[0][1]`
`TypeError: 'dict_items' object does not support indexing`

**Comment by nithinmurali** [comment]
Hi, thanks for reporting this. Its fixed in staging, until its merged to the master please install pygsheets  from staging
`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip`
