### ISSUE TITLE
Pygsheets crashing when compiled as EXE

### ISSUE THREAD

**Issue by DgitalTrex** [nithinmurali/pygsheets#493]
**Describe the bug**
When compiling a python script that uses pygsheets, the executable always fails.
This bug has been previously reported on https://github.com/nithinmurali/pygsheets/issues/200 and https://github.com/nithinmurali/pygsheets/issues/341 but none really specifies what NEEDS to be done to make it work. I have a ton of client.py in my system and scattered inside the python base folder.

Should I be downloading which py and editing which py to include in which py?

**To Reproduce**
```
pyinstaller -F C:\Users\JohnDoe\PycharmProjects\SomeProject\main.py
from the console, run main.exe
# see error
[Errno 2] No such file or directory: 'C:\\Users\\.........\\pygsheets\\data\\sheets_discovery.json'
```

**System Information**
 - OS: Win 10
 - pygsheets version : 2.0.5
 - pygsheets installed from (github or pypi): pip

**Comment by nithinmurali** [comment]
can you please try installing the staging version and check if it's working? 

`pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip
`

**Comment by DgitalTrex** [comment]
@nithinmurali 

God bless you that worked. I had to uninstall the pygsheets first, then installed this staging version. THEN it worked!!! Thank you

**Comment by mlo31415** [comment]
I have the same problem. I uninstalled pygsheets 2.0.5, confirmed that it was gone, and then ran "pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip".  It reported "Successfully installed pygsheets-2.0.5
". I re-ran the EXE build, but I still can't run the EXE it produces.  (The program runs in the Pycharm IDE.) When I run it I get the messages:

Traceback (most recent call last):
  File "ProgramAnalyzer.py", line 6, in <module>
ModuleNotFoundError: No module named 'pygsheets'

I'd appreciate any help with this!

**Comment by nithinmurali** [comment]
@mlo31415 your issue is different from one mentioned here. i think in your case pygsheets is not installed in the env you are using.  dosent look like a pygsheets specific issue.

**Comment by mlo31415** [comment]
Using Pycharm, I see pygsheets 2.0.5 installed, and the program runs under the debugger only when it shown as installed. (I tested it before uninstalling, after uninstalling, and then after re-installing from Github.)   Is there some other test which would clarify things?

**Comment by DgitalTrex** [comment]
@mlo31415
you could have installed it on a virtual env. not the same env the
pyinstaller uses. definitely a different problem

**Comment by mlo31415** [comment]
Good catch! While I had all my packages installed in the venv, I was using a pyinstaller that was off in the Python38 directory.  I repointed my build.bat to the venv and it works.

Many thanks for your help!

**Comment by Jarige** [comment]
So I've experienced this exact problem today. It seems like the pip repositories still have the unfixed version of pygsheets. Is there any chance this fix will be rolled out so that I do not have to manually patch my venv?
