### ISSUE TITLE
setFormula for a pygsheet range

### ISSUE THREAD

**Issue by DgitalTrex** [nithinmurali/pygsheets#499]
When adding formulas to a range, I have to loop through the range and do a cell.formula = "=FORMULA". In GSheets API, there's already an implemented setformula for a range. 

Hoping that setFormula be added to pygsheets

**Comment by nithinmurali** [comment]
> In GSheets API, there's already an implemented setformula for a range.

hmm, can you please provide a link to the docs of the same?

**Comment by nithinmurali** [comment]
if you want to apply formulae, use the code below

```
# set a formula and extend it to more cells
cell = wks.cell('C1')
cell.value = '=A1+B1'
wks.apply_format('C1:C10', cell, 'userEnteredValue.formulaValue')

```

**Comment by rrfaria** [comment]
I did same thing and got an error:

When I use your example:

```python
cell = wks.cell('F2')
cell.value = '=B2+1'
wks.apply_format('F3:F300', cell, 'userEnteredValue.formulaValue')
```

```python
AttributeError: 'Worksheet' object has no attribute 'apply_format'
```

I also tried different
```python
cell = wks.cell('F2')
cell.formula = '=B2+1'
wks.get_values("F3","F300",returnas="range").apply_format(cell)
```

but got another error:
```python
AttributeError: 'str' object has no attribute 'get_json'
```
