### ISSUE TITLE
Requesting Enhancement : "get_all_records()"

### ISSUE THREAD

**Issue by jdsinh** [nithinmurali/pygsheets#5]
If "get_all_records" will be implemented it will be great. Actually get_all_values returns list of list.
And I need is dictionary of the data in key value pairs of headers and values.

**Comment by nithinmurali** [comment]
The get_all_values has a param names `returnas` set it to 'cell' and you will get a list of cells, which has headers in it. The get_all_recods function is supposed to format the values to corresponding datatypes rather than strings.

**Comment by jdsinh** [comment]
can't I get data in following format : 

     "1": {
            "Status": 1,
            "Sales": 50,
            "Month": "January"
        },
        "0": {
            "Status": 1,
            "Sales": 100,
            "Month": "January"
        },
        "3": {
            "Status": 1,
            "Sales": 200,
            "Month": "January"
        },


where keys "1","0" and "3" are row_ids
then every list has keys "Status", "Sales" and "Month" which are headers.
and all corresponding  values of that headers are its values.

**Comment by nithinmurali** [comment]
Isn't this easily obtainable from the output of  `get_all_values` as list of list. as the list is ordered, the first row will be header, and the corresponding values in other rows will be its values. If I am understanding correctly, the `header` is rather vaguely defined term, as a general sheet may not have a header.

**Comment by nithinmurali** [comment]
In that case we will have to consider first non empty row as header colum

**Comment by nithinmurali** [comment]
As the index of the row is rather redudent, it returns a list

**Comment by jdsinh** [comment]
Thanks a lot :)
