### ISSUE TITLE
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

### ISSUE THREAD

**Issue by pikku1** [nithinmurali/pygsheets#507]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

We are using pygsheets as module in our python scripts and its throwing the below error. Please help me on this.
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

**Comment by nithinmurali** [comment]
This doesn't look like an issue specific to pygsheets. Could you please give some more info like, which function call is throwing this error. and other conditions like, are you inside a vpn or if you are facing this issue in specific situations?

**Comment by pikku1** [comment]
Hey Nithin,

We are using Global Protect as VPN and after SSL decryption project, the user is getting error while running the python scripts,when he is using pygsheets as module in his scripts. If we enroll the user out of the decryption rule on firewall, he is able to run the scripts well without errors. As we need to enroll users under decryption project, we need to fix this issue as why the module is not happy getting decrypted.

**Comment by pikku1** [comment]
Hey Nithin,

Can you please look into this and help to resolve the issue.

**Comment by nithinmurali** [comment]
Hi @pikku1, 
Your error seems very specific to your use-case and it doesn't look like a library fix. 
But I have few suggestions, you can try fixing this by creating a custom client with custom http object to client. [here](github.com/nithinmurali/pygsheets/blob/staging/pygsheets/client.py#L45).

```
# try disabling ssl verification
import httplib2
 h = httplib2.Http(disable_ssl_certificate_validation=True)

# or you can try passing custom ca cert
h = httplib2.Http(ca_certs='./ca.crt')

```

**Comment by nithinmurali** [comment]
Also try to get the [sample code](https://developers.google.com/sheets/api/quickstart/python) from google sheets api docs to work. if so pygsheets should also work without any issues.

**Comment by pikku1** [comment]
Hey Nithin,

I am trying the above suggestion provided by you and would let you know how it works.
Thank you so much for looking into it.

**Comment by nithinmurali** [comment]
closing as this issue is unrelated to pygsheets code.
