### ISSUE TITLE
Find merged cells boundaries

### ISSUE THREAD

**Issue by megastruktur** [nithinmurali/pygsheets#508]
Hey there!

Is there any way to find merged cells Addresses in range? The core functionality of the sheet I want to parse is to identify merged ranges and parse them accordingly.
However **studying the docs** and experimenting I couldn't find a way to identify merged cells boundaries if they were merged via Sheets UI.

E.g. I have a range of cells ( A1: C3 ).
(B2 : B3) and (C2 : C3) are merged and some data is set there. How can I see whether these ranges are merged or not?

**Comment by nithinmurali** [comment]
Hi, i have it deployed in staging. please check `wks.merged_ranges`.
