### ISSUE TITLE
Client auth caching assumes access to /tmp/ which breaks App Engine compatibility

### ISSUE THREAD

**Issue by hellofornow** [nithinmurali/pygsheets#52]
https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/client.py#L53

Unless you are using the new "flexible" environment this breaks app engine compatibility.
Perhaps let cache folder be configurable -- not sure if anyone else has run into this issue.

**Comment by nithinmurali** [comment]
I have exposed http client, so you could create a client object with custom http client. You wont be able to use the `authorize` though. You can use the `get_outh_credentials` if you need to get the oauth credentials object.
