### ISSUE TITLE
Cant provide axis while creating a chart

### ISSUE THREAD

**Issue by aadhikar** [nithinmurali/pygsheets#529]
Hi folks, 
I am trying to create a chart in which I can specify the x-axis, so far I got: ```wks.add_chart(('G1', 'G1'), [('B2','B4'), ('C2','C4'), ('D2','D4'), ('E2','E4')], 'TestChart', ChartType.LINE)``` Is there any way I can do that?

**Comment by nithinmurali** [comment]
Hi, The domain is the x-axis (the first param). But here you have given both as G1, so its essentialy one point. suppose you want your x values from G1 to G10, then pass the first param as ('G1', 'G10').

I have updated the docs.

**Comment by aadhikar** [comment]
Thanks for your valuable comments!
