### ISSUE TITLE
Using set_dataframe - HttpError 400

### ISSUE THREAD

**Issue by zilnhoj** [nithinmurali/pygsheets#53]
I'm trying to set a pandas dataframe directly into a sheet and I'm getting the error 
<HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/sheetidremoved forthisrequest/values/billing_data%21B1%3AT105?valueInputOption=USER_ENTERED&alt=json returned "Invalid values[0][0]: list_value {
  values {
    string_value: "Timestamp"
  }
  values {
    string_value: ""
  }
}">

I've set the Timestamp to a str and set all nan's to 0

I'm using wks.set_dataframe(df,(1,2),copy_head=True, fit=True)

If I don't convert the 'Timestamp' to string I get "TypeError: Timestamp('2017-02-12 00:00:00') is not JSON serializable" error

Can you please let me know why this is happening?

Thanks

**Comment by nithinmurali** [comment]
can you please show the DataFrame you are using ?

**Comment by zilnhoj** [comment]
It is a multi index pivot_table dataframe [the shape I needed] except for a date column - but when I flattened it I was able to get the data into the google sheet

it also baulked at NaN's which was ok as I just fillna'd it and it as fine

**Comment by nithinmurali** [comment]
So, if the issue is solved please close the issue.

**Comment by zilnhoj** [comment]
Will do

**Comment by raubtaube** [comment]
I have a quick test for that behavior. It seems like multindex is not supported properly.

```
import pandas as pd
import numpy as np
import pygsheets as ps

arrays = [np.array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux']),
          np.array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'])]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
#df = pd.DataFrame(np.random.randn(8, 4), index=arrays)
df = pd.DataFrame(np.random.randn(8, 8), index=index, columns=index)
wks.set_dataframe(df,'A1',copy_index=True) # todo bug report multiindex
Will raise an error: 
HttpError: <HttpError 400 when requesting 

```
