### ISSUE TITLE
Which python versions are supported?

### ISSUE THREAD

**Issue by pedrorojasg** [nithinmurali/pygsheets#553]
Hello all,
Will be nice to add this info to the repo.

Apparently version 2.0.5 is working nice with Python 3.6

**Comment by nithinmurali** [comment]
We test with python 3.6 to 3.9 https://github.com/nithinmurali/pygsheets/blob/staging/.travis.yml#L3-L6

**Comment by pedrorojasg** [comment]
Thanks a lot!
