### ISSUE TITLE
Update docs to latest staging commit

### ISSUE THREAD

**Issue by pedrorojasg** [nithinmurali/pygsheets#559]
**Describe the bug**
The documents of pygsheets doesn't have last improvements of staging branch.
Apparently the docs is using this build from 2021:
https://github.com/nithinmurali/pygsheets/blob/fa227b8c25ff78bee3c586bf546c06b78e5ccd85

**Expected result**
Will be nice to have the last version of the docs in ht docs.

**Comment by nithinmurali** [comment]
Fixed with release of new version.
