### ISSUE TITLE
client.py, line 124, attempt to take index on dict

### ISSUE THREAD

**Issue by exactstat** [nithinmurali/pygsheets#562]
Module: client.py  
Method: create  
Code:  
```
        if folder:
            self.drive.move_file(result['spreadsheetId'],
                                 old_folder=self.drive.spreadsheet_metadata(fid=result['spreadsheetId'])[0].get('parents', [None])[0],
                                 new_folder=folder)
```  
self.drive.spreadsheet_metadata(fid=result['spreadsheetId']) - returns a dict, not a list.

**Comment by colwynlegitscript** [comment]
I put up a draft PR here with the changes that worked for me: https://github.com/nithinmurali/pygsheets/pull/571. That said, I'm not sure if there are more corner cases that need to be caught.
