### ISSUE TITLE
How to set hyperlink?

### ISSUE THREAD

**Issue by purgenetik** [nithinmurali/pygsheets#569]
Hello!

Thanks for the module - fantastic work! The question is - how to insert a hyperlink into a cell (Cntrl-K option in Google Spreadsheets)? Is there such a functionality. or is it somehow possible to insert it in the form of a formula? Didn't understand how to do it?

Good luck!

**Comment by nithinmurali** [comment]
Hi you can use this formula  `=HYPERLINK("https://www.google.com", "my_link")`
