### ISSUE TITLE
Clear all rows in sheet except for the first

### ISSUE THREAD

**Issue by dovy** [nithinmurali/pygsheets#58]
It would be really useful to be able to clear a sheet rather than have to delete and recreate it. Ideally I'd love to have a helper function that would auto-delete all except the first row.

I suppose I could select all of the rows, and then iterate and update manually, but I see that as painful.

Thoughts?

**Comment by nithinmurali** [comment]
You can clear a sheet using `clear` [function](https://pygsheets.readthedocs.io/en/latest/worksheet.html#pygsheets.Worksheet.clear) in worksheets.

**Comment by nithinmurali** [comment]
However only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept. So were you were referring to clearing the formatting ?

**Comment by dovy** [comment]
Fantastic. You're library is perfect. Thank you.
