### ISSUE TITLE
[feature request] easy ways to append columns

### ISSUE THREAD

**Issue by fvisin** [nithinmurali/pygsheets#59]
An `append_rows` method exists, but a corresponding  `append_cols` does not. I think it would be a great addition to the framework. 

Similarly, it would be nice if `update_cells` could automatically add columns and rows to the workspace if needed.

**Comment by nithinmurali** [comment]
The `append_rows` is changes to `append_table` with dimension specification.

Yes, It would be a nice feature indeed. I think an `extend` param to `update_cells` which will extend the sheet if necessary should do.

**Comment by fvisin** [comment]
> The append_rows is changes to append_table with dimension specification.

Great, thanks for fixing it immediately!!

> Yes, It would be a nice feature indeed. I think an `extend` param to `update_cells` which will extend the sheet if necessary should do.

Yes indeed. I agree an `extend` boolean param is the best interface for this.
