### ISSUE TITLE
wks.range function doesn't work

### ISSUE THREAD

**Issue by jason79** [nithinmurali/pygsheets#61]
Traceback (most recent call last):
  File "C:\Users\jason\Google Drive\python\custom3.py       ", line 11, in <module>
    cell_list = wks.range('A1:C7')
  File "C:\Python27\lib\site-packages\pygsheets\worksheet.py", line 177, in range
    return self.get_values(startcell, endcell, returnas='cell')
  File "C:\Python27\lib\site-packages\pygsheets\worksheet.py", line 212, in get_values
    values = self.client.get_range(self.spreadsheet.id, self._get_range(start, end), majdim.upper())
  File "C:\Python27\lib\site-packages\pygsheets\client.py", line 308, in get_range
    result = self._execute_request(spreadsheet_id, request, False)
  File "C:\Python27\lib\site-packages\pygsheets\client.py", line 378, in _execute_request
    raise RequestError
RequestError

**Comment by nithinmurali** [comment]
`RequestError` is because of the network Timeout. If necessary you can increase the number of retries in the client by changing `client.retries`

**Comment by jason79** [comment]
I've changed the .retries = 5 and I get ... 

Cant connect, retrying ... 0
Cant connect, retrying ... 1
Cant connect, retrying ... 2
Cant connect, retrying ... 3

i can get the sheet fine with `.worksheet_by_title`,  so it is not a connection issue. Any more suggestions please?

**Comment by nithinmurali** [comment]
I am unable to reproduce this. So until the logging is implemented, I am afraid i cant get enough info to debug this. Else you can print the request error stacktrace form `_execute` function in client (by manually inserting a `print` there) and post it here.

**Comment by jason79** [comment]
i don't know how to do that. I'm going to use the api directly, and will
check back on your project at a later version. thanks for trying.

**Comment by nithinmurali** [comment]
That's alright, While using the api directly , if you are able to successfully get values using the endpoint `spreadsheets().values().get()` , please post here.

**Comment by jason79** [comment]
what do you want me to post?

i'm using this statement and it works

`result = self.service.spreadsheets().values().get(spreadsheetId=key,
range=range).execute()`

**Comment by nithinmurali** [comment]
Thanks, I just wanted to know, if its working when you are calling the api directly.

**Comment by jason79** [comment]
And by the way... I write speed is insanely fast. It's so much faster than
gspread. Haven't tried pygsheets. It seems like it just writes and moves
on. Do you know why it is so much faster?

**Comment by nithinmurali** [comment]
well, I think its just because of the new api v4.
