### ISSUE TITLE
Keep Signon Token Longer

### ISSUE THREAD

**Issue by pkkid** [nithinmurali/pygsheets#63]
After developing my script for a bit, walking away to get lunch and then returning, my script needed to re-authenticate. This happened again this afternoon as well.  Is there a way to keep the token valid forever?

Please close this if I am just missing how this can be done.

**Comment by nithinmurali** [comment]
Hi, can you specify exactly what Exception it is throwing? a stack-trace would be useful. I think i refresh token is getting expired.

**Comment by pkkid** [comment]
There was no stacktrace, it was just popping up the Google Auth step in the browser every few hours. Anyway, I ran my script again this morning and it didn't do that.. so I have no clue why it needed to re-authenticate again before.  I'll reopen if it happens again with more information.

**Comment by pkkid** [comment]
I figured out what's going on here.  Each time I would run my script from a different directory it wouldn't be able to find the json file with tokens and need to re-auth. I was able to code around this by hard coding the json filepath after first run.

**Comment by nithinmurali** [comment]
Hi, for that if you set the `outh_creds_store`  of `authorize()` as `global`. The json file with tockens will be saved in a global directory (to be specific, on your home).

**Comment by pkkid** [comment]
Perfect thanks! Sorry I missed that before.
