### ISSUE TITLE
get content of 2 rows

### ISSUE THREAD

**Issue by petrk94** [nithinmurali/pygsheets#67]
Hello,

I have tried the examples and have made the API working, and its pretty impressive^^ (great job :) )
But I would like to get the content of 2 rows and save it in a variable, to save it in a file, which I proceed with a other program.
Is this possible and if yes, how I can get the content?

**Comment by nithinmurali** [comment]
For getting 2 rows, you could use `get_row` for each row or you could use `get_values` if they are consecutive rows.
