### ISSUE TITLE
Insufficient tokens for quota 'ReadGroup'

### ISSUE THREAD

**Issue by j2318** [nithinmurali/pygsheets#78]
Hi,
Can you shed some light on this error:
Error: <class 'googleapiclient.errors.HttpError'> <HttpError 429 when requesting https://sheets.googleapis.com/v4/spreadsheets/1YSo5QBlo6eagKruQIVCGmg-0q9emCKp3e892sR1o430/values/Case%20Units%21B1%3AB16?valueRenderOption=FORMATTED_VALUE&alt=json&majorDimension=COLUMNS returned "Insufficient tokens for quota 'ReadGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:247898894239'.">
Is there way to increse this limit?
-- jacek

**Comment by nithinmurali** [comment]
I am not sure which quota you are exceeding. Either way in the [Api quota page ](https://console.developers.google.com/apis/api/sheets.googleapis.com/quotas) there is an option `apply for higher quota`  you could try that.

**Comment by j2318** [comment]
It looks like the 100 requests per sec. I assume that one API pygsheets translates into one Google's API call, but I don't think I call your API 100 times a sec. Anyway I will run more tests a let you know.

⁣Jacek

**Comment by nithinmurali** [comment]
If you could you post your code or mention which functions you are calling, i could look into it.

**Comment by oreniko26** [comment]
I have the same problem only with the WriteGroup tokens. I'm trying to execute 178 update_cell() calls for 7  different sheets. Is it possible to somehow buffer those calls and burn less writing tokens? or does update_cell() have the ability to write multiple cell updates?

**Comment by nithinmurali** [comment]
Can you please share your code

**Comment by ghanshyam-schoolbook** [comment]
Hello,
I am getting following error
"`Google::Apis::RateLimitError: rateLimitExceeded: Insufficient tokens for quota 'WriteGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:864617607794`'."
Can anyone guide me how to resolve this issue

**Comment by nithinmurali** [comment]
You are making more than 100 requests per second, reduce it.
