### ISSUE TITLE
Does pygsheets Support Access to Spreadsheets on Team Drives?

### ISSUE THREAD

**Issue by casalemi** [nithinmurali/pygsheets#79]
I am trying to access a Spreadsheet on a Team Drive using gspread.  It is not working.  I was wondering if gsheets has the new capability available in Google Drive API v3 to open spreadsheets on Team Drives.  If so, how do I specify the fact I want to open a spreadsheet on a Google Team Drive and not my own Google drive? If not, when will that functionality be available? Thanks!

**Comment by nithinmurali** [comment]
Hi, 
No, currently there is no teamdrive support. But i have created a new branch [teamdriveSupport](https://github.com/nithinmurali/pygsheets/tree/teamdriveSupport) for adding support. I have made some changes to enable support. But i cant test them as i dont have a teamdrive access. So it would be great if you could test it. 

As far as i can see from the drive docs, if you have acess to a teamdrive you should be able to acess spreadsheets in them. As per my changes, once you create a pygsheets client, you should set the `enableTeamDriveSupport` and `teamDriveId` to open a sheet in a teamDrive.

**Comment by casalemi** [comment]
Hi Nithin,  Sounds good! Let me know where I can pick up the new package and I'll test it for you.

**Comment by nithinmurali** [comment]
You can either clone the repo and checkout the `teamdriveSupport` branch and test using the script in `test/manual_test.py`  or you can install the package by `pip install https://github.com/nithinmurali/pygsheets/archive/teamdriveSupport.zip` and test it.

**Comment by casalemi** [comment]
Nithin,

Does pygsheets work with Google Drive or Google Sheets API?

Thanks,
Charlie

Charlie Salemi
DevOps Engineer
Nielsen Catalina Solutions
Office: 727-559-1131
Mobile: 732-208-8520
Email: Charlie.Salemi@ncsolutions.com  or ncvoperations@ncsolutions.com
Twitter: @ncsolutions
Website: www.ncsolutions.com

**Comment by nithinmurali** [comment]
Hi,
 It uses both. It mainly relies on sheets api. The drive api is used for getting the file list, deleting sheet, permissions etc

**Comment by casalemi** [comment]
I only have Google Drive enabled for my project.  Do I also need to enable
Google Sheets for that project as well?

Charlie Salemi
DevOps Engineer
Nielsen Catalina Solutions
Office: 727-559-1131
Mobile: 732-208-8520
Email: Charlie.Salemi@ncsolutions.com  or ncvoperations@ncsolutions.com
Twitter: @ncsolutions
Website: www.ncsolutions.com

**Comment by nithinmurali** [comment]
yes, please read the docs. Also use stackoverflow with `pygsheets` tag if you have any usage questions.

**Comment by casalemi** [comment]
Hi Nithin,

I installed the teamDrive package and added Google Sheets API to the project.  However, it is still unclear to me how open knows to open the spreadsheet on a Team Drive vs. a User Drive.   Also, I am using a Service Account to access the spreadsheet.  That seems to be giving me issues.  I am running the manual test you provided but getting failures:

-bash-4.2$ ./manual_test.py
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
./manual_test.py: line 7: from: command not found
./manual_test.py: line 8: syntax error near unexpected token `path.dirname'
./manual_test.py: line 8: `sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))'

Thanks.

**Comment by nithinmurali** [comment]
Hi, The `manual_test.py` dosent have a shebang set, so please run it as `python manual_test.py`. Also you will need to edit the manual_test to open your sheet in teamdrive. To enable teamdrive, add

```
gc.enableTeamDriveSupport = True 
gc.teamDriveId = "your id"

```

after the client is created.

**Comment by casalemi** [comment]
Thanks for that hint.  Still having issues.  The creds.json files in your manual test does not exist in the data directory:

CREDS_FILENAME = path.join(path.dirname(__file__), 'data/creds.json')
gc = pygsheets.authorize(outh_file=CREDS_FILENAME)

Do I need to provide those?  I only have the Service account info I created for my project.  Also, since this appears to be using the open() from gspread can I use my creds that way?

Thanks!

**Comment by nithinmurali** [comment]
Yes, you will need to provide those. please read the [docs](http://pygsheets.readthedocs.io/en/latest/authorizing.html#signed-credentials) on how to user service account. you can basically use ` # gc = pygsheets.authorize(service_file='./data/service_creds.json')`. you can see some commented lines for the same. Yes you can use the gspread way also, its given in the docs.

**Comment by casalemi** [comment]
Hi Nithin,  OK, I had a Python script that was working for me with a Service Account, now it is not.  This is what I get when I run both the updated Python script for teamDrive and my "good" Python script:

Traceback (most recent call last):
  File "./good.py", line 18, in <module>
    client = gspread.authorize(creds)
  .
.
.
  File "/home/yyy/.local/lib/python2.7/site-packages/oauth2client/client.py", line 744, in _refresh
    self._do_refresh_request(http)
  File "/home/yyy/.local/lib/python2.7/site-packages/oauth2client/client.py", line 812, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_client: The OAuth client was not found.

Any ideas?   Thanks!

**Comment by casalemi** [comment]
Got it working again for spreadsheets on my Google Drive.  Still can't access team drive spreadsheets even with the teamDrive ID and setting the enableTeamDriveSupport attribute to True.

BTW: what is the teamDrive ID and how do I find it?  Thanks!  I just took it off the URL of the team drive.  That sounds about right.  Thanks!

**Comment by casalemi** [comment]
Nithin,

Here's my code:

#! /usr/bin/python

import sys
import json
import gspread
import pygsheets

from oauth2client.service_account import ServiceAccountCredentials

ssheet = sys.argv[1] if len(sys.argv) >= 3 else ''
wsheet = sys.argv[2] if len(sys.argv) >= 3 else ''

# use creds to create a client to interact with the Google Drive API
scope = ['https://spreadsheets.google.com/feeds']
creds = ServiceAccountCredentials.from_json_keyfile_name('/home/xxx/gspread-test-95c0f0afdd6f.json', scope)
client = **pygsheets**.authorize(creds)

client.enableTeamDriveSupport = True
client.teamDriveId = "XXXXXXXXXXXX"

# Find a workbook by name and open the first sheet
# Make sure you use the right name here.
sheet = client.open(ssheet)
worksheet = sheet.worksheet(wsheet)

# Extract and print all of the values
list_of_hashes = worksheet.get_all_records()
print(list_of_hashes)

Here's the error:

  File "./plug.py", line 19, in <module>
    client = pygsheets.authorize(creds)
  File "/usr/lib/python2.7/site-packages/pygsheets/client.py", line 512, in authorize
    outh_nonlocal=outh_nonlocal)
  File "/usr/lib/python2.7/site-packages/pygsheets/client.py", line 450, in get_outh_credentials
    credentials = store.get()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/lib/python2.7/site-packages/oauth2client/file.py", line 45, in locked_get
    _helpers.validate_file(self._filename)
  File "/usr/lib/python2.7/site-packages/oauth2client/_helpers.py", line 250, in validate_file
    if os.path.islink(filename):
  File "/usr/lib64/python2.7/posixpath.py", line 142, in islink
    st = os.lstat(path)
TypeError: coercing to Unicode: need string or buffer, ServiceAccountCredentials found

**Comment by casalemi** [comment]
Nithin,  i did the install as suggested but when I looked at the /usr/lib/python2.7/site-packages/pygsheets/client.py file I did not see the updated code that was committed to the git repository under teamDriveSupport branch.  Probably one of the reason it's not working.  I am more than happy to try to help you test but I need your assistance to make sure I have things set up properly so you can pinpoint real issues.

**Comment by casalemi** [comment]
Hi Nithin,

Continued testing and I am almost there.  Here is the latest diagnostics from my testing:

-bash-4.2$ ./manual_test.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
Traceback (most recent call last):
  File "./manual_test.py", line 23, in <module>
    ss = gc.open('Team Drive')
  File "/home/xxx/.local/lib/python2.7/site-packages/pygsheets/client.py", line 159, in open
    return [Spreadsheet(self, id=x['id']) for x in self._spreadsheeets if x["name"] == title][0]
  File "/home/xxx/.local/lib/python2.7/site-packages/pygsheets/spreadsheet.py", line 31, in __init__
    raise InvalidArgumentValue
pygsheets.exceptions.InvalidArgumentValue
-bash-4.2$

Team Drive is the name of my Spreadsheet on my Team Drive.

**Comment by nithinmurali** [comment]
Are you able to open a spreadsheet on your account using this script?  if you are using the `manual_test.py`, it will use the package from the cloned repo, so make sure your clone repo is in `teamdriveSupport` branch.

**Comment by casalemi** [comment]
I'm not sure.  This is as far as I get trying to open a spreadsheet on my Team Drive with your code.  As I mentioned before I did the install as recommended using pip install "git repo".  Was that from the master branch or the teamDriveSupport branch?

**Comment by nithinmurali** [comment]
that would be from teamdirve, but if you did so you cant use the manual_test.py. Folow the instructions below:

- git clone <pygsheets repo>
- git checkout teamdriveSupport
- now replace the manual_test.py with attached file [manual_test.zip](https://github.com/nithinmurali/pygsheets/files/997191/manual_test.zip)
- insert values in the file as needed
- first check if a sheet in your account can be opened
- the uncomment lines for teamdrive support and test if a sheet on your team dirve can be acessed

**Comment by casalemi** [comment]
Hi Nithin,

I think I followed your instructions properly but I'm not 100% sure.  Either way, I have two Python scripts:  one that looks at a spreadsheet on my Google drive and it works fine:

-bash-4.2$ ./my_drive.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
<Spreadsheet u'My Drive' Sheets:3>
<Worksheet u'Test Sheet 1' index:0>

When I use another Python script (modified as suggested) to do the same thing with a spreadsheet on my Team Drive, this is what I get:

-bash-4.2$ ./team_drive.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
Traceback (most recent call last):
  File "./team_drive.py", line 15, in <module>
    ss = gc.open('Team Drive')
  File "/home/salech01/.local/lib/python2.7/site-packages/pygsheets/client.py", line 159, in open
    return [Spreadsheet(self, id=x['id']) for x in self._spreadsheeets if x["name"] == title][0]
  File "/home/salech01/.local/lib/python2.7/site-packages/pygsheets/spreadsheet.py", line 31, in __init__
    raise InvalidArgumentValue
pygsheets.exceptions.InvalidArgumentValue
-bash-4.2$

Any ideas?

**Comment by nithinmurali** [comment]
> File "/home/salech01/.local/lib/python2.7/site-packages/pygsheets/client.py", line 159, in open
> return [Spreadsheet(self, id=x['id']) for x in self._spreadsheeets if x["name"] == title][0]
> File "/home/salech01/.local/lib/python2.7/site-packages/pygsheets/spreadsheet.py", line 31, in init

Why is this using your installed pygsheets? Have you put the script in the `test` folder of the cloned  repo ?

**Comment by casalemi** [comment]
No, I put the cloned repo in this directory:  /home/salech01/.local/lib/python2.7/site-packages/pygsheets.

I'm sure I am doing something wrong.  Should I just be in the cloned directory on my Linux system and running my tests from there?  I know the "normal" google drive access is working as expected.  It is the teamDrive where I am having issues but that's expected as well.

**Comment by nithinmurali** [comment]
even in the teamDrive script, if you try to open a "normal" sheet , is it working? If so try to `print(gc.enableTeamDriveSupport)` right after `pygsheets.authorize`

**Comment by casalemi** [comment]
No Good:

-bash-4.2$ ./my_drive.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
Traceback (most recent call last):
  File "./my_drive.py", line 15, in <module>
    print(gc.enableTeamDriveSupport)
AttributeError: 'Client' object has no attribute 'enableTeamDriveSupport'
-bash-4.2$

**Comment by casalemi** [comment]
Should have come back False, correct?

**Comment by nithinmurali** [comment]
yes, That means you are not using the updated code in tramDriveSupport branch.

**Comment by casalemi** [comment]
Like I said, not sure if I followed your instructions fully.   I clone the code via download zip then transfer to my Linux system.  I have no idea where to put that code since I don't have root access to add it to the system location.  Then once I download the branch code where should that be copied to?

**Comment by nithinmurali** [comment]
> Should I just be in the cloned directory on my Linux system and running my tests from there? 
yes you can do that, you can try it on your local linux system.

> I clone the code via download zip then transfer to my Linux system.
I am attaching whole code, just download it and run the manual_test.py. You can place it wherever you want.
[pygsheets-teamdriveSupport.zip](https://github.com/nithinmurali/pygsheets/files/997767/pygsheets-teamdriveSupport.zip)

**Comment by casalemi** [comment]
OK, I installed you version of pygsheets on my Windows workstation.   Installed Python, and ran my tests.  Here are the results:

C:\Users\salech01\Downloads\Nithin\test>python team_drive.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
Traceback (most recent call last):
  File "C:\Users\salech01\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 154, in open
    ssheet_id = [x['id'] for x in self._spreadsheeets if x["name"] == title][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "team_drive.py", line 15, in <module>
    ss = gc.open('Team Drive')
  File "C:\Users\salech01\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 159, in open
    return [Spreadsheet(self, id=x['id']) for x in self._spreadsheeets if x["name"] == title][0]
  File "C:\Users\salech01\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\client.py", line 159, in <listcomp>
    return [Spreadsheet(self, id=x['id']) for x in self._spreadsheeets if x["name"] == title][0]
  File "C:\Users\salech01\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pygsheets-1.1.1-py3.6.egg\pygsheets\spreadsheet.py", line 31, in __init__
    raise InvalidArgumentValue
pygsheets.exceptions.InvalidArgumentValue

C:\Users\salech01\Downloads\Nithin\test>python my_drive.py
service_email : pygsheets@pygsheets-167412.iam.gserviceaccount.com
False
<Spreadsheet 'My Drive' Sheets:3>
<Worksheet 'Test Sheet 1' index:0>

C:\Users\salech01\Downloads\Nithin\test>

As you can see, I am now accessing your code (False return from my_drive.py) but the team_drive code is still failing.

**Comment by casalemi** [comment]
Looks like the same error I've been reporting....

**Comment by nithinmurali** [comment]
Ahh, that seems like a bug in the code. In the downloaded code in `spreadsheet.py` replace  line 30

`if type(jsonsheet) != dict and type(jsonsheet):`

with 

`if type(jsonsheet) != dict and jsonsheet is not None:`

**Comment by casalemi** [comment]
That did the trick!  Thanks!

**Comment by nithinmurali** [comment]
So, can you conform that pyghseets support teamdrive ?

**Comment by casalemi** [comment]
I was able to reach the spreadsheet on my Team Drive.  Let me do one more
check just to verify.

Charlie Salemi
DevOps Engineer
Nielsen Catalina Solutions
Office: 727-559-1131
Mobile: 732-208-8520
Email: Charlie.Salemi@ncsolutions.com  or ncvoperations@ncsolutions.com
Twitter: @ncsolutions
Website: www.ncsolutions.com

**Comment by casalemi** [comment]
I believe it is working as expected.  I can get to the spreadsheet and show there are three sheets associated with it as well as Test Sheet 1 being at index:0.

**Comment by nithinmurali** [comment]
See if `export` is working

**Comment by casalemi** [comment]
I will be happy to do that but help me understand how to.  I am new to both python and pygsheets.

**Comment by nithinmurali** [comment]
just run `ss.export()` (where ss is the spreadsheet object) this will export the spreadsheet as a csv file in your machine.

**Comment by casalemi** [comment]
Exported all three worksheets as single csv files (three files in all).  Is that the expected output?

**Comment by nithinmurali** [comment]
Yes, Thanks for testing. I will merge this with main branch.

**Comment by Aruloli** [comment]
Hi Nithin, How are you? My wife having few Google sheets with data asked me to make reports based those data. Before touching her drive,  I tested your code in my drive first and it worked perfect. When i tried in my wife's google account it shows following error. 
''ss = gc.open('chitra')
  File "C:\Users\Aruloli\Python\pygsheets-staging\pygsheets\client.py", line 136, in open
    spreadsheet = list(filter(lambda x: x['name'] == title, self.drive.spreadsheet_metadata()))[0]
IndexError: list index out of range'' 
When I open with gc.open_by_key & gc.open_by_url it works perfect but without many pygsheets methods
Pl help me. Arul

**Comment by nithinmurali** [comment]
@Aruloli Can you please create a new issue, so that we dont spam others in the this thread?

**Comment by Aruloli** [comment]
Very sorry. I am new to GitHub issues. I will do so
