### ISSUE TITLE
Different Users Access error

### ISSUE THREAD

**Issue by j2318** [nithinmurali/pygsheets#80]
Hi,
I have two processes accessing one Google sheet - when second process is accessing the sheet (diffrent user) I am getting this error:
**Unexpected error: <type 'exceptions.IOError'> [Errno 13] Permission denied: '/tmp/
.pygsheets_cache/sheets.googleapis.com,v4,spreadsheets,1YSo5QBlo6eagKruQIVCGmg-Oq9emCKp3e892sR1o430,fields=properties%2Csheets%2Fproperties%2Cspr
eadsheetId%2CnamedRanges&alt=json&includeGridData=false,ded17f3e63d32f48ef171491c49e4a63'**

-- Jacek

**Comment by nithinmurali** [comment]
Hi,
 As a quick workaround you can disable cache for one of the process. by setting `no_cache=True` of client.
