### ISSUE TITLE
spreadsheet updated method returns error

### ISSUE THREAD

**Issue by casalemi** [nithinmurali/pygsheets#83]
Trying to determine the last time a spreadsheet was updated using the spreadsheet updated method.  When I open a known spreadsheet via:

ss= gc.open(ssheet)

and then try to print the update information via;

updated = ss.updated()
print (updated)

This is my result:

Traceback (most recent call last):
  File "./get_updated_data.py", line 26, in <module>
    updated = ss.updated()
  File "/usr/lib/python2.7/site-packages/pygsheets-v1.1.1-py2.7.egg/pygsheets/spreadsheet.py", line 317, in updated
    response = self.client._execute_request(self.id, request, False)
  File "/usr/lib/python2.7/site-packages/pygsheets-v1.1.1-py2.7.egg/pygsheets/client.py", line 381, in _execute_request
    response = request.execute()
  File "/usr/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1rmb1_DGMmkvPbe6JFuMeSbhdAdwTJ_enSBlBaYlSHGc?fields=modifiedTime&alt=json returned "File not found: 1rmb1_DGMmkvPbe6JFuMeSbhdAdwTJ_enSBlBaYlSHGc.">

**Comment by nithinmurali** [comment]
Its working perfectly in my case. `updated` is a property, you are calling it as a function. Also in your case, api is returning a file not found error, which is kinda weird. Can you try the same for some other file?

**Comment by casalemi** [comment]
Hi Nithin,

Here's my code that works for the exact same spreadsheet when exporting worksheets:

#! /usr/bin/python

import os
import sys
import pygsheets

ssheet = sys.argv[1] if len(sys.argv) >= 3 else 'Campaign Exposure Tracking Sheet'
wsheet = sys.argv[2] if len(sys.argv) >= 3 else 'LiveRamp'

SCOPES = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.metadata.readonly']

gc = pygsheets.authorize(service_file='/xxx/shared/software/scripts/test/data/pygsheets.json')

gc.enableTeamDriveSupport = True
gc.teamDriveId = "XXX"

sys.stderr = open(os.devnull, "w")

ss = gc.open(ssheet)
sys.stderr = sys.__stderr__

#print (ss)
worksheet = ss.worksheet_by_title(wsheet)

#print("Exporting Team Drive spreadsheet")
#worksheet.export()

# Extract and print last time spreadsheet was updated
updated = ss.updated
print (updated)

Not sure why it can't find the specified file when it does for other requests.

**Comment by casalemi** [comment]
Bump

**Comment by nithinmurali** [comment]
Ahh, the `updated`  method was calling the api without the Teamdrive support, that's why it was unable to find your file.

**Comment by nithinmurali** [comment]
Please, reopen if this fix is not working

**Comment by jf-parent** [comment]
Hi,

Seem like the fixes #83 (cf6c28d) is not on the version 2.0.1, in fact it is not in the master branch (https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/drive.py#L65).

Can you re-include this fix?

Thanks
