### ISSUE TITLE
Cell.color always returns (1.0,1.0,1.0,1.0)

### ISSUE THREAD

**Issue by jalavosus** [nithinmurali/pygsheets#87]
Cell.color doesn't accurately reflect the background color of the sheet.

**Comment by jalavosus** [comment]
Looking through the Google Sheets API, the `includeGridData`parameter does return the background color in RGB format. I have confirmed this through my own testing as well. 

I'm not sure how your code handles the values it gets from spreadsheet().get(), but parsing each cell's background color would be incredibly helpful.

**Comment by nithinmurali** [comment]
By default, the cells are simple. So before accessing color, you should do a cell.fetch()

```
a = wks.cell('B3')
a.fetch()
a.color
```

**Comment by nithinmurali** [comment]
Update the docs about simple cells, and update fetch function doc.
