### ISSUE TITLE
set_dataframe fails when index is type int

### ISSUE THREAD

**Issue by usagliaschi** [nithinmurali/pygsheets#88]
Hi,

tool is great but I think I found a little bug. When attempting at writing a DataFrame with int type index the code breaks returning

"Object of type 'int64' is not JSON serializable"

Here below my dataframe, 
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
      <th>c</th>
      <th>d</th>
      <th>foo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-0.239328</td>
      <td>-0.607873</td>
      <td>0.939999</td>
      <td>0.748753</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.806135</td>
      <td>1.144164</td>
      <td>-1.027552</td>
      <td>1.181200</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.222877</td>
      <td>-1.098671</td>
      <td>-0.177695</td>
      <td>-1.250602</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1.554680</td>
      <td>0.013423</td>
      <td>1.269516</td>
      <td>2.295749</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.962001</td>
      <td>0.689026</td>
      <td>0.020453</td>
      <td>1.875726</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-0.164626</td>
      <td>-1.161630</td>
      <td>0.736164</td>
      <td>0.119247</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>6</th>
      <td>-0.214339</td>
      <td>1.506794</td>
      <td>-0.117659</td>
      <td>-2.283946</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>7</th>
      <td>-0.208547</td>
      <td>0.841456</td>
      <td>-1.053574</td>
      <td>-0.898233</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>8</th>
      <td>-2.227894</td>
      <td>-0.141375</td>
      <td>-0.196319</td>
      <td>1.287689</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>9</th>
      <td>-0.137098</td>
      <td>0.535600</td>
      <td>-0.157131</td>
      <td>0.756394</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.203198</td>
      <td>-0.074702</td>
      <td>0.020814</td>
      <td>1.172994</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.544010</td>
      <td>0.644651</td>
      <td>-0.902793</td>
      <td>-0.554629</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>12</th>
      <td>-0.003178</td>
      <td>0.961123</td>
      <td>-0.346739</td>
      <td>0.355867</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.401297</td>
      <td>0.155124</td>
      <td>0.968819</td>
      <td>0.040641</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0.359993</td>
      <td>1.101107</td>
      <td>0.149783</td>
      <td>-0.019702</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>15</th>
      <td>-0.574370</td>
      <td>-0.224871</td>
      <td>0.358658</td>
      <td>0.129561</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>16</th>
      <td>3.596789</td>
      <td>-0.083012</td>
      <td>-0.071461</td>
      <td>0.058319</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>17</th>
      <td>0.596427</td>
      <td>0.258036</td>
      <td>0.940905</td>
      <td>0.005854</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1.080344</td>
      <td>0.295176</td>
      <td>1.781685</td>
      <td>0.557361</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1.223156</td>
      <td>-2.268100</td>
      <td>0.662699</td>
      <td>0.028708</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>20</th>
      <td>0.157471</td>
      <td>-0.439025</td>
      <td>-0.659790</td>
      <td>-0.834769</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>21</th>
      <td>-1.181479</td>
      <td>0.260105</td>
      <td>-2.195900</td>
      <td>-1.110619</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>22</th>
      <td>0.028138</td>
      <td>1.403058</td>
      <td>0.657363</td>
      <td>-0.901635</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>23</th>
      <td>0.158918</td>
      <td>0.890882</td>
      <td>-2.372174</td>
      <td>0.679946</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0.208674</td>
      <td>-1.309359</td>
      <td>-1.134994</td>
      <td>-0.151899</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>25</th>
      <td>0.513415</td>
      <td>0.907455</td>
      <td>0.846958</td>
      <td>-2.056828</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>26</th>
      <td>0.227088</td>
      <td>0.965421</td>
      <td>-0.897194</td>
      <td>-0.842636</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>27</th>
      <td>-0.043356</td>
      <td>0.946692</td>
      <td>-0.430520</td>
      <td>1.457925</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>28</th>
      <td>-0.199506</td>
      <td>0.232850</td>
      <td>-2.670447</td>
      <td>-0.371889</td>
      <td>=2*B2</td>
    </tr>
    <tr>
      <th>29</th>
      <td>0.522627</td>
      <td>-0.715304</td>
      <td>0.894553</td>
      <td>-0.824867</td>
      <td>=2*B2</td>
    </tr>
  </tbody>
</table>

Thanks,
Umberto

**Comment by nithinmurali** [comment]
Hi, I am unable to reproduce the issue. Its working good with an integer index. I tested it with a small subset of your df. Can you show how exactly to creating this array (a subset). Also can you try with `copy_index=False` and see if its failling.
