### ISSUE TITLE
Add python3 to CI

### ISSUE THREAD

**Issue by petr-tik** [nithinmurali/pygsheets#91]
Travis.yml doesn't agree with the versions offered in the readme
```
language: python
python:
  - "2.6"
  - "2.7"
```

Should we add testing for python3?

**Comment by nithinmurali** [comment]
The travis uses the offline testes (mocked) which are almost non-existent (see `offline_test.py`) . I usually run the online tests (which actually calls the api). Unfortunately i don't have enough time to write mock tests. So it doesn't actually matter, still if you wish to make a PR i will accept it.
