### ISSUE TITLE
A few inconsistency in README.md

### ISSUE THREAD

**Issue by zhuliguang** [nithinmurali/pygsheets#94]
wks.update_cells(range='A1:E10', values=values_mat)
I think para range should be crange according to source

in cell operation,

cell_list = worksheet.range('A1:C7')
for cell in cell_list:
    cell.value = 'O_0'
 
worksheet.range('A1:C7') gives a list of lists, then each cell in cell_list would be a list of cells, therefore cell would not have value member

**Comment by nithinmurali** [comment]
Hi, Thanks for pointing this out.
