### ISSUE TITLE
Client.remove_permissions()  ignores 'emailAddress' of list_permissions if it has Uppercase chars

### ISSUE THREAD

**Issue by francixcoag** [nithinmurali/pygsheets#96]

**Comment by francixcoag** [comment]
Is it being used as intended? If that's the case sorry for taking your time

great job on this package nithinmurali's team!

**Comment by francixcoag** [comment]
to reproduce it,

add new permission in lowercase   (if in Uppercase, pygsheets rejects the email as it parses as Domain)
_ws.share("alexandrectag@gmail", role="writer")_

but list of permissions is returned with Uppercase
_ws.list_permissions()_
[{'id':13451234, 'type':'user', 'emailAddress':'AlexandreCTAG@gmail.com'}]

when removing permissions from Uppercase "AlexandreCTAG@gmail.com", parses the list of permissions but 
the key 'emailAddress' expects only lowercase, and the email is ignored by the regex
_ws.remove_permissions("AlexandreCTAG@gmail.com")


in the case of removing permissions from Lowercase "alexandrectag@gmail.com"
it doesn't find the user in the list of permissions, since the list of permissions has the user/emailAddress in Uppercase

**Comment by nithinmurali** [comment]
Hi, thanks for reporting this! it should be fixed by now. Can you please verify it by installing development version of pygsheets by running the below?
```
  pip install --upgrade https://github.com/nithinmurali/pygsheets/archive/staging.zip
```

**Comment by francixcoag** [comment]
It's fixed, good job!

thanks for the quick response
