### ISSUE TITLE
Text Align

### ISSUE THREAD

**Issue by shindig21** [nithinmurali/pygsheets#97]
Hi,

Sorry for the basic question, but I can't find where to horizontal-align the cell text anywhere... any ideas?

Thanks

**Comment by nithinmurali** [comment]
can you please elaborate on what horizontal alignment is? how to achieve this in web interface and/or a screenshot will do.

**Comment by shindig21** [comment]
Yep so a center-align would be:

![center-align](https://user-images.githubusercontent.com/25266193/27995981-fc70bb50-64cf-11e7-9b78-8432955a146c.png)

and left-align would be:

![left-align](https://user-images.githubusercontent.com/25266193/27995982-07ad0230-64d0-11e7-925f-1d3961b5631b.png)

thanks!

**Comment by nithinmurali** [comment]
This is not implemented as of now.

**Comment by nithinmurali** [comment]
Hi, this should fix the issue. Use `wks.set_text_alignment("TOP")`. Install latest version using 
```
pip install --upgrade https://github.com/nithinmurali/pygsheets/archive/master.zip
```

**Comment by shindig21** [comment]
Thanks very much.

I'm getting an error now on this call..

gc = pygsheets.authorize(service_file='client_secret.json', retries=5)

**Error:**
IOError: [Errno 2] No such file or directory: 'c:\\users\\nick\\appdata\\local\\temp\\fa15-d97b-43ca-8f7b-f4ba84ac3\\www.googleapis.com,drive,v3,files,includeTeamDriveItems=false&pageSize=500&fields=files%28id%2C+name%29&corpora=user&supportsTeamDrives=false&q=mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%,4ad0f84d69be2396dd368422a'

Do I need to modify anything with the new version?

Thanks again

**Comment by nithinmurali** [comment]
Try setting `no_cache=True` in authorize

**Comment by shindig21** [comment]
Hi,

Thanks - that worked.

Getting an error on the following code:

`wks.set_dataframe(df, (1, 1))`

**Error:**
  File "C:\Python27\lib\site-packages\pygsheets\worksheet.py", line 766, in set_dataframe
    self.update_cells(crange=crange, values=values)
  File "C:\Python27\lib\site-packages\pygsheets\worksheet.py", line 419, in update_cells
    self.client.sh_update_range(self.spreadsheet.id, body, self.spreadsheet.batch_mode, parse=parse)
  File "C:\Python27\lib\site-packages\pygsheets\client.py", line 339, in sh_update_range
    batch_length = int(batch_limit / len(body['values'][0]))  # num of rows to include in a batch
**TypeError: unsupported operand type(s) for /: 'tuple' and 'int'**

(sorry, it used to work)

**Comment by nithinmurali** [comment]
That looks like a bug. Can you please show your Dataframe? or a small sample?

**Comment by shindig21** [comment]
Yep...

df.info():

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 19 columns):
Adset ID          2 non-null object
Adset Name        2 non-null object
Mode              2 non-null object
Updated           2 non-null object
Budget            2 non-null object
Bid               2 non-null object
Spend/Min (hr)    2 non-null object
Spend Today       2 non-null object
PUR               2 non-null object
CPP               2 non-null object
ATC               2 non-null object
CPATC             2 non-null object
VC                2 non-null object
CPVC              2 non-null object
Last Log Time     2 non-null object
Last Action       2 non-null object
Sheet Name        2 non-null object
Night Mode        2 non-null object
Defib Level       2 non-null object
dtypes: object(19)

df:

            Adset ID                                         Adset Name  \
0  23842694790600488  2 ($1k) || MP1 MAX || LAA1% KVY PUR USD19...   
1  23842695314810488  MEGA($1k) || MP1 MAX || LAA2% KVY PUR USD...   

     Mode              Updated  Budget    Bid   Spend/Min (hr) Spend Today  \
0  Normal  2017-07-10 10:07:35  1000.0  13.35      🛀 $0.01 🛀        0.91   
1  Normal  2017-07-10 10:07:35  1000.0   16.7  0.0487037037037       18.12   


   PUR    CPP ATC CPATC  VC  CPVC   Last Log Time            Last Action  \
0  0.0    0.0   0   0.0   6  0.15  < 1 minute ago   Raising bid by $1.00   
1  1.0  18.12   2  9.06  43  0.42  25 minutes ago  Lowering bid by $0.10   

                  Sheet Name Night Mode Defib Level  
0    TATT-2 ($1k) || MP1 MAX       TRUE              
1  TATT-MEGA($1K) || MP1 MAX       TRUE

**Comment by nithinmurali** [comment]
I am unable to reproduce the issue. I think its probably because i cant reproduce your dataframe correctly.

**Comment by nithinmurali** [comment]
Can you write the df to a csv file (use `df.to_csv()`)  and attach it or mail me (imnmfotmal@gmail.com)? Also please start a new issue as this seems like a separate bug.
