### ISSUE TITLE
set_dataframe not working in new version

### ISSUE THREAD

**Issue by shindig21** [nithinmurali/pygsheets#99]
set_dataframe used to work perfectly, but since the newest version it is no longer working.

The code I'm using to set the dataframe is thus:

`wks.set_dataframe(df, (1, 1))`

Here is the error:

```
  File "C:\Python27\lib\site-packages\pygsheets\worksheet.py", line 766, in set_dataframe
    self.update_cells(crange=crange, values=values)
  File "C:\Python27\lib\site-packages\pygsheets\worksheet.py", line 419, in update_cells
    self.client.sh_update_range(self.spreadsheet.id, body, self.spreadsheet.batch_mode, parse=parse)
  File "C:\Python27\lib\site-packages\pygsheets\client.py", line 339, in sh_update_range
    batch_length = int(batch_limit / len(body['values'][0]))  # num of rows to include in a batch
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
```

I've tried 2 different full dataframes, as well as a blank dataframe, and a dataframe with 1 col / 1 row with a string, using:

```
        sh2 = gc.open(account.googlesheet)
        wks2 = sh.worksheet_by_title('Test')
        df2 = pd.DataFrame(columns=['name'])
        df2 = df2.append({'name': 'test'}, ignore_index=True)

        wks2.set_dataframe(df2, (1, 1))
```

The same error for all instances, which suggests is not an issue with the dataframe itself...

Using:

`df.to_csv('df.csv', encoding='utf-8')`

Couldn't attach so will email.

Thanks!

**Comment by nithinmurali** [comment]
Your dataframe is working well in my case. So as you said, its not an dataframe issue. Can you please check what is the value of `pygsheets.client.GOOGLE_SHEET_CELL_UPDATES_LIMIT`

**Comment by shindig21** [comment]
This is how I have it set normally:

`pygsheets.client.GOOGLE_SHEET_CELL_UPDATES_LIMIT = 10,000`

Tried at 100,000 and not setting it.  Same deal..

**Comment by nithinmurali** [comment]
Somehow in your case the batch_limit is becoming a tuple, eventhough it is set to a `GOOGLE_SHEET_CELL_UPDATES_LIMIT` [here](https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/client.py#L337).  

ohh, wait.  `10,000` is a tuple. I think that's the problem. its a tuple even without the brackets. Try  `pygsheets.client.GOOGLE_SHEET_CELL_UPDATES_LIMIT = 10000`

**Comment by shindig21** [comment]
Yesssssssss.

Thank you!

How funny it allowed the tuple before and not this time.  Thanks so much.  Text align working perfectly too.

Big thanks.  pygsheets is brilliant.

**Comment by nithinmurali** [comment]
This was implemented recently. So you might have been just setting it and the value was not getting used.
